### PR TITLE
rename KeyZipper to IterKeyZipper

### PR DESCRIPTION
**Pull request by pmeier**
Sister PR to pytorch/data#50.

### CODE REVIEW

**Review by NivekT — APPROVED** [review]
LGTM! @pmeier Is `MapZipper` used anywhere yet? If not, then I think we are set and I will let you know when I land my PR.

**Comment by pmeier** [comment]
> Is `MapZipper` used anywhere yet?

Nope and AFAIK we do not plan to use `MapDataPipe`'s anywhere.

**Comment by NivekT** [comment]
@pmeier FYI, I am in the process of landing the change in `TorchData`. I will let you know once that goes through. Thanks!

**Comment by NivekT** [comment]
The change has landed in TorchData. Let me know if you run into any issues.

**Pull request merged**
