### PR TITLE
Cleanup weight docs

### PR DESCRIPTION
**Pull request by NicolasHug**
This PR addresses my own comments from https://github.com/pytorch/vision/pull/6936#issuecomment-1313387747

Diff looks big but it's only a few lines in `conf.py` - the rest is just pure `s/x/y`

Before:

image

After:

image

Also renames the `_weight_size` key  into `_file_size` to avoid confusion with the actual size occupied in RAM by the weights, which is also something we want to document: https://github.com/pytorch/vision/issues/5982. For the same reason I removed the file size info from the main tables, because it may be more relevant to document the weight size there instead of the file size (and there is only so much column space available).

### CODE REVIEW

**Review by pmeier — COMMENTED** [review]
Just for my understanding: we are just changing the "keys" in the table to avoid showing the underscore which might be confusing and leaks implementation details, right? 

Plus, there is a doc failure: https://app.circleci.com/pipelines/github/pytorch/vision/22527/workflows/6df95767-c7cb-4078-9c9b-4235343bdb2d/jobs/1804785?invite=true#step-108-367

**Comment by NicolasHug** [comment]
> we are just changing the "keys" in the table to avoid showing the underscore

Mostly yes. I aslo renamed the (sort-of private) key from `_weight_size` to `_file_size` to avoid confusion, and removed the "Size" column from the big tables; this is because what we originally wanted to document was the weights size as in RAM, not the file size (https://github.com/pytorch/vision/issues/5982). But there's only so much info we can show in the table so I prefer waiting until we have the RAM usage info. The file size is still available in the individual models doc.

**Comment by NicolasHug** [comment]
Docs are OK now: https://output.circle-artifacts.com/output/job/ca9e66a9-b554-405e-888d-5807170f210a/artifacts/0/docs/models.html

**Review by pmeier — APPROVED** [review]
LGTM, thanks Nicolas!

**Pull request merged**
