### PR TITLE
Modify expected value and threshold for retinanet unit-test.

### LINKED ISSUE #2810: Empty expected values on test_retinanet_resnet50_fpn
## 🐛 Bug

The Unit-test expected values of RetinaNet are empty and thus the test does not protect us from breaking the code.

## To Reproduce

```
>>> import torch
>>> expected = torch.load("./test/expect/ModelTester.test_retinanet_resnet50_fpn_expect.pkl")
>>> print(expected)
[{'boxes': tensor([], size=(0, 4), requires_grad=True), 'scores': tensor([], requires_grad=True), 'labels': tensor([], dtype=torch.int64)}]

```

## Expected behavior

Ensure we have some non-trivial expected values so that we detect it when the code breaks. @fmassa advised to try and find a way that does not involve download pretrained weights.

### PR DESCRIPTION
**Pull request by datumbox**
Updating the score_thresh=0.013 for RetinaNet returns non-empty results. This fixes #2810.

### CODE REVIEW

**Review by fmassa — APPROVED** [review]
LGTM, thanks a lot !

Let's just wait until CircleCI gets back to normal before merging this PR.

**Comment by fmassa** [comment]
Test failures seem related (and happen only on GPU). Maybe there are duplicate detections somewhere and due to floating point errors we get a slightly off prediction?

If debugging / fixing this is hard, we can skip the numerical tests for retinanet on the GPU (while performing the other tests), and re-enable those later?

**Comment by datumbox** [comment]
@fmassa I agree. This is likely due to floating point errors, possibly made worse from the fact that all weights and input data are random. I'll have another look, hopefully we won't need to disable the GPU tests.

**Comment by datumbox** [comment]
Unfortunately there is numerical and sort instability on this unit-test across platforms. Given that currently on master we don't sufficiently test retinanet, I think it's worth putting at least some tests in. As a workaround I disable some of the cuda checks but I plan to revisit this once I have a proper GPU setup.

**Review by fmassa — APPROVED** [review]
Awesome, thanks a lot @datumbox !

**Pull request merged**
