### PR TITLE
Show built doc links directly in PR GUI -- v2

### PR DESCRIPTION
**Pull request by NicolasHug**
This is a second attempt at https://github.com/pytorch/vision/pull/3711, to show link to the rendered docs in the PR GUI. The first version worked but the `on: status` was creating issues with a internal system https://github.com/pytorch/vision/pull/3711#issuecomment-825823893

This version changed `on:status` to

```
on:
  pull_request:
    branches: [ master ]
```

which is what other actions ([CodeQL](https://github.com/pytorch/vision/blob/master/.github/workflows/codeql.yml) and [Bandit](https://github.com/pytorch/vision/blob/master/.github/workflows/bandit.yml)) are currently using. These other actions seem to be run on every commit and don't seem to bother the internal system, so hopefully that should be fine.

CC @bigfootjon

### CODE REVIEW

**Comment by NicolasHug** [comment]
Making this a draft, there's no point merging for now as the docs don't build anyway (upstream pytorch issue)

**Review by lastthyme — APPROVED** [review]

**Comment by NicolasHug** [comment]
@bigfootjon if you want I can let you merge this, so that if anything goes wrong you'd be able to quickly revert?

**Review by bigfootjon — APPROVED** [review]
I'll leave merging to you, but this LGTM

**Comment by NicolasHug** [comment]
I'll self merge since this is the same as https://github.com/pytorch/vision/pull/3711 which was already approved

**Pull request merged**
