### PR TITLE
Fixed the typo in the "Update viable/strict" workflow.

### PR DESCRIPTION
**Pull request by DanilBaibak**
Fixed the typo in the "Update viable/strict" workflow.

### CODE REVIEW

**Review by pmeier — APPROVED** [review]
LGTM, thanks @DanilBaibak! In other workflows that we don't typically run on a PR, we have this extra condition to run them in case the workflow is touched:

https://github.com/pytorch/vision/blob/f0a1df315db3c0fdec3d638895f6173809030bba/.github/workflows/tests-schedule.yml#L3-L8

So here this would be

```
on:
  pull_request:
    paths:
      - ".github/workflows/update-viablestrict.yml"
```

In addition, we only perform the actual action like reporting an issue or fast-forwarding the branch in case this happens on a schedule:

https://github.com/pytorch/vision/blob/f0a1df315db3c0fdec3d638895f6173809030bba/.github/workflows/tests-schedule.yml#L47-L49

With this setup you can avoid typo errors like this when working on the workflow, while not changing the actual functionality.

**Comment by DanilBaibak** [comment]
Yeah, let's add a trigger by modifying the workflow. Otherwise, it's hard to test the changes.

**Comment by pmeier** [comment]
Case in point: https://github.com/pytorch/vision/actions/runs/4488086872

**Comment by pmeier** [comment]
Workflow is green: https://github.com/pytorch/vision/actions/runs/4488123965/jobs/7892815057

**Pull request merged**
