### PR TITLE
Adapted SqueezeNet for Variable Size Input Images

### PR DESCRIPTION
**Pull request by sauhaardac**
Replaced final AveragePooling layer with an AdaptiveAveragePooling layer to allow for no code changes when switching from 255x255 images to other image sizes.

### CODE REVIEW

**Comment by fmassa** [comment]
Thanks for the PR.
According to the discussion in https://github.com/pytorch/vision/pull/155 , it might be preferable to add a constructor argument to switch between both behaviors. What do you think?

**Comment by sauhaardac** [comment]
The way I see it is, in the current code base any input image of a different size (bigger or smaller) causes the network to crash when run. When given an adaptive pool layer rather than fixed average pooling the network still runs as intended with 255x255 images for classification but also supports other image sizes with the same resultant behavior. I think in the case of other jobs such as segmentation (fully dense outputs), it should be up to the end user to make the necessary modifications since there are too many use cases to create arguments in the constructor for each case.

**Comment by fmassa** [comment]
I'm ok to merge this as is. Do you have an idea on how the network performs for different image sizes?

**Comment by apaszke** [comment]
If we're going to change this network shouldn't we change all other ones too? I'm not sure if it's a good idea, replacing a single layer should be quite straightforward and is more explicit

**Comment by sauhaardac** [comment]
Yeah I agree we should be replacing the other ones as well. If no one else
wants to I can take it on, but it may take me a few days since I'm still
pretty new to Pytorch and Deep Neural Nets. It should be a good learning
experience to go through and look at the structures of each of these nets
though.

**Comment by skrish13** [comment]
What's the status of this PR? It'd be cool to not have to change anything, but if there is some reason for keeping it the way it is, that's also cool, as @apaszke said, that's pretty straightforward.

**Comment by chao1224** [comment]
I happend to face same problem. I think at least it would be reasonable to add some comments in the code.

**Comment by fmassa** [comment]
This has been implemented in https://github.com/pytorch/vision/pull/643.

Thanks for the PR!

**Pull request closed without merging**
