### PR TITLE
Unpinned the libjpeg version and fixed jpeg_mem_dest's size type Wind…

### LINKED ISSUE #4181: RuntimeError: No such operator image::read_file on Docker
## 🐛 Bug

In a Docker environment, `torch.io.read_file` causes `RuntimeError: No such operator image::read_file`.

### 1. Setup a container

I used the following Docker file.

```dockerfile
FROM nvidia/cuda:11.0-base-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -qq \
    && apt install -y -qq \
    apt-utils \
    bzip2 \
    build-essential \
    cmake \
    curl \
    git \
    libncurses5-dev \
    libncursesw5-dev \
    libboost-all-dev \
    locales \
    nasm \
    ruby \
    sudo \
    swig \
    unzip \
    wget \
    zsh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV CONDADIR ${HOME}/.miniconda
RUN cd ${HOME} \
    && wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh \
    && bash miniconda.sh -b -p ${CONDADIR} \
    && rm miniconda.sh
```

```
docker build -t test .
docker run --rm -it test
# in the launched container
export PATH=.miniconda/bin:$PATH
conda create -n test python=3.9 -y
source activate test
conda install -c pytorch -c nvidia -c conda-forge pytorch torchvision cudatoolkit=11.1 numpy -y # another issue, but numpy is not automatically installed as a dependency
```

### Run the following

```python
import torchvision
torchvision.io.read_file(".")
# RuntimeError: No such operator image::read_file
```

## Environment

`collect_env.py` collects the following information (Docker v20.10.7).

```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-77-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0                     9_mkl    conda-forge
[conda] libcblas                  3.9.0                     9_mkl    conda-forge
[conda] liblapack                 3.9.0                     9_mkl    conda-forge
[conda] mkl                       2021.2.0           h06a4308_296
[conda] numpy                     1.21.0           py39hdbf815f_0    conda-forge
[conda] pytorch                   1.9.0           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchvision               0.10.0               py39_cu111    pytorch
```

## Additional context

I could not reproduce this issue in a non-Docker environment. A nightly build resolved this issue.

### PR DESCRIPTION
**Pull request by zzk1st**
Fixes #4181

### CODE REVIEW

**Comment by NicolasHug** [comment]
Thanks for working on this  @zzk1st !
Let's see what the CI says - as a reference for the current CI health, you can check out https://github.com/pytorch/vision/pull/3808

We'll also need to make sure everything works on the fbcode side before merging this. Is there a corresponding diff on fbcode? If not let us know and we'll help you import the changes from GH to fbcode.

**Review by datumbox — COMMENTED** [review]
Thanks for your PR.

I think this approach will work. I like you avoid using the preprocessor.  I left one comment concerning windows.

Before merging we should:
1. Check that this patch works with both pinned and unpinned JPEG. This will help us ensure the solution works across different platforms and versions.
2. Port this on FBcode and confirm that everything works there too.

The CI is currently a bit broken but based on what I see on master, it's only the `cmake_windows_gpu` job that should be failing. Worth checking that the current CI failures are not related.

**Review by datumbox — APPROVED** [review]
LGTM, good job @zzk1st. 

Let's do a quick check and add back the pinning to confirm that your solution works both with 9b and 9d versions.

Also before merging, we will check FBcode. We'll catch up for that internally.

**Comment by datumbox** [comment]
@zzk1st Looks like the patch works also with 9b. :)

Remove the pinning again and let's test this on FBcode.

**Comment by datumbox** [comment]
Thanks for the contribution @zzk1st!

**Comment by cprobert-insitro** [comment]
Hi @datumbox @zzk1st - Since this commit relaxes dependency constraints on the conda packages, I wanted to ask if there any chance you'd consider re-building/releasing the conda packages for `0.10.0` with this cherry-picked in? Or, could you provide any guidance on when `0.10.1` will be released (and if it will include this commit?). I am blocked on using `0.10.0` until this lands because of other packages depending on `jpeg=9d`.

**Comment by datumbox** [comment]
Thanks @cprobert-insitro 

The releases are coordinated along with PyTorch core, so it's something we can look into. I think if a revision is within the plans to be released (TBD) we can cherrypick this PR and fix the jpeg version issues.

**Pull request merged**
