### PR TITLE
fix fcos gt_areas calculation

### PR DESCRIPTION
**Pull request by simonJJJ**
I fix the gt_areas calculation in the FCOS model.

### CODE REVIEW

**Comment by simonJJJ** [comment]
Hi @datumbox , can you take a look of this?

**Review by datumbox — APPROVED** [review]
@simonJJJ LGTM, thanks a lot for patching this. This is definitely a typo which remained undetected.

@xiaohu2015 @zhiqwang @jdsgomes I assume this ended up having little effect on the overall accuracy. Do we want to retrain and confirm?

**Comment by xiaohu2015** [comment]
> @simonJJJ LGTM, thanks a lot for patching this. This is definitely a typo which remained undetected.
> 
> @xiaohu2015 @zhiqwang @jdsgomes I assume this ended up having little effect on the overall accuracy. Do we want to retrain and confirm?

yes, I think it maybe has little effect on the overall accuracy, becuase here we don't have many situations which one position match multiple GTs. But I think we should retrain the model if possible.

**Comment by xiaohu2015** [comment]
> I fix the gt_areas calculation in the FCOS model.

Thanks a lot

**Comment by jdsgomes** [comment]
Thanks for the fix @simonJJJ . I am running the training just to make sure the impact is not significant.

**Comment by jdsgomes** [comment]
> Thanks for the fix @simonJJJ . I am running the training just to make sure the impact is not significant.

I have re-run the training job and the performance difference does not seem significant.

With the fix: 
```
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.390
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.578
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.418
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.218
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.423
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.513
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.326
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.530
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.565
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.358
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.602
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.731
Training time 5:50:18
submitit INFO (2022-04-21 01:28:12,411) - Job completed successfully
```
Original results:
```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.392
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.582
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.420
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.222
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.423
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.513
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.324
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.529
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.562
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.350
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.609
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.728
 ```

So I don't think there is a need to update the pre-trained weights or take any further action. 

In any case thank you @simonJJJ   again for making the fix!

**Comment by datumbox** [comment]
Agreed. I don't think it's worth releasing a new pair of weights for 0.2 mAP. 

Soon we can try to retraining FCOS after #5410 is completed to really push its accuracy similarly to what we did with FasterRCNN and RetinaNet. This should give us a material push on the accuracy of several mAP points.

**Pull request merged**
