### PR TITLE
Add test for CIFAR10(0)

### PR DESCRIPTION
**Pull request by pmeier**
This adds test for the `CIFAR10` and `CIFAR100` datasets as mentioned in #1006.

### CODE REVIEW

**Comment by pmeier** [comment]
Seems like the `pickle.load()` within the dataset is not correct for python2. I don't have a environment set up to test python2. @fmassa Could you check this?

**Comment by fmassa** [comment]
@pmeier the pickle file seems to be Python3-only.

I see two options: 
- re-save and re-upload the pickle with pickle protocol 2 https://docs.python.org/3/library/pickle.html#data-stream-format 
- add the logic to generate dummy files in the test code, like in https://github.com/pytorch/vision/blob/ac2e995a4352267f65e7cc6d354bde683a4fb402/test/test_datasets.py#L27-L59

Given that you have generated the dummy file yourself, I think it might make sense to go for option 2, and plus the data generation logic stays in the code as well.

Thoughts?

**Comment by pmeier** [comment]
Should be fixed now. As a general thought: Do we want to do the fake data generation on-the-fly for all datasets? If yes, I think we should move the generation to a separate module to avoid cluttering the actual tests.

**Comment by fmassa** [comment]
> Do we want to do the fake data generation on-the-fly for all datasets? If yes, I think we should move the generation to a separate module to avoid cluttering the actual tests.

Yes, I think we should be doing it on-the-fly, and I agree that they should eventually be moved to a separate file.

**Pull request merged**
