### PR TITLE
Add test for loading pretrained weights

### PR DESCRIPTION
**Pull request by ekagra-ranjan**
Adds the test for checking whether the model can successfully load the pretrained weights besides outputting 1000 classes. Will raise an error if the model parameters are not properly defined or named according to the saved weights.

### CODE REVIEW

**Comment by fmassa** [comment]
While I agree with this tests, I'm afraid it will make tests more flaky in general (because it relies on being able to download a number of large files)

**Comment by ekagra-ranjan** [comment]
Oh, that is a valid point. So what do you suggest me to do?

**Comment by ekagra-ranjan** [comment]
Will passing num_class equal to a number other than 1000 help in making the test more enforcing in nature?

**Comment by soumith** [comment]
> Will passing num_class equal to a number other than 1000 help in making the test more enforcing in nature?



Yesss this would be great!

Closing the PR to avoid flaky tests.

**Pull request closed without merging**
