### PR TITLE
Make offset_groups an argument for deform_conv2d

### PR DESCRIPTION
**Pull request by jungomi**
The number offset groups had been calculated from the offset tensor `offset.shape[1] // (2 * weight_h * weight_w)`, which crashed with a floating point exception when the offset was smaller than the required size per group because of a division by zero (in the C++ code). Since the offset must be provided by the user, that's bound to happen and very unpleasant.

Furthermore, it was not consistent with the module `DeformConv2d`, which has an `offset_groups` argument that has been completely ignored, meaning that the offset tensor in the forward call determined the number of offset groups.

Considering that the offset needs to be manually supplied to the forward call of `DeformConv2d` and the fact that the number of offset groups had been configured in the constructor, it's reasonable to expect that the offset needs to adhere to that configuration and if it doesn't, it results in an error instead of silently choosing a valid number of groups.

### CODE REVIEW

**Comment by jungomi** [comment]
Yes that's definitely another way to do it, which is more focused on the functional application, whereas I had mostly the module in mind. The biggest reason for me to choose that side, was that not having the number of offset groups makes it very difficult to know the needed shape of the offset tensor. Currently it's given in the forward documentation as `Tensor[batch_size, 2 * offset_groups * kernel_height * kernel_width, out_height, out_width]`, so I know what those values need to be and I can resort to the default values if I don't specify them.

I'm absolutely fine with both solutions, but I'm wondering how the meaning of offset groups would be documented if it's not a parameter and only occurs in the shape of the offset tensor.

**Comment by fmassa** [comment]
> but I'm wondering how the meaning of offset groups would be documented if it's not a parameter and only occurs in the shape of the offset tensor.

I think this should be explicitly documented in the module documentation, and raise a good error message if it doesn't fit the expected sizes.
A similar thing already happens in `nn.Conv2d`, where the input shape has some restrictions (i.e., the number of input channels must match `self.weight.shape[1]`).

Thoughts?

**Comment by jungomi** [comment]
My reasoning was kind of based on `nn.Conv2d`, where you define all the necessary shapes in the constructor and the functional call is then handled by the module and you just need to respect the parameters you've chosen.

The pain point with `DeformConv2d` is having to deal with the offset manually instead of being abstracted by the module, which is the reason for this discussion. It has to be manual, so the user isn't forced to one particular offset calculation. So I would say it's less about the deformable convolution than the offset and how to calculate it and therefore its shape.

- `in_channels` must be divisible by `offset_groups` https://github.com/pytorch/vision/blob/6bf920b9e6321e50c744fbb500fcfd98c475aafe/torchvision/csrc/cpu/DeformConv_cpu.cpp#L299
- But `offset_groups` will be calculated with `offset_channels // (2 * kernel_width * kernel_height)` https://github.com/pytorch/vision/blob/6bf920b9e6321e50c744fbb500fcfd98c475aafe/torchvision/ops/deform_conv.py#L43

Naturally, I will fix the `offset_groups`, because that's the term that's represented in both and calculate the `offset_channels` as well as make sure `in_channels` fits as well.

I'm probably also biased because I would calculate the offsets with a convolution on the same input (as it's also done in Detectron2 for example). But by simply changing `offset_groups` the offset is automatically adjusted with the deformable convolution. It's best to show the abstraction I had in mind.

```py
import torch
import torch.nn as nn
from torchvision import ops
from torch.nn.modules.utils import _pair


class DeformConv2dWithOffsetConv(nn.Module):
    """Deformable Convolution where the offset is calculated by a convolution"""

    def __init__(
        self,
        in_channels,
        out_channels,
        kernel_size=3,
        padding=1,
        stride=1,
        offset_groups=1,
    ):
        super(DeformConv2dWithOffsetConv, self).__init__()

        kernel_width, kernel_height = _pair(kernel_size)
        offset_channels = 2 * kernel_width * kernel_height
        deform_channels = offset_groups * offset_channels

        self.conv_offset = nn.Conv2d(
            in_channels,
            deform_channels,
            kernel_size=kernel_size,
            padding=padding,
            stride=stride,
        )
        self.deform_conv = ops.DeformConv2d(
            in_channels,
            out_channels,
            kernel_size=kernel_size,
            padding=padding,
            stride=stride,
            offset_groups=offset_groups,
        )

    def forward(self, x):
        offset = self.conv_offset(x)
        out = self.deform_conv(x, offset)
        return out


# Default for offset_groups, therefore no additional restriction.
deform_conv1 = DeformConv2dWithOffsetConv(3, 30)
# in_channels are 30 hence offset_groups of 3 is valid.
# But offset_channels never needs to be considered even with a different kernel_size
deform_conv2 = DeformConv2dWithOffsetConv(30, 50, kernel_size=5, padding=2, offset_groups=3)

input = torch.randn((2, 3, 224, 224))
out1 = deform_conv1(input)
out2 = deform_conv2(out1)
```

I can of course do the same abstraction on top of the other API in torchvision, it's just what I hoped the `DeformConv2d` would be like.

I don't know how others would use it and what would be more intuitive to them.

**Comment by pedrofreire** [comment]
I think the most important issue here is that you should never get an error that is hard to understand (I think it is okay for a user-provided value to be of wrong dimension (which is inevitable) and raise an error, but this error should be reported in an extremely clear way that should be trivial to fix).

In this case, the forward in DeformConv_cpu.cpp and DeformConv_cuda.cu should guarantee that the dimensions are correct and throw a clear error otherwise.

I thought this was the case, but I guess if you have n_offset_grps == 0, then the divisibility check 
https://github.com/pytorch/vision/blob/6bf920b9e6321e50c744fbb500fcfd98c475aafe/torchvision/csrc/cpu/DeformConv_cpu.cpp#L299
is going to throw a division-by-zero error. The simplest ways to fix this seems to be to swap this check with the one that follows it (of `offset.size(1) == n_offset_grps * 2 * weight_h * weight_w`).

With that in mind, I agree that having the explicit offset_groups parameter should also make it clearer.

I also agree that it would be nice if there was an easy way to not have to care about the offset, as having to keep track of the offset yourself highly increases the complexity of making a DeformConv2d and I most people will probably use the offset in the default way. I guess it'd be possible to either have a new module like the DeformConv2dWithOffsetConv proposed ([this is also done in mmdet](https://github.com/open-mmlab/mmdetection/blob/b7894cbdcbe114e3e9efdd1a6a229419a552c807/mmdet/ops/dcn/deform_conv.py#L239)), or by having a boolean at DeformConv2d.\_\_init\_\_ that defines whether the offset is provided by the user or whether it is calculated internally, somewhat similar to how it is done with the bias).

**Comment by fmassa** [comment]
@jungomi 
> I'm probably also biased because I would calculate the offsets with a convolution on the same input (as it's also done in Detectron2 for example)

Detectron2 [does not have a `nn.Conv2d` internally in the `DeformConv` to calculate the offsets for you](https://github.com/facebookresearch/detectron2/blob/78cd72d63d5a15fe07de59c7a830201832e7da57/detectron2/layers/deform_conv.py#L343-L359).

I think it's up to the user to have their wrapper module that would combine a `nn.Conv2d` and a `DeformConv2d`. My reasoning is as follows: do we want to specify a different `kernel_size` for the `nn.Conv2d`? It might be reasonable to do so. In this case, do we expose it or not to the constructor? What if I want a `Conv ReLU Conv`?

Having a wrapper `DeformConv2dWithOffsetConv` is a possibility, but I think that it's so simple for the user to implement it that I would rather add it later rather than sooner.

I think that we should:
- fix the implementation to avoid the hard crash
- better document how the `offset` tensor should be
- raise a better error message for incompatible sizes
- remove `offset_groups` from `DeformConv2d`, as it's not necessary.

**Pull request closed without merging**
