### PR TITLE
Fix bug on autocontrast when `min==max`

### PR DESCRIPTION
**Pull request by datumbox**
Fixes issue reported by @ain-soph at https://github.com/pytorch/vision/pull/4995#issuecomment-980352057

cc @vfdev-5 @datumbox

### CODE REVIEW

**Comment by ain-soph** [comment]
Thanks for your response, but this fix doesn't seem to be correct?

You are replacing NAN with 1.0, which is not expected.

Constant across channel should still keep the value after autocontrast, rather than replacing them to 1.0.

Am I understanding autocontrast correctly?

**Comment by ain-soph** [comment]
Current fix seems to implement **(channel-wise)** normalization as I illustrated in https://github.com/pytorch/vision/pull/4995#issuecomment-980352057. Is this expected? Or shall we use **(image-wise)**?

**Comment by datumbox** [comment]
@ain-soph I believe the correct is to do channel-wise. 

I've added one more test that shows/confirms this. Below we are comparing the output of PIL vs TorchVision implementation for an image that has constant values across channels:
https://github.com/pytorch/vision/blob/35de04cd87d4b6eac361548093faed0644b6fece/test/test_transforms.py#L576-L582

**Comment by ain-soph** [comment]
That sounds nice.

**Review by fmassa — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
