### PR TITLE
Fix paper links of VGG models

### PR DESCRIPTION
**Pull request by NicolasHug**
Addresses part of https://github.com/pytorch/vision/issues/3681

### CODE REVIEW

**Comment by oke-aditya** [comment]
Will sphinx gallery work fine with Sphinx 2.4.4 ? In #3652 you mentioned latest sphinx does it better.

**Comment by NicolasHug** [comment]
I just tried and pushed a new commit in #3652 with 2.4.4 and yes, all seems well.
It was the really old sphinx 1.7 that we were using before that had  a problem with sphinx-gallery

**Comment by oke-aditya** [comment]
Great then we can stay with Sphinx 2.4.4. Al

**Review by datumbox — APPROVED** [review]
LGTM, thanks

**Pull request merged**
