### PR TITLE
Add Python-3.10 (build and test)

### PR DESCRIPTION
**Pull request by malfet**

### CODE REVIEW

**Comment by jdsgomes** [comment]
I think [these](https://app.circleci.com/pipelines/github/pytorch/vision/14805/workflows/ad497c35-6746-4580-a885-0ce33c384d39/jobs/1191566) fails can be solved by replacing  [this](https://github.com/pytorch/vision/blob/main/torchvision/transforms/functional_pil.py#L122) 

with   

`gamma_map = [round((255 + 1 - 1e-3) * gain * pow(ele / 255.0, gamma)) for ele in range(256)] * 3`

Looking at the code I believe this is equivalent and solves the float/int issue.

**Comment by malfet** [comment]
> 
> `gamma_map = [round((255 + 1 - 1e-3) * gain * pow(ele / 255.0, gamma)) for ele in range(256)] * 3`
> 
`round` or `int` (also, not sure which one is faster)?

**Comment by malfet** [comment]
Moved `adjust_gamma` change to https://github.com/pytorch/vision/pull/5427

**Comment by datumbox** [comment]
@jdsgomes We will probably need to cherrypick this on the release branch. I assume 3.10 support will be added in this release right?

**Comment by pmeier** [comment]
I'm guessing this is not synchronized with #5320? cc @vfdev-5

**Comment by datumbox** [comment]
@pmeier that was just a check, we can close the other one.

**Comment by pmeier** [comment]
Note that #5320 was mostly a superset of what is proposed here. It also handled the README compatibility table, as well as docker and OSX wheels.

**Comment by malfet** [comment]
> Note that #5320 was mostly a superset of what is proposed here. It also handled the README compatibility table, as well as docker and OSX wheels.

Wow, I wasn't aware of `osx_wheel.sh`, but at glance at this script it does not seem to be used (nor work) right now, so I propose we delete them in https://github.com/pytorch/vision/pull/5433

**Comment by datumbox** [comment]
Seems like the failing tests are due to dependency issues from core and numpy.

**Comment by datumbox** [comment]
@malfet @atalman I had a look at the failing tests and it seems the issues are related to dependencies issues from Core.

The `binary_win_conda_py3.10_cpu` [fails](https://app.circleci.com/pipelines/github/pytorch/vision/14858/workflows/0095d4e9-d938-4013-90bd-1444daa1fd4b/jobs/1195823) due to multiple conflicts:
```
Package pytorch-mutex conflicts for:
pytorch==1.12.0.dev20220207 -> pytorch-mutex==1.0[build='cuda|cpu']
pytorch-mutex==1.0=cpu

Package python conflicts for:
pytorch==1.12.0.dev20220207 -> typing_extensions -> python[version='>=2.7,<2.8.0a0|>=3.5|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
python=3.10
pytorch==1.12.0.dev20220207 -> python[version='>=3.10,<3.11.0a0']

Package setuptools conflicts for:
setuptools
python=3.10 -> pip -> setuptools
```

The `unittest_windows_cpu_py3.10` [fails](https://app.circleci.com/pipelines/github/pytorch/vision/14858/workflows/6c222461-14e8-4c8a-acc7-7b4d550667c9/jobs/1195810/steps) because PyTorch core has been compiled with a different version of numpy than the one installed:
```
Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe 
```

Nevertheless all other `unittest_windows_cpu_py*` jobs pass which makes me wonder if core gets compiled on the specific configuration with a different numpy version accidentally. 

I understand that these issues can be fixed upstream, but if you think otherwise let me know to further investigate. Thanks!

**Comment by malfet** [comment]
> The `binary_win_conda_py3.10_cpu` [fails](https://app.circleci.com/pipelines/github/pytorch/vision/14858/workflows/0095d4e9-d938-4013-90bd-1444daa1fd4b/jobs/1195823) due to multiple conflicts:
> 
> ```
> Package pytorch-mutex conflicts for:
> pytorch==1.12.0.dev20220207 -> pytorch-mutex==1.0[build='cuda|cpu']
> pytorch-mutex==1.0=cpu
> 
> Package python conflicts for:
> pytorch==1.12.0.dev20220207 -> typing_extensions -> python[version='>=2.7,<2.8.0a0|>=3.5|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
> python=3.10
> pytorch==1.12.0.dev20220207 -> python[version='>=3.10,<3.11.0a0']
> 
> Package setuptools conflicts for:
> setuptools
> python=3.10 -> pip -> setuptools
> ```
This was resolved by https://github.com/pytorch/builder/commit/3e6551ca3b205d17fa9570e747c87fdf8df1449c
> 
> The `unittest_windows_cpu_py3.10` [fails](https://app.circleci.com/pipelines/github/pytorch/vision/14858/workflows/6c222461-14e8-4c8a-acc7-7b4d550667c9/jobs/1195810/steps) because PyTorch core has been compiled with a different version of numpy than the one installed:
> 
> ```
> Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe 
> ```
> 
> Nevertheless all other `unittest_windows_cpu_py*` jobs pass which makes me wonder if core gets compiled on the specific configuration with a different numpy version accidentally.
> 
Seems to be connected to the previous failure

**Pull request merged**
