### PR TITLE
updating the code to import load_state_dict_from_urls from .hub instead of .utils

### PR DESCRIPTION
**Pull request by DIvyesh0204**

### CODE REVIEW

**Review by fmassa — CHANGES_REQUESTED** [review]
Hi,

Thanks for the PR!

Unfortunately we won't be able to get this PR merged.

Indeed, we rely on the `.utils` file internally so that we can replace `load_state_dict_from_url` with a custom implementation that works on our internal system.

So I'm closing this PR, but thanks again for having sent it!

**Comment by NicolasHug** [comment]
perhaps we should add a comment in `utils` indicating that it shouldn't be removed?

**Comment by fmassa** [comment]
@NicolasHug yes, I was going to propose the same thing. Can you send a PR with some comments?

**Comment by DIvyesh0204** [comment]
> Hi,
> 
> Thanks for the PR!
> 
> Unfortunately we won't be able to get this PR merged.
> 
> Indeed, we rely on the `.utils` file internally so that we can replace `load_state_dict_from_url` with a custom implementation that works on our internal system.
> 
> So I'm closing this PR, but thanks again for having sent it!

No problem, mam.

**Pull request closed without merging**
