### PR TITLE
pip install from PyPI

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by soumith** [comment]
let me know when the pip package is in pypi, i'll pull this in. thx!

**Comment by graingert** [comment]
@soumith to put the package on PyPI I'll need another version bump. Also what's your username on PyPI (register here: https://pypi.org/account/register/ )

**Comment by soumith** [comment]
hmmm, can we avoid the version bump? the current version is 0.1.6 across torch and torchvision and I dont want that to change at the moment.
My pypi username is: soumith

**Comment by graingert** [comment]
@soumith no. PyPI are very strict on that. You can't re-upload a new version of the same version.

**Comment by graingert** [comment]
@soumith you can upload packages to torch and torchvision now

**Comment by soumith** [comment]
hmm ok i will change the vision version in the setup.py for now to 0.1.6.1 if that's okay

**Comment by soumith** [comment]
actually, i see that the package is already on pypi. why do you need another version bump? just curious. https://pypi.python.org/pypi/torchvision/0.1.6

**Comment by graingert** [comment]
@soumith master currently has new code in it. To deploy new code you need to give it a new version

**Comment by graingert** [comment]
0.1.6.1 isn't a valid semver version

**Comment by soumith** [comment]
ok first i'm going to be pushing master into the branch v0.1.6
And then let's freeze 0.1.6 as-is. The pytorch version has been frozen as well.

After that, I'll simply empty-bump both version to 0.1.7 :-/

**Comment by soumith** [comment]
ok i have version bumped it to 0.1.7 and frozen it.

**Comment by soumith** [comment]
you can use the branch v0.1.7 to build the wheels.

**Comment by graingert** [comment]
If you do `python3 setup.py sdist bdist_wheel upload`

**Comment by graingert** [comment]
It should package it and upload it for you

**Comment by soumith** [comment]
thank you, i'll try that

**Comment by soumith** [comment]
this worked :)

```
python setup.py sdist bdist_wheel
twine upload dist/torchvision-0.1.7-py2.py3-none-any.whl
```

it is live. Thank you for all your help.

**Pull request merged**
