### PR TITLE
Support for ROIAlign Layer

### PR DESCRIPTION
**Pull request by varunagrawal**
- Fixes and improvements to ROIAlign forward pass.
- Working implementation and improvements of ROIAlign backwards for GPU & CPU.
- Tests based on results from Caffe2 to verify correctness.

Support for `autograd.gradcheck` is still needed.

### CODE REVIEW

**Comment by fmassa** [comment]
This is awesome, thanks!

There are some conflicts with this branch, can you rebase and add an `autograd.gradcheck` test, and the this is good to merge

**Comment by varunagrawal** [comment]
@fmassa done and done!

**Comment by fmassa** [comment]
Merged https://github.com/pytorch/vision/pull/632, so this is redundant, right?

**Comment by varunagrawal** [comment]
Yup. Closing this.

**Pull request closed without merging**
