### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by fmassa**
Original PR and fixes from https://github.com/pytorch/vision/pull/951 by @kerry-Cho, with the linter added.

Thanks a lot @kerry-Cho for the fixes!

### CODE REVIEW

**Comment by peterjc123** [comment]
cc @soumith

**Comment by TheCodez** [comment]
@fmassa now that this is fixed when is the windows pip release coming for 0.3.0?

**Comment by fmassa** [comment]
@TheCodez Windows wheels are already available, right? I think they are already live.

cc @peterjc123

**Comment by TheCodez** [comment]
@fmassa I tried it today and the latest was 0.2.2.post3
Also there’s no windows wheel listed under downloads on the pip website.

**Comment by fmassa** [comment]
Isn't this one working?
```
pip3 install https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp36-cp36m-win_amd64.whl
```

**Comment by peterjc123** [comment]
@fmassa I get 403 Forbidden when I tried to download the file. cc @soumith

**Comment by peterjc123** [comment]
@TheCodez Should be fixed now. Please try the installation steps on https://pytorch.org.

**Comment by TheCodez** [comment]
Thanks, it's working now 👍

**Pull request merged**
