### PR TITLE
Enable ONNX test in circle CI

### PR DESCRIPTION
**Pull request by jiafatom**
The [PR](https://github.com/pytorch/vision/pull/3137) disable onnx test since it is failing since 11/14/2020. ~~I did a test locally and find that onnx need update to 1.8.0. So This PR aims to enable onnx test by pulling latest onnx==1.8.0.~~
The root cause is that `onnx_shape_inference` is enabled on 11/13/2020, but the shape inference [PR](https://github.com/pytorch/pytorch/pull/44920) (committed 9/30/2020) does not handle invalid dynamic axes input well. In torch vision CI, there are some invalid axes, so we fixed it in this PR, and enable onnx test. In a separate pytorch PR, we add exception handling for invalid axes input, then it will give meaningful failure msg rather than seg fault here.

### CODE REVIEW

**Comment by jiafatom** [comment]
@fmassa I try to enable onnx test, it works in my local machine, but fails in the Ci build [here](https://app.circleci.com/pipelines/github/pytorch/vision/5422/workflows/0e0b549d-85a1-43ad-81ba-58ccfebdf2db/jobs/340899), it shows 
`free(): invalid next size (fast)`
which is a memory issue. Do you have any ideas on why this happen? thanks!

**Comment by fmassa** [comment]
Hi @jiafatom 

Thanks for the PR!

> Do you have any ideas on why this happen?

I don't know what could be the issue. This looks like something inside ORT might be problematic?

**Comment by jiafatom** [comment]
@fmassa Just fixed the issue, and test_onnx passes in CircleCI, could you please sign off? Thank you!

**Review by datumbox — APPROVED** [review]
Awesome work and investigation @jiafatom. Thanks for the PR.

**Comment by datumbox** [comment]
@jiafatom I think the test broke again, possibly due to upstream changes. Could you have a look on your side and confirm?

**Comment by jiafatom** [comment]
@datumbox 
Could you please show me the link of test broken? I am checking https://travis-ci.org/github/pytorch/vision/builds
The last time the master branch runs is 12/8/2020, that is 3 days ago, before this commits checked in.

The latest job failure is https://travis-ci.org/github/pytorch/vision/jobs/748808277
but this is a v0.8.2 branch, not related to this PR.

v0.8.2 did `pip install -q --user -i https://test.pypi.org/simple/ ort-nightly==1.4.0.dev202008122`
I cannot find this ort-nightly in pytorch/vision master.
This ort-nightly cannot be fetched, the possible explanation is that onnxruntime 1.6.0 released on 12/10/2020 (yesterday),
so some old ort-nightly is removed. 

Try to use `pip install --user -i https://test.pypi.org/simple/ ort-nightly==1.5.2.dev202012031` instead.
Please let me know if you have other questions. Thanks.

**Comment by fmassa** [comment]
@jiafatom check https://github.com/pytorch/vision/pull/3123 for example, where the only failing job is an ONNX test job.

**Comment by jiafatom** [comment]
@datumbox @fmassa 
There is a PR merged in pytorch at 12:30 pm 12/10/2020 (yesterday). That PR changes pytorch-onnx exporter API for a special case when the last input is a dictionary. So we need fix our unit test here.
The fix is [here](https://github.com/pytorch/vision/pull/3160), please sign off, thank you!

cc @spandantiwari

**Comment by spandantiwari** [comment]
Hi @fmassa  - thank you for your help with this. @jiafatom is working with our team. This latest PR https://github.com/pytorch/vision/pull/3160 should fix the test. It was broken because of a commit that went into PyTorch recently (just yesterday). It seems like there was a bit of difference in test running in PyTorch CI which is why this wasn't immediately detected for the PyTorch commit. We are going to update the version of tests running in PyTorch CI so that it matches vision tests with priority.
Thanks again for your help.

**Comment by datumbox** [comment]
@spandantiwari @jiafatom I confirm that the PR #3160 fixed the issue. Thanks a lot for your speedy response and support. We just merged the fix into master. Have great weekend.

**Comment by fmassa** [comment]
Thanks @jiafatom and @spandantiwari for the help!

**Pull request merged**
