### PR TITLE
Make read_file and write_file accept unicode strings on Windows

### PR DESCRIPTION
**Pull request by peterjc123**
Fixes https://github.com/pytorch/vision/issues/2931.

### CODE REVIEW

**Comment by peterjc123** [comment]
@fmassa The complicated thing here is that, conventionally, we should provide both the ascii version (e.g. `_read_file`) and the unicode version of the function (e.g. `_wread_file`) and make the choice according to the macro `_UNICODE` in the header file. But it will make the code look messy. Do you have any good suggestions here?

**Comment by peterjc123** [comment]
@fmassa Oh, I come up with a better idea. Since `pybind11` translates `filename` to a UTF-8 `std::string`, we just need to convert it to a Unicode string and then call the Unicode variants of the Windows APIs.

**Comment by peterjc123** [comment]
@fmassa BTW, could you please tell me a good place to host the unicode <-> utf8 util functions?

**Comment by fmassa** [comment]
Thanks a lot for the quick fix!

> could you please tell me a good place to host the unicode <-> utf8 util functions?

For now, you can either leave it in the body of the function as you currently did, or move it to the header of the file. We don't yet have a generic utils file for torchvision C++ (but we should at some point).



Additionally, can you take the `test_read_file_non_ascii` from https://github.com/pytorch/vision/pull/2946 and integrate it in your PR?

I'm thinking that I'll be cherry-picking this PR and integrating it in the dot release of torchvision which will be out in December.

**Comment by peterjc123** [comment]
@fmassa Thanks, and will do.

**Comment by peterjc123** [comment]
> I'm thinking that I'll be cherry-picking this PR and integrating it in the dot release of torchvision which will be out in December.

I guess sth like still needs to be done in PyTorch. So you may only cherry-pick it if there's also a dot release for PyTorch.

**Comment by fmassa** [comment]
There will be a dot release in PyTorch in December, but with this PR we can already fix this issue in torchvision right away, right?

**Review by fmassa — APPROVED** [review]
Thanks a lot @peterjc123 !

**Pull request merged**
