### PR TITLE
docs: add `NVCC_FLAGS` to build from source

### PR DESCRIPTION
**Pull request by plammens**
See #1076 and #1029.

### CODE REVIEW

**Comment by plammens** [comment]
How can coverage have decreased? I only touched a text file 🤔

**Comment by fmassa** [comment]
@plammens don't worry about that :-)

**Comment by peterjc123** [comment]
@fmassa Yes, that is a great idea. And you can try to wrap that with an if-clause `if USE_CUDA:`.

**Comment by peterjc123** [comment]
@fmassa Actually, this one needs to be done at the pytorch side for all the CUDA extensions. But I'm okay if you add it here first.

**Comment by fmassa** [comment]
Yes, we can add it here, and open an issue on PyTorch to explain the problem.
Once PyTorch implements the solution, we can remove it.

@peterjc123 can you open an issue in PyTorch explaining the problem, and maybe linking it to some torchvision issues and this PR?

**Comment by fmassa** [comment]
I believe this has been fixed in PyTorch in https://github.com/pytorch/pytorch/pull/22563

As such, I'm closing this PR, but please let me know if there is still something that needs to be done.

Thanks for the original PR @plammens !

**Pull request closed without merging**
