### PR TITLE
Remove Python linking dependency if USE_PYTHON=OFF

### LINKED ISSUE #5863: Python dependency added to TorchVisionConfig.cmake despite building with -DUSE_PYTHON=off
### 🐛 Describe the bug

Despite building `libtorchvision.so` with the flag `-DUSE_PYTHON=off`, when building a program that depends on it (`infer-masts`), `cmake` throws an error due to a missing Python dependency:
```
$ Torch_DIR=~/.local/lib/python3.9/site-packages/torch/share/cmake/Torch cmake -DTORCH_CUDA_ARCH_LIST="5.3;6.2;7.2" -Wno-dev -GNinja ..
...
CMake Error at CMakeLists.txt:24 (add_executable):
  Target "infer-masts" links to target "Python3::Python" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
Changing line 61 of TorchVisionConfig.cmake from
```
set_target_properties(TorchVision::TorchVision PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${${PN}_INCLUDE_DIR}" INTERFACE_LINK_LIBRARIES "torch;Python3::Python" )
```
to
```
set_target_properties(TorchVision::TorchVision PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${${PN}_INCLUDE_DIR}" INTERFACE_LINK_LIBRARIES "torch" )
```
allows my program to build without issues.

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0a0+gitbc2c6ed
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.20.4
Libc version: glibc-2.27

Python version: 3.9.10 (main, Mar 16 2022, 15:59:07)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.9.201-tegra-aarch64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.0.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] numpy-quaternion==2022.2.10.14.20.39
[pip3] torch==1.11.0a0+gitbc2c6ed
[pip3] torchvision==0.12.0a0+9b5a3fe
[conda] Could not collect
```
Note: This is on a Jetson Nano device. Python3.9, torch and torchvision were built with gcc-8, not gcc-7 as indicated by the collect_env.py script. Relevant environment variables are:
```
export BUILD_CAFFE2_OPS=OFF
export USE_FBGEMM=OFF
export USE_FAKELOWP=OFF
export BUILD_TEST=OFF
export USE_MKLDNN=OFF
export USE_NNPACK=OFF
export USE_XNNPACK=OFF
export USE_QNNPACK=OFF
export USE_PYTORCH_QNNPACK=OFF
export USE_CUDA=ON
export USE_CUDNN=ON
export TORCH_CUDA_ARCH_LIST="5.3;6.2;7.2"
export USE_NCCL=OFF
export USE_SYSTEM_NCCL=OFF
export USE_OPENCV=OFF
export MAX_JOBS=2
export PATH=/usr/lib/ccache:$PATH
export CC=gcc-8
export CXX=g++-8
```
torchvision was configured with the above environment variables and the command
```
torchvision-0.12.0/build$ cmake -Wno-dev -DWITH_CUDA=on -DTORCH_CUDA_ARCH_LIST="5.3;6.2;7.2" -DUSE_PYTHON=off -GNinja -DCMAKE_INSTALL_PREFIX=~/.local ..
```

### PR DESCRIPTION
**Pull request by laitingsheng**
A similar fix proposed previously by #5602 failed the CI tests. I made some amendments, and it is compilable in my environment.

It should now correct the problem raised in #5863 as well.

Closes #5602.
Resolves #5863.

### CODE REVIEW

**Review by datumbox — COMMENTED** [review]
The approach looks reasonable.

@fmassa Any thoughts around this?

**Review by fmassa — APPROVED** [review]
LGTM if tests passes!

Also, ccing @bmanga as you have originally implemented the cmake file

**Comment by fmassa** [comment]
Also, might be worth seeing if we can remove the following lines

https://github.com/pytorch/vision/blob/2e70ee1af3bb3c5ba0f9a8bcf16cd1611831690f/torchvision/csrc/vision.cpp#L17-L27

since this is what blocks us to have to include python (but this wasn't supposed to be the case). Maybe we can now remove this, or folks from torchaudio have found a different workaround since then? cc @mthrok

**Comment by laitingsheng** [comment]
> My intention is to wait a couple of days for the rest of the people to respond and merge afterwards. Please don't close the PR. Thanks in advance!

My pleasure.

> Right now our CI is still broken due to PyTorch upstream issues, so it's not a good time to test it. Let's wait until they are resolved (tracked at #5881) and then check what the CI things about them.

The quote is from comments under #5602. This is surprising to me as the tests failed again. Since I have permission to look at the CircleCI logs for my commit, I reckon this might be an issue due to the CI system environment. I guess the docker image `cimg/python` eliminates the shared object files of LibPNG to reduce the overall size, but I don't have a chance to check this. I suggest adding a preparation step like `apt-get install libpng-dev` to the CircleCI configuration.

**Review by datumbox — CHANGES_REQUESTED** [review]
@laitingsheng So in the previous commit, for some reason, the CI didn't run all the tests. I'm certain because I checked so I kicked the CI to rerun them.

Unfortunately the failings are related so to avoid accidental merges, I'll mark the PR with "Request Changes". If we can make the CI pass, I'll be happy to unblock. Apologies for the inconvenience.

**Comment by laitingsheng** [comment]
I found a related issue in python-pillow/Pillow#5813.

I think the error indicates that the shared object path resolution might be broken in the testing environment, but adding the Python target to the linkage dependency somehow resolves this issue. The last commit I pushed might solve the problem on CEntOS-based testing environments, but not on those running macOS.

From my perspective, it might be necessary to prune the whole building and testing scripts to actually resolve this issue, but this involves a large amount of work. I will now close my PR and see if any smarter coders could propose a better solution instead.

**Comment by datumbox** [comment]
@laitingsheng Understood, thanks for the effort!

**Pull request closed without merging**
