### PR TITLE
deprecate `tests/fakedata_generation.py`

### PR DESCRIPTION
**Pull request by pmeier**
With #3705 the last dataset was converted to the new test architecture. Thus, `tests/fakedata_generation.py` is no longer needed. Some internal FB code depends on the `CIFAR` fakedata generation. Thus, we leave them here in a BC way.

This should not be merged until it passes the FB internal checks.

### CODE REVIEW

**Comment by NicolasHug** [comment]
Thanks @pmeier , I'll import the PR to fbcode and report back

**Review by lastthyme — APPROVED** [review]

**Comment by NicolasHug** [comment]
Sorry for the delay on this, syncing was hectic lately.

This PR does seem to  break fbcode as one of the classyvision test is relying on this file. I'll try to see with them what can be done about this. For ref the diff is D28568302 (fb internal only)

**Comment by pmeier** [comment]
@NicolasHug could you try again? I fixed some logic and it should work now.

**Comment by pmeier** [comment]
Closed by #4130.

**Pull request closed without merging**
