### PR TITLE
Resnext

### PR DESCRIPTION
**Pull request by csarofeen**
Add ResNeXt to models.

### CODE REVIEW

**Comment by fmassa** [comment]
I think this looks good, thanks @csarofeen!
Quick question: do we have pre-trained models for resnext?

**Comment by skrish13** [comment]
@fmassa quick clarification, we'd need trained models with weights required to be added to PyTorch models right? (and not just the network arch) (takeaway from the discussion #260)

We can add that point to the README for guidelines towards contributing (will save time rejecting ones which dont follow them and also save effort for people who are writing and unaware)

Is there any unofficial library of sorts where we can compile different papers implementations in PyTorch, if so, we can redirect appropriate PRs like these there too!

**Comment by fmassa** [comment]
@skrish13 yes, we should add a mention to the README saying that the models should ideally be trained using the `imagenet` example with the same mean/std and preprocessing, so that the models are easily reproducible by others.

There are a number of repos with pytorch models.
One that comes to mind is https://github.com/Cadene/pretrained-models.pytorch, which has pre-trained pytorch models for which the weights were converted to pytorch from the original implementation.

But I do believe we should have some newer models that are proven to be better under the same training tricks, so that users have a good idea if the models are indeed better because of the architecture or just because of more tricks during training.

**Comment by fmassa** [comment]
This has been implemented in master, and I'm in the process of adding pre-trained weights. Thanks for the PR @csarofeen !

**Pull request closed without merging**
