### PR TITLE
Revert "Apply clipping in save_image"

### PR DESCRIPTION
**Pull request by ntomita**
Reverts pytorch/vision#119

Sorry, found an error and let me revert it.

### CODE REVIEW

**Comment by soumith** [comment]
what was the error?

**Comment by ntomita** [comment]
mistakenly used clip(), but should be clamp()
Now I have corrected and tested. Do you mind if I pull request again?

**Comment by soumith** [comment]
go ahead. those names are so similar, even I missed that mistake. :)

**Comment by ntomita** [comment]
thanks. that makes me feel better :)

**Pull request merged**
