### PR TITLE
Add translate and RandomTranslate

### PR DESCRIPTION
**Pull request by ekagra-ranjan**
This PR adds translate and RandomTranslate as a separate transformation like the rotation transformation.

### CODE REVIEW

**Comment by surgan12** [comment]
@ekagra-ranjan would be nice if you add some tests.

**Comment by ekagra-ranjan** [comment]
@surgan12 Yup! Will add them.

**Comment by ekagra-ranjan** [comment]
@fmassa Please have a look at the PR.

**Comment by fmassa** [comment]
Hi,

What's the difference between `translate` and a random crop?

**Comment by ekagra-ranjan** [comment]
If the user needs to randomly translate the image by some pixels then I think using `RandomTranslate` with its parameters will be more intuitive for the users (due to the straight forward naming of function and its parameter) rather than using `RandomCrop`. I agree that `RandomCrop` can get the same results but it is just that `RandomCrop`'s main function is cropping and not translate. Being able to give translated image as well is a sort of extension with the padding argument. 

@fmassa Your views on this?

**Comment by fmassa** [comment]
So, there was a PR in the past that already added a similar functionality https://github.com/pytorch/vision/pull/363

I was not convinced by then, because both performed the same thing in the end.

**Comment by ekagra-ranjan** [comment]
I think it is the connotation of RandomCrop that can get people confused about its application. 

Maybe we can add translation as a use case in the docs of RandomCrop just like there was a mention about whitening in the LinearTransformation (now AffineTransformation)?

**Comment by ekagra-ranjan** [comment]
@fmassa What are your views on addition of translation as a use case in RandomCrop?

**Pull request closed without merging**
