### PR TITLE
Install torch only if not present

### LINKED ISSUE #590: conda install installs PyTorch even if already present
Running `conda install torchvision -c pytorch` results in PyTorch  `0.4.1-py36_py35_py27__9.0.176_7.1.2_2` being installed for me, although I have a newer version compiled from source installed.

The requirements should be configured in a way that newer PyTorch versions are also accepted.
At a minimum, a note should be added to the Readme to install PyTorch _after_ installing `torchvision`.

### PR DESCRIPTION
**Pull request by vishwakftw**
Closes #590 

I think the binaries must reflect this as well.

### CODE REVIEW

**Comment by vishwakftw** [comment]
I went through https://github.com/pytorch/builder/tree/master/conda/torchvision-0.2.1, and noticed that the build command is `python setup.py install`, which is why I thought this would be a correct patch.

**Comment by soumith** [comment]
yes, but `pip install torchvision` directly installs the pre-built wheel file (`.whl`).  That wheel file is generated using `python setup.py bdist_wheel`, which also uses setup.py. So after your patch, the wheel no longer will depend on `torch`

**Comment by vishwakftw** [comment]
I am sorry if I am missing something here: the wheel would no longer depend on `torch` if `torch` is already installed, right? I did something like what was done for `pillow`.

**Comment by soumith** [comment]
The wheel encodes `static` list of dependencies. `setup.py` doesn't run again when the `pip install torchvision` is run. What's going to happen is this:

We create a `.whl` file by running `python setup.py bdist_wheel`. This will run the `setup.py` logic, and determine the conditional `requirements.append('torch')`, and then hardcode `requirements` into the wheel file.
Subsequent environments will just use that `statically` encoded `requirements` and wont execute `if get_dist('torch') is None:`

**Comment by vishwakftw** [comment]
Thank you for the explanation @soumith . Sorry to bother you about this. I will close this PR too.

**Pull request closed without merging**
