### PR TITLE
Fix shape mismatch error

### PR DESCRIPTION
**Pull request by prabhat00155**
Resolves https://github.com/pytorch/vision/issues/1884.

### CODE REVIEW

**Review by bjuncek — APPROVED** [review]

**Comment by bjuncek** [comment]
@datumbox LGTM, this partially resolves kinetics issue

**Comment by datumbox** [comment]
@prabhat00155 @bjuncek Thanks! Have we tested the patch and confirmed it works for training? 

What does partially means here?

**Comment by prabhat00155** [comment]
@bjuncek Were you able to test this on your setup?

**Comment by bjuncek** [comment]
So on my system that resolves dataset generation issue, but probably does not resolve accuracy issue (I can't test this due to only having one gpu).

**Pull request merged**
