### PR TITLE
Support float in `torchvision.io.video.read_video`

### PR DESCRIPTION
**Pull request by bryant1410**
`start_pts` can be `float` or `int`, depending on the value of `pts_unit`. [`float` typing considers both](https://stackoverflow.com/a/50928627/1165181).

### CODE REVIEW

**Comment by NicolasHug** [comment]
Thanks for the PR @bryant1410 

Looks like start_tps can also be a `Fraction`, according to the docstring. And it looks like we could update end_tps too.

**Comment by bryant1410** [comment]
Good catch!

**Comment by bryant1410** [comment]
The failing tests are unrelated to this change, right?

**Review by NicolasHug — APPROVED** [review]
LGTM, thanks @bryant1410 !
Yes, the failures are unrelated

**Pull request merged**
