### PR TITLE
Refactor mkdir function

### PR DESCRIPTION
**Pull request by yassersouri**
What I understood is the purpose of the `mkdir` function is to create the directories and not raise an error if the directories are already there, but raise other exceptions.

I think this simple refactoring does the same thing.

### CODE REVIEW

**Comment by yassersouri** [comment]
BTW, I just noticed that a similar function also exists in `references/detection/utils.py` and `references/segmentation/utils.py`.

I am not sure how you want to deal (if at all) with this code duplication.

**Comment by soumith** [comment]
afaik, this doesn't work on python2

**Comment by fmassa** [comment]
Thanks for the PR, but the reason why we have this function is precisely what @soumith mentioned: the `exists_ok` doesn't exist on Python2.

**Comment by yassersouri** [comment]
Sorry, I didn't know your policy regarding Python 2.

**Comment by fmassa** [comment]
@yassersouri no worries :-)

**Pull request closed without merging**
