### PR TITLE
Add Python 3.11 Linux CPU Unittesting

### PR DESCRIPTION
**Pull request by osalpekar**

### CODE REVIEW

**Comment by pmeier** [comment]
Hey @osalpekar, supporting 3.11 for us means that we'll have to wait until the conda defaults channel supports it as well as all of our dependencies for it. Unfortunately, `conda-forge` is not an option since we don't want to have builds from multiple channels. Thus, we'll just have to wait for now. There is #7108 that will include your change here minus the compatibility stuff.

**Comment by osalpekar** [comment]
Using this as a branch to do experiments, and I want to try out Nikita's suggestion from here: https://github.com/pytorch/vision/issues/7049#issuecomment-1412879108. Not necessarily planning on merging this, but using this to figure out all the blockers to 3.11 support.

**Comment by osalpekar** [comment]
Got all the 3.11 tests to run and pass, except for that depended on PyAV: https://github.com/pytorch/vision/actions/runs/4078992818/jobs/7029872042. 

In a previous commit, pyav installation failed, but it appears there are Python 3.11 manylinux wheels available for PyAV (https://files.pythonhosted.org/packages/55/ac/8c31205c9b49ea3e0111276a2f3ea8dae42dd026cee0832e46658c9a4650/av-10.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl), so will take a closer look at why those could not be installed earlier.

**Comment by pmeier** [comment]
`av==10.0.0` contains a bug that breaks our stuff. See #6790. This is why we don't install it:

https://github.com/pytorch/vision/blob/135a0f9ea9841b6324b4fe8974e2543cbb95709a/.circleci/unittest/linux/scripts/environment.yml#L16

https://github.com/pytorch/vision/blob/135a0f9ea9841b6324b4fe8974e2543cbb95709a/.github/workflows/test-linux-cpu.yml#L53

According to https://github.com/pytorch/vision/issues/6814#issuecomment-1410344508, the bug was fixed so we just need to wait for the next release to be able to support `av>=10`.

However, you are right than all versions for `av<10` don't have a wheel for Python 3.11. So not sure what to do about that.

**Comment by osalpekar** [comment]
Getting 16145 tests to pass, 7 are failing due to lack of appropriate `av` library which those 7 tests depend on.

**Comment by pmeier** [comment]
> 7 are failing due to lack of appropriate `av` library which those 7 tests depend on.

Nope, they are failing because we don't have any `av` installed. Since `av` is an optional dependency, we should not depend on it in the test suite either. Let me send a PR that removes this hard dependency to unblock this PR.

**Comment by pmeier** [comment]
@osalpekar Test is passing now: https://github.com/pytorch/vision/actions/runs/4144563519/jobs/7167774851

**Comment by osalpekar** [comment]
We can close this in favor of https://github.com/pytorch/vision/pull/7189

**Pull request closed without merging**
