### PR TITLE
replace remaining asserts

### PR DESCRIPTION
**Pull request by jdsgomes**
Replace torch._asserts as a follow up to this PR https://github.com/pytorch/vision/pull/5587

Thanks @datumbox for raising it in https://github.com/pytorch/vision/issues/5494

### CODE REVIEW

**Review by NicolasHug — APPROVED** [review]
Thanks @jdsgomes

**Comment by jdsgomes** [comment]
tests are failing because of this change: https://github.com/pytorch/vision/pull/5636/files#diff-678e419692ae76586d9f58ce62d2841be82d607637b7d507ead76eca412fcdd1R244

I am thinking to revert and leave this particular `torch._assert` because its traceable. 
@NicolasHug do you know if I have other options here?

**Comment by NicolasHug** [comment]
Sorry, I thought I had replied to this comment but it looks like I didn't :man_facepalming: 

I don't know if there is a good workaround for this. But I'm surprised that we did not encouter the same error for the changes we did in https://github.com/pytorch/vision/pull/5587. Do you know why that might be the case?

**Comment by datumbox** [comment]
I had a very quick look on https://github.com/pytorch/vision/pull/5587 and I think it works because all of our Exceptions are either on utils/methods that are not part of the models or on model constructors. I agree with jdgomes that we should probably close the PR and leave the assertions as is.

**Comment by NicolasHug** [comment]
Looks like even in https://github.com/pytorch/vision/pull/5587 there were a bunch of changes made to the forward pass of e.g. [RAFT](https://github.com/pytorch/vision/pull/5587/files#diff-695b16043168ca4717ef0ac674e2c78c3055e752616b0366a0b2608a40375db8R397), but it looks like we don't test RAFT against fx

**Comment by jdsgomes** [comment]
Abandoning this PR and will follow up with another PR reverting some of the recent exceptions added after the offline discussion with @datumbox

**Pull request closed without merging**
