### PR TITLE
setup.py

### PR DESCRIPTION
**Pull request by gujralsanyam22**
i fix some issues which i think is fixed in setup.py

### CODE REVIEW

**Comment by fmassa** [comment]
Thanks for the PR, but the changes that you have bring syntax error in the build, as can be seen from the CI.

As such, I'm closing this PR but let us know if you disagree

**Comment by gujralsanyam22** [comment]
I am disagree please make changes in it

**Comment by fmassa** [comment]
Could you please explain what issues you are trying to solve?

**Comment by gujralsanyam22** [comment]
I am solve the space issues and extra errors which terminate the program

**Pull request closed without merging**
