### PR TITLE
[proto] Simplified code in overridden transform forward methods

### PR DESCRIPTION
**Pull request by vfdev-5**

### CODE REVIEW

**Review by datumbox — APPROVED** [review]
LGTM, let's wait for the tests to confirm.

Should we apply the changes to `_RandomApplyTransform` and `_auto_augment.py` file? cc @pmeier

**Comment by pmeier** [comment]
> Should we apply the changes to `_RandomApplyTransform` and `_auto_augment.py` file?

Yes, we should be consistent where we can. AA might be not possible though, because we don't do the regular processing and need to put the augmented image back into the sample.

**Comment by datumbox** [comment]
@vfdev-5 The [failing](https://github.com/pytorch/vision/runs/8034716688?check_suite_focus=true) test is irrelevant; the flaky gaussian blur again. So not a blocker.

@pmeier Sounds good. Could you review this one to see if all the places changed are valid? I think Victor said that he changed everything that is currently safe to do.

**Comment by datumbox** [comment]
The [failure](https://github.com/pytorch/vision/runs/8036191934?check_suite_focus=true) is unrelated, merging.

**Pull request merged**
