### PR TITLE
[skip CI] try fix trigger for unlabeled PR pings

### PR DESCRIPTION
**Pull request by pmeier**

### CODE REVIEW

**Comment by datumbox** [comment]
@pmeier I got pinged incorrectly. I assume that's what you try to fix?
image

**Comment by pmeier** [comment]
@datumbox Yes. Could you link the PR where you were pinged? I can't see anything on #4011.

**Comment by datumbox** [comment]
It's the 4011 but I got it on the notifications panel.

**Comment by pmeier** [comment]
This probably happens for failed workflows that follow a push event on `master`. If this is done, the behavior should also go away.

**Comment by datumbox** [comment]
It's complaining because:
```
Run DATA=$(python .github/foo.py ea6be1240e5d83888b8d7fb08062496fa0c0c711)
python: can't open file '/home/runner/work/vision/vision/.github/foo.py': [Errno 2] No such file or directory
Error: Process completed with exit code 2.
```

I think this got fixed earlier in a different PR.

**Pull request merged**
