### PR TITLE
torchvision/models support load pretrained model from local system

### PR DESCRIPTION
**Pull request by LXYTSOS**
Sometimes we already have a pretrained model and we don't wish to download it again or put it in the default path where the download code will download a model into, I add some codes in the way keras does, so users can provide a local model path and load the pretrained model from it.

### CODE REVIEW

**Comment by fmassa** [comment]
Thanks for the PR!

Did you consider modifying instead the environment variable that is accessed in https://github.com/pytorch/pytorch/blob/655a37085935fa87b898d01fa5002d2be4c99d40/torch/hub.py#L438 ?
This enables the user-code to stay path-independent, and only the environment variable should be modified.

Thoughts?

**Comment by LXYTSOS** [comment]
Yes, we considered modify the environment variable, and it would work. But under another circumstance, we are developing a AI platform and will be deployed in a docker, we hope when we are coding we don't have to know what the environment variables are and which to modify, we just provide a model's path to it and it just can load it just like keras does, the programers don't have to know much about the underlying, they don't have to know which environment variable to modify to generate a correct path to the model they already have, what they want is convenience. 


In keras, users can provide a local model path to it if they don't want to download the model from online resources, so this is quite easy to manage the models, users can store the pretrained models wherever they want, and don't need to modify some environment variables(if the location changs, environment variables will be modified again), so I think PyTorch could learn this from keras and make it a easier job for the coders.




------------------ 原始邮件 ------------------
发件人: "Francisco Massa"<notifications@github.com>;
发送时间: 2019年6月26日(星期三) 下午5:22
收件人: "pytorch/vision"<vision@noreply.github.com>;
抄送: "刘翔宇"<834287447@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pytorch/vision] torchvision/models support load pretrained modelfrom local system (#1057)




Thanks for the PR!
 
Did you consider modifying instead the environment variable that is accessed in https://github.com/pytorch/pytorch/blob/655a37085935fa87b898d01fa5002d2be4c99d40/torch/hub.py#L438 ?
 This enables the user-code to stay path-independent, and only the environment variable should be modified.
 
Thoughts?

**Comment by LXYTSOS** [comment]
and according to these codes:
```
torch_home = os.path.expanduser(
        os.getenv(ENV_TORCH_HOME,
                  os.path.join(os.getenv(ENV_XDG_CACHE_HOME, DEFAULT_CACHE_DIR), 'torch')))
```
```
model_dir = os.path.join(torch_home, 'checkpoints')
```
the model path is hard coded, even we modify the environment variables we still should make sure that the model is under xxx/torch/checkpoints, and this is very unfriendly.

**Comment by fmassa** [comment]
I'm inclined to say that if the user knows a local path, then this can be accomplished with two lines:
```python
model = torchvision.models.resnet18()
model.load_state_dict(torch.load('path/to/file'))
```
or by changing the environment variable, and thus, we shouldn't add more complexity to the current functions.
If the model location change, they need to change their code anyway, so changing the environment variable is a way of keeping the code agnostic to its path.

Plus, torchvision doesn't provide out-of-the-box functionality to load a checkpoint for a different number of classes (like `models.resnet18(pretrained=True, num_classes=10)`, because there is not a single way of transferring the weights (should only the last classifier be changed? should we keep the weights for common classes?), as we think that this is problem-dependent.

I'm adding @soumith and @ailzhang to the discussion, as they have worked on the TorchHub, and those points are shared between both torchvision and TorchHub.

**Comment by loretoparisi** [comment]
@fmassa not sure I have understood, if I do

```python
model = torchvision.models.resnet18()
model.load_state_dict(torch.load('path/to/file'))
```

this will not load the file locally, because when I do 

```python
model = torchvision.models.resnet18()
```

it will immediately download the hosted model.

**Comment by fmassa** [comment]
@loretoparisi if you do `torchvision.models.resnet18()`, it defaults to `pretrained=False`, so the model won't be downloaded.

Following the prior discussion in this PR, I'm closing it, but thanks again for the PR and the discussion!

**Comment by loretoparisi** [comment]
ah so, btw I prefer to do like

```
os.environ['TORCH_HOME'] = '/app'
```

and then put local models into `/app/checkpoints/resnet18-5c106cde.pth`

So I can keep the code with `pretrained=True` (as I wanted to do)

**Comment by fmassa** [comment]
@loretoparisi great, thanks for the feedback!

**Pull request closed without merging**
