### PR TITLE
Drop virtual from private member functions of Decoder class

### PR DESCRIPTION
**Pull request by prabhat00155**
Only `SyncDecoder` class inherits `Decoder` class and I don't see any of these functions(marked virtual) being overwritten there.
enableLogLevel() and logCallback() functions being marked virtual is causing segfault when we cast [ void * to Decoder * ](https://github.com/pytorch/vision/blob/810811f81ca24b196d08778c9e7f50bc5fe3ef3d/torchvision/csrc/io/decoder/decoder.cpp#L111) and then call these virtual [functions](https://github.com/pytorch/vision/blob/810811f81ca24b196d08778c9e7f50bc5fe3ef3d/torchvision/csrc/io/decoder/decoder.cpp#L135). Objects of classes with virtual function have a VPTR data member pointing to the VTABLE. Since, we are type-casting to Decoder *  here, I think it doesn't have that information and hence throwing SIGSEGV.
For more information, check T91816044(FB internal task).

### CODE REVIEW

**Review by datumbox — COMMENTED** [review]
Given that the classes are public, have you checked if anyone else inherits it outside of TorchVision (Github and FBcode)? What if  we replace the `reinterpret_cast` with `dynamic_cast` and keep the fields virtual?

Edit:
Yeah that's not going to be a simple change:
```
decoder.cpp:106:17: error: 'void' is not a class type
      decoder = dynamic_cast<Decoder*>(context->opaque);
                ^                      ~~~~~~~~~~~~~~~
```

**Comment by prabhat00155** [comment]
> Given that the classes are public, have you checked if anyone else inherits it outside of TorchVision (Github and FBcode)? What if we replace the `reinterpret_cast` with `dynamic_cast` and keep the fields virtual?
> 
> Edit:
> Yeah that's not going to be a simple change:
> 
> ```
> decoder.cpp:106:17: error: 'void' is not a class type
>       decoder = dynamic_cast<Decoder*>(context->opaque);
>                 ^                      ~~~~~~~~~~~~~~~
> ```

I have not checked on GitHub. Here is the diff to check tests in fbcode with this change: D28995387.

**Comment by datumbox** [comment]
@prabhat00155 I was editing my reply as you were responding... That's the 2nd time this happens to me today. 😄  Check again...

**Comment by prabhat00155** [comment]
> Given that the classes are public, have you checked if anyone else inherits it outside of TorchVision (Github and FBcode)? ~What if we replace the `reinterpret_cast` with `dynamic_cast` and keep the fields virtual?~
> 
> Edit:
> Yeah that's not going to be a simple change:
> 
> ```
> decoder.cpp:106:17: error: 'void' is not a class type
>       decoder = dynamic_cast<Decoder*>(context->opaque);
>                 ^                      ~~~~~~~~~~~~~~~
> ```
> 
> Dynamic casting is not going to happen if we use void* pointers all over the place. Also I don't see any other way to make the following method compile and maintaining `readCallback ` virtual without changing the method signature and rewriting large parts of the code:
> 
> https://github.com/pytorch/vision/blob/810811f81ca24b196d08778c9e7f50bc5fe3ef3d/torchvision/csrc/io/decoder/decoder.cpp#L170-L176

Yeah, [opaque is a void *](https://ffmpeg.org/doxygen/4.0/structAVCodecContext.html).

**Review by datumbox — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
