### PR TITLE
port test_models_detection_utils.py to pytest

### PR DESCRIPTION
**Pull request by AnirudhDagar**
Port `test_models_detection_utils.py` to pytest. See #4033 for more details.

### CODE REVIEW

**Review by NicolasHug — APPROVED** [review]
LGTM when green, thanks :)

**Comment by AnirudhDagar** [comment]
CI timed out again. 

Btw what do you suggest for `assertAlmostEqual` in something like [this](https://github.com/pytorch/vision/blob/e27b3925c9c6bbcf7605c0cf8c6119339fec0e4e/test/test_hub.py#L34). I guess `pytest.approx` will be a good choice here. Or maybe we can go to `torch.testing.assert_close` defining some tolerance.

**Comment by NicolasHug** [comment]
For numbers, `assert x == pytest.approx(y)` is preferable. For iterables (lists, tensors, etc.) we can use `torch.testing.assert_close`

**Comment by NicolasHug** [comment]
Thanks!!

**Comment by AnirudhDagar** [comment]
> For numbers, `assert x == pytest.approx(y)` is preferable. For iterables (lists, tensors, etc.) we can use `torch.testing.assert_close`

Yeah, Thanks for the clarification!

**Pull request merged**
