### PR TITLE
(temporary) add `pyyaml` to unittest requirements

### PR DESCRIPTION
**Pull request by pmeier**
pytorch/pytorch#68772 added `pyyaml` as dependency and with pytorch/pytorch#68773 it is now a hard dependency when using `torch.jit.load`. Since it is not listed in `torch`'s dependency, we need to install it manually. 

I propose to merge this PR now and revert it as soon as this is resolved upstream.

cc @seemethere @tugsbayasgalan @gmagogsfm

### CODE REVIEW

**Review by fmassa — APPROVED** [review]
Ok to unblock, but let's not forget to remove it once PyTorch fixes it.

Can you add a comment on each line so that we remember to remove this?

**Comment by fmassa** [comment]
Issue to track this https://github.com/pytorch/pytorch/issues/69905

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Hmm, @pmeier looks like you`ve added `dependency issue` label which is mentioned in `process_commit.py`, why does it still complain about missing labels?

**Comment by cccclai** [comment]
https://github.com/pytorch/pytorch/issues/69905 is resolved. `pyyaml` can be safely removed.

**Pull request merged**
