### PR TITLE
Added defusedxml to parse untrusted XML data

### PR DESCRIPTION
**Pull request by mstfbl**
This PR fixes an issue pointed out by Bandit w.r.t. using the `xml` library to parse untrusted data, by using `defusedxml` instead.

Bandit output:
```
>> Issue: [B314:blacklist] Using xml.etree.ElementTree.parse to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.etree.ElementTree.parse with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called
   Severity: Medium   Confidence: High
   Location: ./torchvision/datasets/voc.py:206
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b313-b320-xml-bad-elementtree
```

### CODE REVIEW

**Review by fmassa — COMMENTED** [review]
LGTM, thanks!

Lint is failing, can you fix it so that we can merge the PR?

**Comment by fmassa** [comment]
One possible solution to the type checking is to disable it for defusedxml, as was done for some other libraries like https://github.com/pytorch/vision/blob/9e5edbd5fc3c844dd53686c4e781854b9b26cd8f/mypy.ini#L63-L65

**Comment by mstfbl** [comment]
Thank you @fmassa for your reviews and for merging the previous PRs. I have added the mypy type check disable for the `defusedxml` package.

**Review by fmassa — APPROVED** [review]
Thanks!

**Pull request merged**
