### PR TITLE
Replaced ToTensor with a combination of PILToTensor and ConvertImageDtype

### PR DESCRIPTION
**Pull request by prabhat00155**
Training logs before these changes: 
[training_log_no_changes.txt](https://github.com/pytorch/vision/files/7227958/training_log_no_changes.txt)
Training logs after these changes:
[training_log_after_changes.txt](https://github.com/pytorch/vision/files/7227959/training_log_after_changes.txt)

cc @datumbox

### CODE REVIEW

**Review by datumbox — APPROVED** [review]
The changes LGTM, but there are additional references of ToTensor in other places. I think it's worth removing them from code usages and documentation.

Here are some examples:



https://github.com/pytorch/vision/blob/c8e3b2a5925e7b7ed21662e86a7e9553170a5633/torchvision/transforms/transforms.py#L38
https://github.com/pytorch/vision/blob/c8e3b2a5925e7b7ed21662e86a7e9553170a5633/torchvision/transforms/transforms.py#L1573


https://github.com/pytorch/vision/blob/c8e3b2a5925e7b7ed21662e86a7e9553170a5633/references/detection/presets.py#L9
https://github.com/pytorch/vision/blob/c8e3b2a5925e7b7ed21662e86a7e9553170a5633/references/segmentation/presets.py#L14

Feel free to merge this PR if you want and open another one to address the rest, or do the changes here. Whatever works for you.

**Comment by prabhat00155** [comment]
> The changes LGTM, but there are additional references of ToTensor in other places. I think it's worth removing them from code usages and documentation.
> 
> Here are some examples:
> 
> https://github.com/pytorch/vision/blob/c8e3b2a5925e7b7ed21662e86a7e9553170a5633/torchvision/transforms/transforms.py#L38
> 
> 
> https://github.com/pytorch/vision/blob/c8e3b2a5925e7b7ed21662e86a7e9553170a5633/torchvision/transforms/transforms.py#L1573
> 
> https://github.com/pytorch/vision/blob/c8e3b2a5925e7b7ed21662e86a7e9553170a5633/references/detection/presets.py#L9
> 
> 
> https://github.com/pytorch/vision/blob/c8e3b2a5925e7b7ed21662e86a7e9553170a5633/references/segmentation/presets.py#L14
> 
> Feel free to merge this PR if you want and open another one to address the rest, or do the changes here. Whatever works for you.

Thanks @datumbox! I already replaced T.ToTensor() in [detection](https://github.com/pytorch/vision/blob/4ef8e6bc73368c21654b9cae95fcfbab04777bf8/references/detection/transforms.py#L47) and [segmentation](https://github.com/pytorch/vision/blob/4ef8e6bc73368c21654b9cae95fcfbab04777bf8/references/segmentation/transforms.py#L78) to be a combination of pil_to_tensor() and convert_image_dtype() in https://github.com/pytorch/vision/pull/4452. I'll update the example usages under torchvision in a separate PR.

**Comment by datumbox** [comment]
@prabhat00155 You are right, I missed the fact that we use a custom `ToTensor` class which internally calls the `F.pil_to_tensor()` and `F.convert_image_dtype()` methods. 

How would you feel about replacing the custom `ToTensor` class  from the segmentation/detection references with 2 similar wrapper classes called `ConvertImageDtype` and `PILToTensor`? This is just to reinforce the fact that ToTensor is not advised. It won't have any real effects on what you actually do. Let me know your thoughts.

**Comment by prabhat00155** [comment]
> @prabhat00155 You are right, I missed the fact that we use a custom `ToTensor` class which internally calls the `F.pil_to_tensor()` and `F.convert_image_dtype()` methods.
> 
> How would you feel about replacing the custom `ToTensor` class from the segmentation/detection references with 2 similar wrapper classes called `ConvertImageDtype` and `PILToTensor`? This is just to reinforce the fact that ToTensor is not advised. It won't have any real effects on what you actually do. Let me know your thoughts.

Yeah, sure. I can make that change.

**Pull request merged**
