### PR TITLE
Explicitly exclude PIL 8.3.0 from compatible dependencies

### PR DESCRIPTION
**Pull request by NicolasHug**
Closes https://github.com/pytorch/vision/issues/4146

CC @pmeier

### CODE REVIEW

**Review by pmeier — APPROVED** [review]
Thanks!

**Review by pmeier — CHANGES_REQUESTED** [review]
I think there are few more places where this needs to be pinned. At least some CI jobs still install `8.3.0`

**Comment by NicolasHug** [comment]
Should be good now, unittests jobs are passing. The same binary jobs failures are present in https://github.com/pytorch/vision/pull/3808, so they're unrelated.

**Review by pmeier — APPROVED** [review]
Stamp

**Pull request merged**
