### PR TITLE
Use ternary if in resize

### PR DESCRIPTION
**Pull request by NicolasHug**
Not very important, just making sure this works now

### CODE REVIEW

**Comment by NicolasHug** [comment]
We can use the ternary if now as it's been fixed in pytorch https://github.com/pytorch/pytorch/issues/53195
@fmassa is this worth merging or should I close?

**Review by fmassa — APPROVED** [review]
Thanks!

**Comment by datumbox** [comment]
I think it's good to fix things like that as we spot them. Shall we create a PR tag for code quality improvements so that we don't mark it as fix/improvement on the release notes?

**Comment by NicolasHug** [comment]
Agreed, I had created a new "refactoring" tag but "code quality" is probably better as it's more general - so I renamed the tag

**Pull request merged**
