### PR TITLE
`SanitizeBoundingBox` based on minimum area

### PR DESCRIPTION
**Pull request by antoinebrl**
During transformations, bounding boxes can be filtered based on minimum size and area.

### CODE REVIEW

**Comment by NicolasHug** [comment]
Thanks for the PR @antoinebrl , I'm curious about the applications where you found this feature useful?

**Comment by antoinebrl** [comment]
Hi @NicolasHug. Filtering by either size and/or area allows for more control when selecting bounding boxes with different aspect ratios. The smallest edge of a rectangle can be smaller that the sides of a square but the rectangle can occupy more space.

**Comment by NicolasHug** [comment]
Isn't passing `min_area=N` strictly equivalent to passing `min_size=sqrt(N)`?

**Comment by antoinebrl** [comment]
If you have square bounding boxes this would be equivalent indeed. However, if there are rectangles with one side ~3-4x longer than the other one, they cover a much larger area than squares with the same small edge. One might want to drop the small squares and keep the rectangles. This effect can be accentuated when resizing images without keeping the aspect ratio.

**Comment by NicolasHug** [comment]
To be clear, `min_size` will drop a bbox if **any** of H or W is lower than `min_size`. So passing `min_area=N` is equivalent to passing `min_size=sqrt(N)`.

taking `N = a * b`, the only way `a * b` to be lower than `N` is for either a or b to be less than `sqrt(N)`. I.e. both parametrizations are equivalent.

**Comment by pmeier** [comment]
Here is "proof" of Nicolas statement above

`a * b <= N` with `a, b, N > 0`

Assume `a = sqrt(N) + eps` with `eps > 0`

`(sqrt(N) + eps) * b <= N` <=> `b <= N / (sqrt(N) + eps) = sqrt(N) * sqrt(N) / (sqrt(N) + eps)`

With `c = sqrt(N) / (sqrt(N) + eps)` and `0 < c < 1`

=> `b <= sqrt(N) * c < sqrt(N)`

**Comment by antoinebrl** [comment]
The `min_size` only tells one thing about the removed bounding boxes. I made an sketch to illustrate the case I want to cover. In this scenario, how would you drop the square (considered too small) and keep both rectangles (who occupy a much larger region)?

Screenshot 2023-07-12 at 23 30 13

**Comment by pmeier** [comment]
Thanks for the sketch @antoinebrl! Here is a snippet to play with it:

```python
import math

import torch

from torchvision import datapoints
import torchvision.transforms.v2 as transforms
from torchvision.utils import draw_bounding_boxes
from torchvision.ops import box_area
from torchvision.transforms.v2 import functional as F


def draw(bounding_boxes, *, name):
    image = torch.zeros((3, *bounding_boxes.spatial_size), dtype=torch.uint8)
    annotated_image = draw_bounding_boxes(image, bounding_boxes, colors=["red", "green", "blue"])
    F.to_image_pil(annotated_image).save(f"{name}.png")


input = datapoints.BoundingBox(
    [
        [20, 20, 360, 80],  # large rectangle
        [30, 30, 70, 70],  # black square
        [40, 40, 380, 60],  # small rectangle
    ],
    format=datapoints.BoundingBoxFormat.XYXY,
    spatial_size=(100, 400),
)
draw(input, name="input")


areas = box_area(input)
square_area = int(areas[1])

transform = transforms.SanitizeBoundingBox(min_size=math.sqrt(square_area) + 1, labels_getter=None)
output_min_size = transform(input)
draw(output_min_size, name="output_min_size")

transform = transforms.SanitizeBoundingBox(min_area=square_area + 1, labels_getter=None)
output_min_area = transform(input)
draw(output_min_area, name="output_min_area")
```

input
output_min_size
output_min_area

You are right that just `min_size` there is no way that I see to just drop the square, but not the larger rectangle. What both @NicolasHug and I have neglected above is that we may want to keep bounding boxes that have a shorter side length but ultimately a larger size because of a large aspect ratio.

**Review by NicolasHug — APPROVED** [review]
I see, thanks for clarifying @antoinebrl . This is indeed not equivalent.

I wonder if we should just accept a filter callable (in addition to `min_size` which I think we should keep) so that users can pass arbitrary filters. @pmeier ?

**Comment by pmeier** [comment]
> I wonder if we should just accept a filter callable (in addition to min_size which I think we should keep) so that users can pass arbitrary filters.

IMO `min_size` and `min_area` are reasonably fundamental to have them as keywords. However, I agree that if anything else comes along we probably should just accept a callable instead of providing more builtin functionality.

**Comment by NicolasHug** [comment]
Alright, let's go with `min_area`. We'll see if users want more filtering strategies. Thanks a lot for the PR @antoinebrl , I took the liberty to resolve some merge conflicts with the latest branch and made some minor updates, but the PR was already in great state.

**Pull request merged**
