### PR TITLE
add v0.10 documentation, adjust versions.html

### PR DESCRIPTION
**Pull request by mattip**
This is the result of
- installing the pytorch 1.9 latest rc
- installing vision from the 0.10rc1 tag
```
cd docs
make html
cd ..
git checkout gh-pages
mkdir 0.10
cp -r docs/build/html/* 0.10
```

I also edited the versions.html to add the version documentation, and changed the symlink for stable to point to 0.10.

Please check carefully that there are no post-rc1 documentation changes (that belong in master and not the release).

### CODE REVIEW

**Comment by mattip** [comment]
A preview can be seen on my fork's github pages https://mattip.github.io/vision/0.10/, just be careful that some of the links lead off the site (like the version dropdown).

**Comment by mattip** [comment]
@brianjo

**Comment by mattip** [comment]
#4059 would have done most of this work when the 0.10 tag is created, @brianjo asked me to prepare this as a backup if it doesn't work

**Comment by mattip** [comment]
Even if creating the tag works, another PR will be needed to adjust stable -> 0.10 and to update the versions.html

**Comment by NicolasHug** [comment]
Thanks for the PR @mattip !

> Please check carefully that there are no post-rc1 documentation changes (that belong in master and not the release).

As long as you ran `make html` from the `0.10rc1` tag, there should be no issue right?

**Review by NicolasHug — APPROVED** [review]
@mattip this PR LGTM modulo confirmation of my previous comment https://github.com/pytorch/vision/pull/4061#issuecomment-861535818

Also IIUC, you suggest we wait and see if pushing the tag works properly before considering merging this PR, correct?

Thanks!

**Comment by mattip** [comment]
> As long as you ran make html from the 0.10rc1 tag, there should be no issue right?

I hope so. Sometimes the docstrings can be tricky, I don't know this repo well. I built a CPU version, does that matter?

> Also IIUC, you suggest we wait and see if pushing the tag works properly

Yes. Please ping me when it happens.

**Comment by NicolasHug** [comment]
> I hope so. Sometimes the docstrings can be tricky, I don't know this repo well. I built a CPU version, does that matter?

OK, as long as we didn't include anything in the v0.10 by mistake (which I doubt), everything should be OK. Building the docs on CPU is just fine. Thanks!

**Comment by NicolasHug** [comment]
> Even if creating the tag works, another PR will be needed to adjust stable -> 0.10 and to update the versions.html

@mattip should we do that before or after pushing the tag?

**Comment by mattip** [comment]
The versions.html and stable link should be adjusted after the final docs are in position, so after the tag/merging this PR.

**Comment by fmassa** [comment]
The tag has been created in https://github.com/pytorch/vision/releases/tag/v0.10.0

Let's see if the docs get built

**Pull request merged**
