### PR TITLE
Surface failing tests on GHA

### PR DESCRIPTION
**Pull request by pmeier**
Running a large test suite like `torchvision` results in really sluggish behavior of GitHub Actions. To counteract this somewhat, we recently merged #7267 although that meant we needed to give up the `-v` flag for the `pytest` invocation. As explained in 2. of https://github.com/pytorch/vision/pull/7267#issue-1587699682, this is not a big deal on CircleCI due to its ability to surface failing tests natively in a separate tab. GHA does not have this ability builtin, but I have written a small action that makes it possible: https://github.com/pmeier/pytest-results-action/

@NicolasHug, @vfdev-5

I've failed a few tests for demonstration purposes. To view them

- Click on the failing job: https://github.com/pytorch/vision/actions/runs/4305621879/jobs/7508327462
- Click on "Summary" at the top of the left sidebar: https://github.com/pytorch/vision/actions/runs/4305621879
- Scroll down until you reach the box for the workflow you are interested in (will only be visible after the workflow is complete): https://github.com/pytorch/vision/actions/runs/4305621879#summary-11691394136

I've reinstated the `-v` flag for a realistic experience. Could you try it and report back if this is good enough? IMO this is the best UX that we can get out of GHA. If we want more, we need other custom solutions.

@osalpekar @DanilBaibak

I've used this patch to upload the results: https://github.com/pytorch/test-infra/compare/3660cdcfa532b664dd3afdd6b25809725c065da2..c2ab5de5211b4eea97dd661a26c1f938645ee2c6. If we want to go that route, we should probably add a `test-results` parameter and only act if that is set.

### CODE REVIEW

**Comment by NicolasHug** [comment]
I'm sure I'll have more specific feedback  in the future after using this for a bit, but even in its current form the new summary is extremely useful. Thanks a lot @pmeier for working on it.

**Comment by pmeier** [comment]
pytorch/test-infra#3841 was merged and thus we can fully depend on this behavior now. 312f4dcbbf09b2250ddfcc3994ac1ca90c181653 will do a final showcase of the functionality. Afterwards, I'll revert caf522a1f9183d2f2b7c235877e3195938281e5e and thus only real failures will remain.

**Comment by NicolasHug** [comment]
Before stamping, who is in charge of maintaining `pmeier/pytest-results-action@v0.3.0`?
Will this be the nova team, or just you?

**Comment by pmeier** [comment]
Right now, it is just me. We didn't have any discussions around that. There are similar instances all over the `test-infra` repository, e.g. [here](https://github.com/pytorch/test-infra/tree/main/setup-ssh#usage).

@DanilBaibak is working on surfacing failing tests through the HUD as well. Right now it only shows you the failing job with the log, but this will be improved in the near future. Meaning, maintainers have two options to get the information and thus if for some reason I no longer can or want to maintain [pmeier/pytest-results-action](https://github.com/pmeier/pytest-results-action), we can just rip it out. Of course forking is always an option.

**Review by NicolasHug — APPROVED** [review]
> Right now, it is just me. We didn't have any discussions around that.

I'll stamp to unblock. However, I want to be clear upfront that while this is a **much needed** feature, this isn't something the torchvision engineers can maintain.

**Pull request merged**
