### PR TITLE
Create imagenet fakedata on-the-fly

### PR DESCRIPTION
**Pull request by pmeier**
This refactors the `ImageNet` test by creating the necessary data on-the-fly as discussed in #1010. @fmassa If this is OK, merge #1011 first and I will incorporate your changes in this PR.

### CODE REVIEW

**Comment by fmassa** [comment]
@pmeier I merged https://github.com/pytorch/vision/pull/1011, can you fix the merge conflicts?

**Comment by pmeier** [comment]
Shouldn't we use `get_file_path_2` everywhere as a replacement of `os.path.join` or did I misunderstood its purpose?

**Comment by fmassa** [comment]
@pmeier that was my original thought as well.

In fact, we only need to use it once to define the base root.
Internally, it might drop the first argument that we pass (which is generally related to `__file__`), and replaces it with another path.

The current state of things make (most) tests work for torchvision in fb, so I think that's ok

**Comment by fmassa** [comment]
@pmeier the rebase got a bit weird in the sense that changes from the first PR got integrated here.

I generally do a combination of
```
git pull --rebase origin master
```
and once the conflicts are resolved, I generally need to push with `--force` option.

**Comment by pmeier** [comment]
Thanks for the tip. I will try that next time. Git can be confusing if you never formally learned it / were introduced to it.

**Comment by fmassa** [comment]
No worries, let me have a look at your PR now and try to factor out the differences from the current master

**Comment by pmeier** [comment]
There are still differences? The GitHub GUI at least shows no conflicts. I did the following while on my branch:
```
git fetch origin
git rebase origin master
<fixed merge conflicts>
git add <previously conflicted files>
git commit -m <commit message>
git push
```

**Comment by fmassa** [comment]
What happened was that my commit appeared here as well. Anyway, I've merged the PR and it looks like GitHub did the right thing with the squash, so no worries :-)

**Pull request merged**
