### PR TITLE
box_rescale function to rescale bounding boxes to a new image shape

### PR DESCRIPTION
**Pull request by tflahaul**
Added a small function (+ doc) in the ops module to rescale bounding boxes to a new image shape.

(It's my first time contributing so I hope I'm doing it right)

### CODE REVIEW

**Review by datumbox — COMMENTED** [review]
Thanks for the PR @tflahaul, welcome to TorchVision!

Since it's your first contribution to the project, I'll just mention a couple of best-practices that maximize your chances of getting your PRs merged:
- When introducing a new major feature, it's often good to create first an issue and provide more information on your use-case. This will help other maintainers give feedback, offer alternatives or help you design the API.
- All new operators and public methods need to be covered by unit-tests, have proper documentation (which you do) and make use of proper typing (which again you do fine).

Given the above, could you add a brief description on your PR to explain what you would like to do? We are in the process of updating our detection transforms so noting your use-case will be helpful.

**Comment by tflahaul** [comment]
hey thanks for your feedback @datumbox ! And sorry for the messy PR haha, I'll follow your advices next time.

Here's some context: I made this function for my detection script because the model needed square images as input. But the bounding boxes outputted by the model are then based on the squared images and I had to rescale them to their original image sizes before drawing them. It's a very short & simple function but I thought it would be useful to many other ppl.

The function multiplies the x and y's by their respective ratios (original width & height / inputted width and height)

Hope this makes more sense, have a great day!

**Comment by datumbox** [comment]
@tflahaul No worries! Thanks for the context.

TorchVision already has a similar method here:
https://github.com/pytorch/vision/blob/b0601631ecd1afb841a312329d976c4c4a966acd/torchvision/models/detection/transform.py#L279-L293

It also offers transforms that handle masks, boxes, keypoints etc:
https://github.com/pytorch/vision/blob/b0601631ecd1afb841a312329d976c4c4a966acd/torchvision/models/detection/transform.py#L150-L173

Perhaps this covers your use-case?

**Comment by tflahaul** [comment]
Oh I had no idea this function existed but it does cover my case, thanks for letting me know!

Would it still be interesting to use my implementation for resize_boxes ? It needs a few tweaks but after running some tests I noticed an average speedup of about 28% on my CPU. And from looking at the code I guess using the slices would use a bit less memory too.

**Comment by datumbox** [comment]
@tflahaul Hmm, it's a tough call on this one...

At the moment, we are in the process of reviewing ways to improve the transforms for Detection, so having your use-case in mind is helpful. The problem with adding this PR in is that we already have a way to do the same thing. Our API is far from perfect and that's why we want to improve it but the functionality is already there. I think I'm weighting towards closing this PR and pinging you once we are ready to implement part of the Detection Transform API in case you want to contribute. This will give us time to finalize the API and reduce the BC-breaking changes. Thoughts?

BTW if you have time and you would like to contribute to the project have a look for issues tagged with "[good first issue](https://github.com/pytorch/vision/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)" and "[help wanted](https://github.com/pytorch/vision/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)". 😃

**Comment by tflahaul** [comment]
Yes I understand, this seems like the best thing to do right now.
Please notify me when you're ready and I'll have a look at the open issues in the meantime.

**Comment by datumbox** [comment]
@tflahaul Awesome, sounds like a plan!

**Pull request closed without merging**
