### PR TITLE
Fixed missing audio with video_reader backend

### PR DESCRIPTION
**Pull request by prabhat00155**
Resolves https://github.com/pytorch/vision/issues/3890.

```
video_path = "data/WUzgd7C1pWA.mp4"
set_video_backend('video_reader')
print(f'set backend: {get_video_backend()}')

visual, audio, info = read_video(video_path, pts_unit='pts')
print('Visual:', visual.shape, 'Audio:', audio.shape, info)

visual, audio, info = read_video(video_path, pts_unit='sec')
print('Visual:', visual.shape, 'Audio:', audio.shape, info)
---
Visual: torch.Size([327, 256, 340, 3]) Audio: torch.Size([523264, 1]) {'video_fps': 29.970029830932617, 'audio_fps': 48000.0}
Visual: torch.Size([327, 256, 340, 3]) Audio: torch.Size([523264, 1]) {'video_fps': 29.970029830932617, 'audio_fps': 48000.0}

video_path = "data/WUzgd7C1pWA.mp4"
set_video_backend('video_reader')
print(f'set backend: {get_video_backend()}')

visual, audio, info = read_video(video_path, start_pts=1001, pts_unit='pts')
print('Visual:', visual.shape, 'Audio:', audio.shape, info)

visual, audio, info = read_video(video_path, start_pts=0.0333667, pts_unit='sec')
print('Visual:', visual.shape, 'Audio:', audio.shape, info)
---
set backend: video_reader
Visual: torch.Size([326, 256, 340, 3]) Audio: torch.Size([521216, 1]) {'video_fps': 29.970029830932617, 'audio_fps': 48000.0}
Visual: torch.Size([326, 256, 340, 3]) Audio: torch.Size([521216, 1]) {'video_fps': 29.970029830932617, 'audio_fps': 48000.0}


video_path = "data//WUzgd7C1pWA.mp4"
set_video_backend('video_reader')
print(f'set backend: {get_video_backend()}')

visual, audio, info = read_video(video_path, start_pts=1001, end_pts=2002, pts_unit='pts')
print('Visual:', visual.shape, 'Audio:', audio.shape, info)

visual, audio, info = read_video(video_path, start_pts=0.0333667, end_pts=0.1001000, pts_unit='sec')
print('Visual:', visual.shape, 'Audio:', audio.shape, info)
---
set backend: video_reader
Visual: torch.Size([2, 256, 340, 3]) Audio: torch.Size([2048, 1]) {'video_fps': 29.970029830932617, 'audio_fps': 48000.0}
Visual: torch.Size([3, 256, 340, 3]) Audio: torch.Size([3072, 1]) {'video_fps': 29.970029830932617, 'audio_fps': 48000.0}
```

### CODE REVIEW

**Review by datumbox — COMMENTED** [review]
The changes look good. Do you think we should put a unit-test to test for this case?

**Review by datumbox — APPROVED** [review]

**Comment by prabhat00155** [comment]
> The changes look good. Do you think we should put a unit-test to test for this case?

Yeah that makes sense, added the unit test.

**Review by datumbox — CHANGES_REQUESTED** [review]
[This failing test](https://app.circleci.com/pipelines/github/pytorch/vision/8498/workflows/acb79c59-a46c-4861-9620-7c2fbf264051/jobs/613296) seems related. Marking as requires changes to avoid accidental merges. Let's check it out next week. :)

**Comment by datumbox** [comment]
Following the reported internal issue, I took this patch and applied it on latest master:
```
$ git diff
diff --git a/torchvision/io/_video_opt.py b/torchvision/io/_video_opt.py
index a34b023b..e92ac1bd 100644
--- a/torchvision/io/_video_opt.py
+++ b/torchvision/io/_video_opt.py
@@ -155,7 +155,7 @@ def _align_audio_frames(aframes, aframe_pts, audio_pts_range):
     e_idx = num_samples
     if start < audio_pts_range[0]:
         s_idx = int((audio_pts_range[0] - start) / step_per_aframe)
-    if end > audio_pts_range[1]:
+    if audio_pts_range[1] != -1 and end > audio_pts_range[1]:
         e_idx = int((audio_pts_range[1] - end) / step_per_aframe)
     return aframes[s_idx:e_idx, :]
 ```


Then opened the same file as on the bug report:
```
>>> from torchvision.io import read_video
>>> vid_path = "./---0tKA3iYI.mp4"
>>> vid, aud, meta = read_video(vid_path, 1, 2, pts_unit="sec")
>>> vid.shape
torch.Size([31, 360, 204, 3])
>>> aud.shape
torch.Size([1, 0])
```

So it seems that the problem persists. Thoughts?

**Comment by prabhat00155** [comment]
> Following the reported internal issue, I took this patch and applied it on latest master:
> 
> ```
> $ git diff
> diff --git a/torchvision/io/_video_opt.py b/torchvision/io/_video_opt.py
> index a34b023b..e92ac1bd 100644
> --- a/torchvision/io/_video_opt.py
> +++ b/torchvision/io/_video_opt.py
> @@ -155,7 +155,7 @@ def _align_audio_frames(aframes, aframe_pts, audio_pts_range):
>      e_idx = num_samples
>      if start < audio_pts_range[0]:
>          s_idx = int((audio_pts_range[0] - start) / step_per_aframe)
> -    if end > audio_pts_range[1]:
> +    if audio_pts_range[1] != -1 and end > audio_pts_range[1]:
>          e_idx = int((audio_pts_range[1] - end) / step_per_aframe)
>      return aframes[s_idx:e_idx, :]
> ```
> 
> Then opened the same file as on the bug report:
> 
> ```
> >>> from torchvision.io import read_video
> >>> vid_path = "./---0tKA3iYI.mp4"
> >>> vid, aud, meta = read_video(vid_path, 1, 2, pts_unit="sec")
> >>> vid.shape
> torch.Size([31, 360, 204, 3])
> >>> aud.shape
> torch.Size([1, 0])
> ```
> 
> Not sure if it's the same issue or a different one. Thoughts?

Sorry, the current PR fixes missing audio with `video_reader` backend
```
set_video_backend('video_reader')
```
By default, we use `pyav` backend, which returns empty audio frames: https://github.com/pytorch/vision/issues/3779.

**Review by datumbox — DISMISSED** [review]
@prabhat00155 thanks for the PR, LGTM.

**Comment by prabhat00155** [comment]
> @prabhat00155 thanks for the PR, LGTM.
> 
> Edit:
> Unfortunately I see a segmentation fault that looks relevant. See [unittest_linux_cpu_py3.9](https://app.circleci.com/pipelines/github/pytorch/vision/8993/workflows/323bbe98-0e30-41a6-8219-dd7306338c63/jobs/655866)

The seg fault was caused by incompatible ffmpeg version, which was fixed in https://github.com/pytorch/vision/pull/4041. It should be fine now.

**Review by datumbox — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
