### PR TITLE
Check sha256 of weights

### LINKED ISSUE #7210: WeightsEnum: use checksums
### 🚀 The feature

All weight enums should store and use the MD5 checksum in order to verify the integrity of the download. We already do the same thing for datasets, and weights should be no different.

### Motivation, pitch

When weight enums are passed to a model, torchvision calls `WeightsEnum.get_state_dict`, which calls `torch.hub.load_state_dict_from_url`, which downloads the weights and calls `torch.load`, which uses pickle to load the data. However, [pickle's documentation](https://docs.python.org/3/library/pickle.html) notes that the pickle format is not secure and the pickle format can allow for arbitrary code execution. For security reasons, it's recommended to first verify the checksum of any pickled files before unpickling.

### Alternatives

_No response_

### Additional context

It's unclear exactly where the checksum should be used. Honestly, we should really add a MD5 check directly in `torch.hub.load_state_dict_from_url`. Otherwise, we'll have to split the download and the load into two separate steps in torchvision so that we can verify the checksum in the middle.

@NicolasHug

### PR DESCRIPTION
**Pull request by adamjstewart**
@NicolasHug @nps1ngh @pmeier would this be sufficient to close #7210? This should be fully backwards compatible in case someone wants to use weights without a sha256 hash suffix. We'll rename all of our weights in TorchGeo to add the suffix.

### CODE REVIEW

**Comment by adamjstewart** [comment]
Ping @NicolasHug

**Comment by NicolasHug** [comment]
After the release please @adamjstewart  :) https://github.com/pytorch/vision/issues/7210#issuecomment-1424549455

**Comment by adamjstewart** [comment]
Would love to get this into the release but if it's past the feature freeze it can wait.

**Comment by pmeier** [comment]
@adamjstewart Branch cut was last Friday, so it won't make it into the next release.

**Comment by adamjstewart** [comment]
@NicolasHug congrats on the new release! I know there's always fallout from new releases, but once that settles down, a gentle reminder to review this PR. I rebased so we can test it against the latest version.

**Comment by adamjstewart** [comment]
Ping @NicolasHug

**Comment by adamjstewart** [comment]
Ping ping @NicolasHug

**Comment by adamjstewart** [comment]
@NicolasHug I believe I got all the remaining ones, let me know if I missed anything.

**Review by NicolasHug — APPROVED** [review]
Thanks @adamjstewart , the PR LGTM. Our CI is a bit toasted right now so I'll try to merge it some time later. Nothing more to do on your side though :)

Thanks!

**Pull request merged**
