### PR TITLE
[Nova] Disable CircleCI Linux CPU Unittests

### PR DESCRIPTION
**Pull request by osalpekar**
Linux CPU and GPU Unittests have been running smoothly for several weeks, so going ahead and removing the CircleCI Linux Unittest jobs. If we see any issues or high queueing, we can bring this back.

### CODE REVIEW

**Comment by pmeier** [comment]
@osalpekar I don't think this is the case for GPU: #6957. Could you look into this first?

@NicolasHug, AFAIK we want to skip the CPU tests on GPU machines, right? I think we need to update https://github.com/pytorch/vision/blob/4a310f26049371959617921d0eb9b001f4d262c6/test/conftest.py#L15-L24 to also account for GHA. Do you want to send a patch or shall I?

**Review by pmeier — CHANGES_REQUESTED** [review]
@osalpekar In #6970 I've confirmed that the GPU setup is incorrect and so far we have never run any CUDA tests on GHA. This needs to be addressed first. If you prefer, I'm also ok with moving this PR forward if we exclude the removal of the CUDA jobs.

**Comment by osalpekar** [comment]
@pmeier Sounds good, I've added back the Linux GPU CI jobs here, so this PR only disabled Linux CPU unittests.

**Review by pmeier — APPROVED** [review]
No concerns regarding CPU unittests from my side. Thanks Omkar!

**Pull request merged**
