### PR TITLE
Replace pybind11 with cmake's Python3 package

### LINKED ISSUE #1845: CMake scripts not working on Windows
It reports that `python37.lib` is not found during linking. Maybe we need to do sth like `find_package(python)` to find out the path of the python library.

### PR DESCRIPTION
**Pull request by bmanga**
Stop relying on pybind11 to discover python paths, but use cmake's more robust Python3 find package module.
This seems to establish the end of support for python2, but I have no idea if the project was still supporting it at all.

Closes #1845

### CODE REVIEW

**Comment by peterjc123** [comment]
@fmassa Would you please merge this PR?

**Comment by fmassa** [comment]
Thanks a lot @bmanga and @peterjc123 !

**Comment by fmassa** [comment]
Python2 is not supported anymore, so this is fine

**Comment by fmigneault** [comment]
@fmassa FYI
README still refers to pybind11 being used. Somewhat misleading.

**Comment by bmanga** [comment]
@fmigneault true, I am planning to update the C++ readme section.

**Comment by ShawnZhong** [comment]
It seems that `FindPython3` is only available after [CMake 3.12](https://cmake.org/cmake/help/v3.12/module/FindPython3.html), but the minimum required version in CMakeList.txt is 3.10. 

https://github.com/pytorch/vision/blob/96268814544998d14e9bbf4b9437df0299aa4cb9/CMakeLists.txt#L1

Should we explicitly specify the minimum version to 3.12 so that people won't get the weird module not found issue? 

BTW, the default package version for Ubuntu 20.04 LTS is [3.16.3](https://packages.ubuntu.com/focal/cmake) (via `sudo apt install cmake`), and the default version on conda is [3.14.0](https://anaconda.org/anaconda/cmake) (via `conda install cmake`)

**Comment by bmanga** [comment]
@ShawnZhong I have a backported version of the module in the works, I will try to get a PR ready soon. See #2085 for the discussion.

**Comment by ShawnZhong** [comment]
Thanks for the quick reply! It will be great if we could backport `FindPython3` for CMake 3.0

**Pull request merged**
