### PR TITLE
[FBcode->GH] [quant][core][better-engineering] Rename files in quantized directory…

### PR DESCRIPTION
**Pull request by NicolasHug**
… to conform with non-quantized countertpart filenames (#77037)

Summary:
X-link: https://github.com/pytorch/pytorch/pull/77037

Names of analogous files in quantized directory (previously snake case) were inconsistent with
their non-quantized filename counterparts (pascal case). This is the first of a series of PRs that changes
all files in quantized (and sub-directories) dir to have pascal case.

`aten/src/ATen/native/quantized/qconv_unpack.cpp` has not been renamed yet
because (for reasons currently unknown) after making the name change, `import torch` produces the below error (`qlinear_unpack.cpp` renaming also seems to fail some phabricator CI tests for similar reasons). We suspect that these may be undefined errors and will revisit naming these files in a future PR.

```
terminate called after throwing an instance of 'c10::Error'
  what():  Type c10::intrusive_ptr<ConvPackedParamsBase<2> > could not be converted to any of the known types.
Exception raised from operator() at ../aten/src/ATen/core/jit_type.h:1735 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x7f26745c0c65 in /data/users/dzdang/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xb1 (0x7f26745bdcd1 in /data/users/dzdang/pytorch/torch/lib/libc10.so)
frame #2: <unknown function> + 0x1494e24 (0x7f2663b14e24 in /data/users/dzdang/pytorch/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0xfed0bc (0x7f266366d0bc in /data/users/dzdang/pytorch/torch/lib/libtorch_cpu.so)
frame #4: c10::detail::infer_schema::make_function_schema(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) + 0x5a (0x7f266366d71a in /data/users/dzdang/pytorch/torch/lib/libtorch_cpu.so)
frame #5: c10::detail::infer_schema::make_function_schema(c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) + 0x7b (0x7f266366e06b in /data/users/dzdang/pytorch/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x1493f32 (0x7f2663b13f32 in /data/users/dzdang/pytorch/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xe227dd (0x7f26634a27dd in /data/users/dzdang/pytorch/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x14e0a (0x7f268c934e0a in /lib64/ld-linux-x86-64.so.2)
..........................truncated.............
```

Reviewed By: malfet

Differential Revision: D36862332

Pulled By: dzdang

fbshipit-source-id: 598c36656b4e71f906d940e7ff19ecf82d43031d

### CODE REVIEW

**Review by datumbox — APPROVED** [review]
Stamping. Feel free to merge on green CI.

**Comment by NicolasHug** [comment]
Most jobs are properly using the nightly from 08 (today), but the prototype jobs are still relying on 07 (yesterday). I believe it's because of the torchdata which is itself still locked at 07 https://github.com/pytorch/vision/runs/6794085957?check_suite_focus=true

**Comment by malfet** [comment]
Looks like prototype failures are due to torchdata nightly build failures which depends on pytorch-nightly from a previous day, which results in a weird double install of torch:
```
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu/
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch-1.13.0.dev2022060[8](https://github.com/pytorch/vision/runs/6797504560?check_suite_focus=true#step:5:9)%2Bcpu-cp37-cp37m-linux_x86_64.whl (190.6 MB)
Collecting torchdata
  Downloading https://download.pytorch.org/whl/nightly/torchdata-0.5.0.dev20220607-cp37-cp37m-linux_x86_64.whl (4.4 MB)
Collecting typing-extensions
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting requests
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting portalocker>=2.0.0
  Downloading portalocker-2.4.0-py2.py3-none-any.whl (16 kB)
Collecting urllib3>=1.25
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch-1.13.0.dev20220607%2Bcpu-cp37-cp37m-linux_x86_64.whl (1[9](https://github.com/pytorch/vision/runs/6797504560?check_suite_focus=true#step:5:10)0.2 MB)
```

**Review by malfet — APPROVED** [review]

**Comment by datumbox** [comment]
Agreed merging.

**Pull request merged**
