### PR TITLE
DOC: move documentation to versioned folders

### PR DESCRIPTION
**Pull request by mattip**
Copy pytorch/audio#992  and pytorch/text#1075 to this repo.
ping @brianjo. This enhancement to the gh-pages branch
- creates the documents in structured directories to allow versioning
- creates the first version of documentation in the gh-pages branch. Previously documentation was copied into the pytorch/pytorch documentation build, but that was removed, requiring a special build for the 0.7 documentation. For this PR, 0.8.1 documentation was built and copied to master and 0.8
- changes index.html to redirect to stable/index.html
- adds a README.md 

Todo in future PRS:
- add a version selector like on the pytorch site
- automate doc building on a merge (to the "master" directory) (see pytorch/audio#1006)
- automate doc building on a tag (to a numbered directory) (see pytorch/audio#1006)
- rethink serving the `_static` content. After this PR, each directory uses its own `_static` subdirectory, i.e, `0.8/index.html` uses `0.8/_static` resources for stylesheets and javascript. It would be nice if the content were shared across versions, so that a styling update would be applied to the older versions automatically: `0.8/index.html` would use `/_static`.

It might be difficult to review this PR because of all the added files. I added a README.md to try to explain how it should work.

### CODE REVIEW

**Review by fmassa — APPROVED** [review]
Thanks a lot!

Approving this PR on my end, but I'll let @brianjo merge it.

**Comment by mattip** [comment]
ping. The audio and text subprojects have merged the equivalent of this PR. I also submitted follow on work to the `master` docs on the nightly CI builds and push them to the gh-pages branch of the repo, and am waiting for this to go in to do the same here.

**Comment by mattip** [comment]
@fmassa @brianjo: thoughts?

**Comment by brianjo** [comment]
Sorry I missed this. I'll mege today after our meeting. Thanks!

**Comment by brianjo** [comment]
@fmassa Can you take a look at merging this? I'm getting an error.

**Pull request merged**
