### PR TITLE
fix for to_tensor when input is np.ndarray of shape [H,W,C]. 

### PR DESCRIPTION
**Pull request by alykhantejani**
Fix for issue #48 when input to `ToTensor` is a `np.ndarray` of shape `[H,W,C]`, `ToTensor` does not transpose the dimensions to output in shape `[C,H,W]` as per the docs.

Also added missing tests for `ToTensor`

### CODE REVIEW

**Comment by soumith** [comment]
i think this might break CIFAR10.
I assumed that the np array is already in CHW
I'll check next week, as part of doing some work on torchvision

**Comment by alykhantejani** [comment]
@soumith you're right, CIFAR10 does this 
```python
 self.train_data = self.train_data.reshape((50000, 3, 32, 32))
```

Happy to fix/change this as part of this PR. 

However, if you think we don't want to support HWC ndarray inputs to `ToTensor` we should then change the docs for `ToTensor` to reflect this

**Comment by alykhantejani** [comment]
@soumith @fmassa sorry for the delay on this. I've updated `CIFAR10` to transpose the images to `HWC`

**Comment by soumith** [comment]
thanks @alykhantejani !

**Pull request merged**
