### PR TITLE
replace imp with importlib (fixes #1607)

### LINKED ISSUE #1607: DeprecationWarning of imp
Hi, I got the following DeprecationWarning. [`imp`](https://docs.python.org/3/library/imp.html) is now deprecated and is recommended to move to `importlib` instead.

```
 /home/xxx/.miniconda/lib/python3.7/site-packages/torchvision/io/video.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
```

### PR DESCRIPTION
**Pull request by nvs-abhilash**
Replaced instances of `imp` with `importlib` to close #1607

### CODE REVIEW

**Comment by nvs-abhilash** [comment]
Sure. I am aware of the issue. Working on fixing it. Currently figuring out how to install torchvision from source and how to run the tests locally.

**Comment by fmassa** [comment]
Information on how to install torchvision from source can be found in https://github.com/pytorch/vision#installation

**Comment by nvs-abhilash** [comment]
Thank you so much for quick response. I was not able to do source install. It is giving some `RuntimeError: Failed to register operator torchvision::_new_empty_tensor_op.` error. I am assuming it is because of version mismatch between `pytorch` and `torchvison`. And currently installing `pytorch` from source. 

Am I doing it right or am I missing something?

**Comment by nvs-abhilash** [comment]
@fmassa , I have made the changes. And tested the old and the new behavior locally on my CPU machine for the imports which looks fine to me. I am not able to relate the CI checks here to my issue. Can you please review my code and let me know if I have to change anything?

**Pull request merged**
