### PR TITLE
Ignore direnv files

### PR DESCRIPTION
**Pull request by garymm**
See https://direnv.net/.

### CODE REVIEW

**Comment by NicolasHug** [comment]
Thanks for the PR @garymm 

Would it be feasible for you to rely on a custom set of gitignore rules instead? Something like https://stackoverflow.com/questions/6117109/is-it-possible-to-have-a-custom-gitignore-read-only-access

**Comment by garymm** [comment]
Seems like widely used tools are already included in .gitignore (e.g. vscode files).
But please close this PR if this is unacceptable and I'll try the work-around.

**Comment by NicolasHug** [comment]
vscode is the default at fb so that's why it's here. But yeah there is stuff like .idea/ .orig and *.venv that are more user specific (and that shouldn't be here IMHO, but OK, let's merge)

**Comment by NicolasHug** [comment]
tagging it as CI for lack of better tag

**Comment by garymm** [comment]
Thanks!

**Pull request merged**
