### PR TITLE
[reland] rename DisableTorchFunction to DisableTorchFunctionSubclass (#88218)

### PR DESCRIPTION
**Pull request by samdow**
Summary: First half of #87990. This doesn't change any of the behavior and is just a rename

Differential Revision:
D41268423

LaMa Project: L1098534

### CODE REVIEW

**Comment by datumbox** [comment]
@samdow Looks good. Please give us a ping when you actually land everything. We will need to export the patch to Github to avoid breaking the CI. :)

**Comment by samdow** [comment]
Thanks @datumbox! Just wanted to let you know that I didn't realize but this change updates a file that's under a code freeze, so I'm going to hold off on it until the new year

**Comment by datumbox** [comment]
@samdow Thanks for the heads up, sounds good!

**Comment by samdow** [comment]
@fmassa @NicolasHug Vasilis asked me to ping when we landed so you can update CI. Since he's moved on, I was hoping one of you is the right person to do this (or know the right people). Thanks!

**Comment by datumbox** [comment]
@samdow Thanks for the ping.

It seems that the commit (972e5a7699b41b7b622f38bdb654bd3967529ab4) landed on fbsync branch. @YosuaMichael @jdsgomes @pmeier Could you cherrypick it on main?

**Comment by pmeier** [comment]
Can I do that as non-meta employee? If yes, do I just send a PR with the commit in question against `main`?

**Comment by datumbox** [comment]
@pmeier Yes you can. We just need to bring the specific commit on main branch and you are good to go. Just make sure you add on the PR title AND at the beginning of the commit message the `[FBcode->GH]`. See this PR for an example: #6813

**Comment by pmeier** [comment]
See #7062

**Comment by pmeier** [comment]
#7062 landed, so I guess we can close this?

**Comment by NicolasHug** [comment]
Thanks all

**Pull request closed without merging**
