### PR TITLE
Added missing typing annotations to transforms/functional_tensor

### PR DESCRIPTION
**Pull request by frgfm**
Following up on #2025, this PR adds missing typing annotations in transforms/functional_tensor.py. I checked locally by editing the mypy.ini and everything looks good :+1: 

Any feedback is welcome!

### CODE REVIEW

**Comment by oke-aditya** [comment]
Oh! I too had a shot at this have a look at #4235.
Let's go ahead with either :smile:

**Comment by frgfm** [comment]
> Oh! I too had a shot at this have a look at #4235.
> Let's go ahead with either

Oh shoot, my bad, I thought I had checked that you hadn't taken care of this one :upside_down_face:

**Comment by frgfm** [comment]
@fmassa I checked locally by removing the mypy ignore from `mypy.ini` and all tests passed, so I think this is good to go for review  :)

**Comment by NicolasHug** [comment]
>  I checked locally by removing the mypy ignore from mypy.ini and all tests passed,

Thanks @frgfm , could you please remove it in this PR as well, so that we can rely on the CI to check the file?

**Comment by frgfm** [comment]
> > I checked locally by removing the mypy ignore from mypy.ini and all tests passed,
> 
> Thanks @frgfm , could you please remove it in this PR as well, so that we can rely on the CI to check the file?

I would have done it, but there are other files handled by other PRs in `transforms`. Do you prefer me to remove the ignore and add several for all the other files?

**Comment by NicolasHug** [comment]
Yes, we should remove the global ignore of `torchvision.transforms.*` and manually add the rest of the files which I believe are

`_functional_video.py,	_transforms_video.py,  autoaugment.py,  functional.py,  functional_pil.py, transforms.py`

**Comment by frgfm** [comment]
I just added other files that were throwing typing errors :ok_hand:

**Review by fmassa — APPROVED** [review]
LGTM, thanks!

**Comment by frgfm** [comment]
Ready to be merged @fmassa :)

**Pull request merged**
