### PR TITLE
enable Windows GPU CI on GHA

### PR DESCRIPTION
**Pull request by pmeier**
Follow-up to https://github.com/pytorch/vision/pull/7475#issuecomment-1495858650.

cc @seemethere

### CODE REVIEW

**Comment by pmeier** [comment]
nvjpeg is now there: https://github.com/pytorch/vision/actions/runs/4849919333/jobs/8642356230#step:9:233

However, it seems something is off with the path as we cannot load the `image.pyd`: https://github.com/pytorch/vision/actions/runs/4849919333/jobs/8642356230#step:9:801

**Comment by pmeier** [comment]
In c12e4f7e7c4bdc7a74ff9673dd9ddb5da3bc2af6 I removed the Windows GPU tests from CircleCI. Although we usually had a grace period, I don't think we need one here. The grace period for the CPU workflow is already over (#7526) and this PR only enables the GPU runs. If the CI is green here, I don't expect any regressions for this later on. LMK if you think otherwise so I can revert that commit.

**Review by NicolasHug — APPROVED** [review]
Thanks Philip

> However, it seems something is off with the path as we cannot load the image.pyd

Just to confirm, is this comment still relevant? I'm seeing the `test/test_image.py::test_decode_jpeg_cuda` tests properly passing (as well as the cuda ones in `test_models.py`) so as far as tests go, this PR LGTM.

**Comment by pmeier** [comment]
No, comment is outdated. This was fixed in 5c0da2e95466fbfe151c5434e96d15cb241b26bd.

**Pull request merged**
