### PR TITLE
.circleci: Downgrade CUDA 11.2 -> 11.1

### PR DESCRIPTION
**Pull request by seemethere**
There were performance issues with 11.2 so we're opting to build
packages for 11.1 instead

Follow up to #3341

Relates to https://github.com/pytorch/pytorch/pull/52151

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

### CODE REVIEW

**Comment by seemethere** [comment]
Looks like we're experiencing failures on windows builds:

For wheels ([CircleCI logs](https://app.circleci.com/pipelines/github/pytorch/vision/6393/workflows/db8d97f4-c102-44c2-8657-5e6d14bdd7ee/jobs/419723)):

```
deform_conv2d_kernel.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) struct cudaDeviceProp * __cdecl at::cuda::getCurrentDeviceProperties(void)" (__imp_?getCurrentDeviceProperties@cuda@at@@YAPEAUcudaDeviceProp@@XZ)
build\lib.win-amd64-3.9\torchvision\_C.pyd : fatal error LNK1120: 1 unresolved externals
```

For conda ([CircleCI logs](https://app.circleci.com/pipelines/github/pytorch/vision/6393/workflows/db8d97f4-c102-44c2-8657-5e6d14bdd7ee/jobs/419724))

This one looks like it's a case of the resolver for `conda` taking too long, going to try and up the no output timeout on windows builds to see if that helps

**Comment by peterjc123** [comment]
https://github.com/pytorch/pytorch/pull/52503 should fix this.

**Comment by peterjc123** [comment]
@fmassa @seemethere Do we need to fix the cmake scripts as well? cc @janeyx99

**Comment by janeyx99** [comment]
I had merged https://github.com/pytorch/pytorch/pull/52305 intending to introduce a dummy torch_cuda when we split the library, which might resolve these downstream dependencies. However, it's not cherrypicked into the release cut :/ so it probably would be best to go with your fixes here @peterjc123

**Comment by seemethere** [comment]
What? I didn't merge this @facebook-github-bot 😞

**Review by malfet — APPROVED** [review]

**Pull request merged**
