### PR TITLE
Bumped version to v0.7.0 and removed a commented line

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
- Minor update of CMakeLists.txt

### CODE REVIEW

**Review by fmassa — APPROVED** [review]
Thanks!

**Comment by fmassa** [comment]
One comment about this though is that master version of torchvision is now at 0.8.0

**Comment by vfdev-5** [comment]
@fmassa correct. I think it would be better to find out a way to fetch the version from `setup.py`. What do you think ?

**Comment by fmassa** [comment]
I think we are moving towards using CMake inside `setup.py`, so that might come naturally.

**Pull request merged**
