### PR TITLE
New dataset added (Caltech-UCSD Birds 200) regarding issue #147 #60829

### PR DESCRIPTION
**Pull request by shakeebmurtaza**
A new dataset added (Caltech-UCSD Birds 200) regarding issue #147 #60829.

A lot of people are using Caltech-UCSD Birds-200-2011 dataset for the evaluation of their proposed models. According to paperswithcode.com 787 papers employed this dataset since 2017 and these numbers are growing. So, I want to add support for this data in the datasets library.

### CODE REVIEW

**Comment by vadimkantorov** [comment]
Some problems with the previous version was that there are multiple setups of using CUB and its metadata.

The typical metric learning setup defines some class splits. 

Considering metadata, there is a bbox crop for every image and attributes. At least it should be available for retrieval via index. At most, maybe there should be an option that always does the crop in the dataset (I think often it's what people do in metric learning evaluation)

So it may be best to also define more specific Cub2011MetricLearningDataset-like classes after ensuring what exactly is the standard practice in metric learning pipelines.

**Review by pmeier — COMMENTED** [review]
Hey @shakeebmurtaza and thanks for the PR! Although this was proposed in #3562 as potential new dataset, AFAIK we never reached a conclusion. @fmassa, are we going to move forward with this, or do we wait with adding new datasets until after the rework?

**Comment by shakeebmurtaza** [comment]
Hey, @pmier and @fmassa. Any update regarding this issue. If your response is positive then I need to do some quick fixes.

**Comment by pmeier** [comment]
@shakeebmurtaza we need to be patient for a little longer. I assume we get an answer mid next week.

**Comment by pmeier** [comment]
In #5154 we added this to the new prototype datasets.

**Pull request closed without merging**
