### PR TITLE
Avoid `_prims_common.check` in favor of `torch._check`

### PR DESCRIPTION
**Pull request by kurtamohler**
`torch._prims_common.check` will be removed in https://github.com/pytorch/pytorch/pull/102219

### CODE REVIEW

**Review by pmeier — APPROVED** [review]
Thanks Kurt! Could you ping me here when the PR on core is merged so I can merge this one as well?

**Comment by kurtamohler** [comment]
@pmeier, do you think we could merge this one first? `torch._check` already exists in pytorch, and having this change in torchvision will fix a CI error I'm getting in the other PR

**Comment by pmeier** [comment]
Yes, we can do that as well.

**Comment by kurtamohler** [comment]
It seems like these CI failures must be unrelated to my changes, right?

**Pull request merged**
