### PR TITLE
Fixed issue with F.crop when cropping outside the input image

### LINKED ISSUE #6613: `F.crop` behavior diverges between tensor and PIL images
```py
import torch
from torchvision.prototype.transforms import functional as F

image_tensor = torch.rand(3, 7, 33)
image_pil = F.to_image_pil(image_tensor)

print(
    F.get_spatial_size(F.crop(image_tensor, top=9, left=9, height=20, width=12)),
    F.get_spatial_size(F.crop(image_pil, top=9, left=9, height=20, width=12)),
)
```

```
[22, 12] [20, 12]
```

cc @vfdev-5 @datumbox @bjuncek

### PR DESCRIPTION
**Pull request by vfdev-5**
Fixes #6613

### CODE REVIEW

**Comment by datumbox** [comment]
@vfdev-5 Something made the mypy go wild with [errors](https://app.circleci.com/pipelines/github/pytorch/vision/20355/workflows/4f2a77e1-7bb4-476c-afc4-d90d2f64a5c0/jobs/1655614). Could you have a look?

**Comment by vfdev-5** [comment]
Philip already reported that, related to torchdata: https://github.com/pytorch/data/pull/780#issuecomment-1252325496

**Review by datumbox — APPROVED** [review]
LGTM, thanks!

**Comment by datumbox** [comment]
@vfdev-5 Yes you can merge it. I understand the issue is caused by an upstream dependency on TorchData and should be fixed.

**Pull request merged**
