### PR TITLE
Ignore mypy's missing import warning for requests

### LINKED ISSUE #4009: python_type_check CI is broken: missing stubs for requests module
## 🐛 Bug

The `python_type_check` CI is failing since mypy can't find library stubs for requests module used [here](https://github.com/pytorch/vision/blob/befbe1b372e7c028a7b4cb2155110fbae708038e/torchvision/datasets/utils.py#L204) .
This can be seen in the [failed tests](https://app.circleci.com/pipelines/github/pytorch/vision/8800/workflows/971b988a-2245-4aa7-acdf-97af0a38afe2/jobs/639205) for the recent [commit](https://github.com/pytorch/vision/commit/e4c56081ded40403bc3b53ff73ed819d6a46f33e) by @prabhat00155 (although those changes are completely unrelated to this) and on some other PRs like #4008 (edit: and #4010) 

## Pitch
A simple fix would be to install them with `python3 -m pip install types-requests` or to avoid something like this happening later we should just run `mypy --install-types` to install all the missing stubs.

### PR DESCRIPTION
**Pull request by datumbox**
Fixes #4009

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
LGTM! Thanks for the fix @datumbox 

A quick question: Any specific reasons for ignoring the type check instead of installing the stubs?

**Review by pmeier — CHANGES_REQUESTED** [review]
I'm with @AnirudhDagar here: installing the stubs would make the `mypy` check more reliable. `mypy` is not a necessary evil that needs to be silenced whenever it turns up something. We opted to use it to catch bugs that are not covered by our tests.

**Comment by NicolasHug** [comment]
> We opted to use it to catch bugs that are not covered by our tests.

I'm curious, in the PRs that were making the code mypy compliant, did you catch actual bugs?

**Comment by datumbox** [comment]
@pmeier @AnirudhDagar The master is currently failing and when this happens it's high priority to fix it. This PR is not about improving the code, it's about restoring the CI in green state. In situations like this, please avoid blocking such PRs unless you see a bug being introduced and opt for making any suggested improvements on subsequent PRs.

**Comment by pmeier** [comment]
> > We opted to use it to catch bugs that are not covered by our tests.
> 
> I'm curious, in the PRs that were making the code mypy compliant, did you catch actual bugs?

It has been a while, but I'm fairly certain that the answer was no. IMO that is a testament to good reviews. 

While developing, I often find myself in a position where `mypy` complains about something and it turns out it is something I didn't think through before. Plus, being `mypy` compliant makes thorough testing [a whole lot easier](https://www.youtube.com/watch?v=pMgmKJyWKn8&t=317s).

**Review by fmassa — APPROVED** [review]
Let's get this merged to get CI green. We can always send a follow-up PR adding it to the stubs.

**Review by NicolasHug — APPROVED** [review]
Stamping, but even though I hate mypy, I agree with @pmeier on this one: it wouldn't hurt much to spend a bit more time to fix the root of the issue.

**Comment by pmeier** [comment]
@datumbox The fix for this is exactly the same number of lines: add `mypy --install-types` after

https://github.com/pytorch/vision/blob/ea6be1240e5d83888b8d7fb08062496fa0c0c711/.circleci/config.yml.in#L207

**Comment by AnirudhDagar** [comment]
@datumbox did not mean to question or block you. Sorry for that. It is definitely important to get a master to green in such a case.

**Comment by NicolasHug** [comment]
Thanks @pmeier for the feedback

> It has been a while, but I'm fairly certain that the answer was no. IMO that is a testament to good reviews.

And to good tests I think

> While developing, I often find myself in a position where mypy complains about something and it turns out it is something I didn't think through before.

Interesting. My own experience was that  whatever mypy was flagging was forcing me to re-write the code into something that either doesn't make sense, or is less readable ^^

> Plus, being mypy compliant makes thorough testing a whole lot easier.

I disagree with the test part from that talk because it's talking about input validation checks: we can't rely on types for that, because this would  assume that our users also use mypy. For libraries such as torchvision, type annotation brings nothing to the table when it comes to input validation of user-facing utilities.

**Comment by datumbox** [comment]
@pmeier I understand that the fix you have in mind might be trivial in this specific case but changes like this still need time to be tested. IMO restoring the CI in green state when it's a false positive is high priority and buys us time to do any further due diligence on improving the code and resolving the root cause. By restoring the CI, it will unblock contributors such as @AnirudhDagar who currently get the [wrong signal](https://github.com/pytorch/vision/pull/4010#issuecomment-857263266).

Happy to review a PR that addresses the issue and improve the codebase.

**Pull request merged**
