### PR TITLE
Help make test dependent on randint compatible with python 3.12

### PR DESCRIPTION
**Pull request by hmaarrfk**
It seems that python 3.12 is a little stricter on the inputs of randint.

I hope this helps
```
In [1]: import random

In [2]: random.randint(10, 10/2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 random.randint(10, 10/2)

File ~/miniforge3/envs/py12/lib/python3.12/random.py:336, in Random.randint(self, a, b)
    332 def randint(self, a, b):
    333     """Return random integer in range [a, b], including both end points.
    334     """
--> 336     return self.randrange(a, b+1)

File ~/miniforge3/envs/py12/lib/python3.12/random.py:312, in Random.randrange(self, start, stop, step)
    309     raise ValueError("empty range for randrange()")
    311 # Stop argument supplied.
--> 312 istop = _index(stop)
    313 width = istop - istart
    314 istep = _index(step)

TypeError: 'float' object cannot be interpreted as an integer

```

### CODE REVIEW

**Comment by hmaarrfk** [comment]
thanks for looking at this so quickly and taking the time to test on your machine.

this seems intentional. see notes about automatic conversation.

https://docs.python.org/3/library/random.html#functions-for-integers

integer division resolves this issue easily. 
the PR is 8 characters that go in the right direction toward 3.12 support without hurting other versions in any way. it is contained in the test suite, and it is obvious from inspection that the type of the inputs to the division operator are integers.

I mostly just wanted to help given that I had tried to see how far along python 3.12 one could go. I'm not asking you to accelerate your timeline in any way.

take it or leave it I guess.

**Comment by hmaarrfk** [comment]
Just a kind ping hoping you can consider the introduction of a total of 10 characters.

**Comment by NicolasHug** [comment]
Thank you for the ping @hmaarrfk . We'll merge the PR in due time, when 3.12 support becomes official for Pytorch and torchvision.

I'm sure you're experienced enough to know that the complexity, dept and criteria for inclusion of a PR doesn't correlate with its number of characters.

**Review by NicolasHug — APPROVED** [review]
Thanks a lot for the PR and for your patience @hmaarrfk. We'll want to release for 3.12 in the next release, so let's get that in now.

**Comment by NicolasHug** [comment]
Failures are unrelated, let's merge

**Pull request merged**
