### PR TITLE
MNIST loader refactored: permanent 'data' and 'targets' fields

### PR DESCRIPTION
**Pull request by dizcza**
Addresses https://github.com/pytorch/vision/issues/577.
Simplified code.

### CODE REVIEW

**Comment by lanpa** [comment]
Hi, This PR breaks many existing example which using MNIST and it might be hard to trace the root cause for people unfamiliar with pytorch. To be more user friendly, I suggest to add those `test_data`, `test_label` etc. (as alias) back along with deprecation message before publishing the next pip release.

**Comment by dizcza** [comment]
Yes, alias with a deprecation message, saying it'll be removed in the next release, might be a good idea.
What do you think, @fmassa ?

**Comment by fmassa** [comment]
@dizcza I agree with this path.
I was planning on cutting a release this week, would it be possible to get this deprecation message in soon?

Thanks!

**Comment by dizcza** [comment]
I won't be available this week. Please find someone else.

**Comment by fmassa** [comment]
Sounds good, I'll get this done

**Pull request merged**
