### PR TITLE
Add support for Python 3.11

### PR DESCRIPTION
**Pull request by pmeier**
_Redo of #6959, because it was pushed to the `main` branch of the fork and I don't have permissions to push to it_

### CODE REVIEW

**Comment by pmeier** [comment]
There are multiple CI failures, but as long as [missing dependencies](https://github.com/pytorch/vision/actions/runs/3948485772/jobs/6758530515#step:10:170) are not fixed, we can't move forward. Both `numpy` and `scipy` are currently missing 3.11 support as well. Both latest version in the channel, i.e. [`numpy==1.23.5`](https://anaconda.org/main/numpy) and [`scipy==1.9.3`](https://anaconda.org/main/scipy), have 3.11 wheels on PyPI. So I guess Anaconda needs to just build them with the newly available Python 3.11.

**Comment by johnnynunez** [comment]
> There are multiple CI failures, but as long as [missing dependencies](https://github.com/pytorch/vision/actions/runs/3948485772/jobs/6758530515#step:10:170) are not fixed, we can't move forward. Both `numpy` and `scipy` are currently missing 3.11 support as well. Both latest version in the channel, i.e. [`numpy==1.23.5`](https://anaconda.org/main/numpy) and [`scipy==1.9.3`](https://anaconda.org/main/scipy), have 3.11 wheels on PyPI. So I guess Anaconda needs to just build them with the newly available Python 3.11.

yes, 1.24 numpy is necessary. I hope that they updated soon.

**Comment by pmeier** [comment]
> yes, 1.24 numpy is necessary

Why? I think they can just build `1.23.5` with Python 3.11

**Comment by johnnynunez** [comment]
> > yes, 1.24 numpy is necessary
> 
> Why? I think they can just build `1.23.5` with Python 3.11

yes, but it is the initial support.
But 1.24 is the released supported https://numpy.org/devdocs/release/1.24.0-notes.html

**Comment by johnnynunez** [comment]
@pmeier What packages does torchvision need? I see that Anaconda doesn't have any for python3.11. From what I've been told the release with python3.11 comes out in March, but I'm trying to press to unlock this merge much earlier

**Comment by pmeier** [comment]
https://github.com/pytorch/vision/blob/d2d448c71b4cb054d160000a0f63eecad7867bdb/packaging/torchvision/meta.yaml#L24-L34

So the Python dependencies are

- `numpy`
- `requests`
- `Pillow`

> but I'm trying to press to unlock this merge much earlier

Don't do that on our behalf. I agree that we need 3.11, but there is no need to push anyone for that.

**Comment by johnnynunez** [comment]
@pmeier yeah of course, but it’s the next milestone/release about March aprox https://github.com/conda/conda/issues/11170

**Comment by pmeier** [comment]
If you have a strong need for 3.11, why not build it yourself from source?

> about March aprox

We will have the branch cut for the next release in under one month (no concrete dates yet) so likely the next release will also be without 3.11. Of course nightlies will be available as soon as this PR is merged.

**Comment by osalpekar** [comment]
cc @malfet @atalman

**Comment by johnnynunez** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/13125

**Comment by johnnynunez** [comment]
@pmeier @atalman @osalpekar https://github.com/ContinuumIO/anaconda-issues/issues/13082#issuecomment-1471179717

**Comment by pmeier** [comment]
`torchvision==0.15.1` is available for Python 3.11 from PyPI. Unfortunately, the conda version didn't make it, because the defaults channel only very recently published 3.11 versions of our dependencies. I'll open a separate issue for that. We'll provide 3.11 builds on our nightly channel soon.

**Pull request closed without merging**
