### PR TITLE
Try fix Windows CircleCI

### PR DESCRIPTION
**Pull request by fmassa**

### CODE REVIEW

**Comment by peterjc123** [comment]
@fmassa Do you know why when all the jobs fail when I push a commit here?

**Comment by fmassa** [comment]
@peterjc123 looks like this is a problem with the rebase approach we are doing. Second try after https://github.com/pytorch/vision/pull/1427, but it still doesn't seem to be enough... :-/

Can you try reverting that PR here and try again?

**Comment by fmassa** [comment]
@peterjc123 reverting those changes seemed to do the trick here, although it's a temporary solution.

I'm fixing the `torchvision_linux_py3.7_cu100` failure in https://github.com/pytorch/vision/pull/1463

**Comment by fmassa** [comment]
Wohoo, CI is all green!

**Pull request merged**
