### PR TITLE
Enable GPU/RE teags for pytorch/*/TARGETS that needs GPU

### PR DESCRIPTION
**Pull request by walterddr**
Summary: Convert pytorch_gpu to use GPU/RE

Reviewed By: malfet

Differential Revision: D26264102

### CODE REVIEW

**Comment by datumbox** [comment]
I don't think the PR intended to target fbsync as it's a protected branch. I'm closing the PR to avoid accidental merges/issues and I'll comment on Phabricator to see what's the best way to merge this. :)

**Comment by walterddr** [comment]
@datumbox sorry it was auto generated in phabricator. should I change it to master?

**Comment by datumbox** [comment]
@walterddr Actually, this was my bad. We don't get lots of PRs from phabricator so I was not aware of the full process. To summarize, you did good to send a PR this way, even if we won't merge it at the end. Sending this PR allow us to check that the CI tests pass. After confirming that the PR passes, we would close it and wait for the shipit to merge it after it's done on phabricator.

For this specific PR, it seems that the [lint fails](https://app.circleci.com/pipelines/github/pytorch/vision/6204/workflows/c691ef6d-f1fd-46c0-8a10-7ec155482368/jobs/403758). All other tests (minus flaky) pass without problem.

**Comment by walterddr** [comment]
Thanks for the follow up @datumbox
I will reopen this PR when I push more commits internally to trigger CIs.

**Comment by walterddr** [comment]
reopen

**Pull request closed without merging**
