### PR TITLE
Change CI cuda versions to 10.2

### PR DESCRIPTION
**Pull request by datumbox**

### CODE REVIEW

**Comment by NicolasHug** [comment]
Thanks for the PR!

Let's see what the CI says. We might need to also change stuff like the use of `      image_name: "pytorch/manylinux-cuda101"` in the yaml file, as well as other references to `101` in `regenerate.py`, in particular:

```py
                if device_type == 'gpu':
                    if python_version != "3.8":
                        job['filters'] = gen_filter_branch_tree('master', 'nightly')
                    job['cu_version'] = 'cu101'
 ```

**Comment by datumbox** [comment]
Thanks I'm still looking for more places I have to change. If you see others please let me know.

**Comment by datumbox** [comment]
It seems that the latest PyTorch core on linux has a new restriction on how you index things across devices:

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument indices in method wrapper_Tensor_index_Tensor)
```

The problem appears only on Linux GPU and not on Windows:
https://app.circleci.com/pipelines/github/pytorch/vision/8241/workflows/6af4ce74-e157-4ca6-9eca-64ed7b9989ee/jobs/590609/tests#failed-test-0

**Review by fmassa — APPROVED** [review]
Accepting to unblock

**Comment by ngimel** [comment]
To close the loop on this, indexing from python is not affected, because python_variable_indexing copies all the indices to `self` device before dispatching to `index`. However, having indices on the different device in c++ has been broken by #56872. cc @wenleix, @ezyang

**Comment by wenleix** [comment]
@ngimel  Thanks for reporting this. Will figure out a fix to this. Does that mean we should opt out automatic device guard for all index related methods? (e.g. `index.Tensor`, `index_copy_`, `index_put`, etc -- will also check the code)?

**Pull request merged**
