### PR TITLE
Change batched NMS threshold for-loop version

### PR DESCRIPTION
**Pull request by ppwwyyxx**
According to the benchmark link https://github.com/pytorch/vision/issues/1311#issuecomment-781329339, for GPU the threshold should be higher (which is why detectron2 used 40k).
This PR changes the threshold to be device dependent.

### CODE REVIEW

**Review by NicolasHug — COMMENTED** [review]
Thanks for the PR @ppwwyyxx 

We decided to use the same threshold for CPU and GPU to keep things as simple as possible and avoid potential surprises.

Do you have a use-case where there are more than 4k boxes on a GPU?

**Comment by ppwwyyxx** [comment]
LVIS has 1200 classes. So in the last NMS of a faster r-cnn trained on LVIS it's common to have 10k-30k boxes.

**Review by NicolasHug — APPROVED** [review]
Thanks for the details @ppwwyyxx . The changes LGTM but I'm wondering, did you observe a significant time improvement with the new threshold?

**Comment by ppwwyyxx** [comment]
IIRC we added thresholding in detectron2 because batched_nms OOM for a specific model with too many boxes. Then we did some benchmarks and determined 40k threshold for GPU. This is similar to the conclusion in #1311. 
D17157130 has some discussions at the time.

**Review by fmassa — APPROVED** [review]
Thanks for the PR @ppwwyyxx !

I believe this is a net improvement. I think the previous threshold was indeed not ideal for GPU, and https://github.com/pytorch/benchmark/pull/547#issuecomment-970487925 seems to indicate that.

**Pull request merged**
