### PR TITLE
Revert "Ported places365 dataset's tests to the new test framework"

### PR DESCRIPTION
**Pull request by datumbox**
Reverts pytorch/vision#3705

### CODE REVIEW

**Review by pmeier — APPROVED** [review]
Thanks. I'll deal with the failing download tests. Then we can merge the PR again. Cc @prabhat00155

**Comment by prabhat00155** [comment]
I have created this PR: https://github.com/pytorch/vision/pull/3719 to remove old tests from test_datasets_download.

**Comment by pmeier** [comment]
Yeah, I need to fix 

https://github.com/pytorch/vision/blob/d4195587166134c3806ae81458d08b06f5e00295/test/test_datasets_download.py#L223-L231

Will do that and than we can merge your PR again. Sorry, I missed that during the review.

**Comment by prabhat00155** [comment]
> Yeah, I need to fix
> 
> https://github.com/pytorch/vision/blob/d4195587166134c3806ae81458d08b06f5e00295/test/test_datasets_download.py#L223-L231
> 
> Will do that and than we can merge your PR again. Sorry, I missed that during the review.

@pmeier We already test `download=True` in the new tests, so we don't need these right? https://github.com/pytorch/vision/pull/3719 should fix the issue.

**Pull request merged**
