### PR TITLE
Remove dependency on tqdm

### PR DESCRIPTION
**Pull request by fmassa**
Fixes https://github.com/pytorch/vision/issues/766

### CODE REVIEW

**Comment by alsrgv** [comment]
@fmassa, it looks like if `tqdm` is not installed, this actually does not work because [tqdm fallback](https://github.com/pytorch/pytorch/blob/master/torch/utils/model_zoo.py#L128) does not have no-argument constructor.

I found out because it broke our [integration tests](https://travis-ci.org/horovod/horovod/builds/500053644?utm_source=github_status&utm_medium=notification).

**Comment by soumith** [comment]
🤕 Francisco can you please land another fix and please test it this time. Going live on binaries with broken things like this is not a good thing.

**Comment by XavierAtShanghai** [comment]
I see the following error:
```
File ".../local/lib/python2.7/site-packages/torchvision/datasets/utils.py", line 73, in download_url
    reporthook=gen_bar_updater(tqdm())
TypeError: __init__() takes at least 2 arguments (1 given)
```

**Comment by fmassa** [comment]
I'm fixing this, sorry about the breakage.
My testings were indeed not enough, I'm sorry about that

**Comment by fmassa** [comment]
@alsrgv this should fix it https://github.com/pytorch/vision/pull/770

**Comment by alsrgv** [comment]
@fmassa, it works now - thanks!

**Pull request merged**
