### PR TITLE
[ONNX] Fix dtype for NonMaxSuppression

### PR DESCRIPTION
**Pull request by justinchuby**
Explicitly cast inputs to NonMaxSuppression to `float32` to accommodate `float64` inputs because `NonMaxSuppression` only supports float32 coordinates. This is necessary to unblock https://github.com/pytorch/pytorch/issues/78442 and https://github.com/pytorch/pytorch/pull/86146.

- Also removed the use of deprecated `_cast_Long`.

cc @BowenBao @mruberry

### CODE REVIEW

**Comment by BowenBao** [comment]
> Explicitly cast inputs to NonMaxSuppression to float32 to accommodate float64 inputs because NonMaxSuppression only supports float32 coordinates.

Should we do this in `scalar_type_analysis` pass, wdyt?

**Comment by justinchuby** [comment]
That's a good point. I will see how it can be done

**Comment by justinchuby** [comment]
@BowenBao I think this change is a much more efficient one. Can we resurrect this change?

**Review by BowenBao — APPROVED** [review]

**Comment by BowenBao** [comment]
@datumbox please take a look.

**Comment by datumbox** [comment]
@justinchuby I'm no longer in the maintainer group to offer a stamp and help you merge.

Not sure if any of the remaining folks from EU are online now. Perhaps @malfet @atalman could stamp?

**Comment by datumbox** [comment]
Also it seems that one of the tests is [failing](https://app.circleci.com/pipelines/github/pytorch/vision/23153/workflows/3c246be8-eeeb-40b9-862a-08046944a163/jobs/1826778)? Could be related.

**Comment by malfet** [comment]
@datumbox I can send you an invite, if you need one.

**Comment by NicolasHug** [comment]
Thanks for the PR @justinchuby 

> Moved symbolic functions to the module scope and cleaned up imports for symplicity.

Any chance we could revert this change? It makes the diff a little difficult to review

**Comment by pmeier** [comment]
Thanks for the PR @justinchuby. Could you clarify what review you need from us? Happy to help get this merged before our branch cut on Feb 17. As @datumbox mentioned, we have a (previously undetected) ONNX failure: #7247.

@NicolasHug I think we need to prioritize getting this landed and CI green over potential style nits given that our branch cut is looming ahead. Happy to revisit afterwards.

**Comment by justinchuby** [comment]
> Thanks for the PR @justinchuby. Could you clarify what review you need from us? Happy to help get this merged before our branch cut on Feb 17. As @datumbox mentioned, we have a (previously undetected) ONNX failure: #7247.
> 
> @NicolasHug I think we need to prioritize getting this landed and CI green over potential style nits given that our branch cut is looming ahead. Happy to revisit afterwards.

thanks! I will work on this today

**Comment by justinchuby** [comment]
@pmeier @NicolasHug I changed this PR to be minimal and found the cause for the test failure. We need https://github.com/pytorch/pytorch/pull/94870 then this then https://github.com/pytorch/pytorch/pull/86146, in this order. Thanks a lot!

**Comment by pmeier** [comment]
Since pytorch/pytorch#94870 is already merged, we should have access to it with todays nightly release in roughly a couple of hours. Will merge then if CI is green. Just so I understand correctly, #7249 is not strictly needed but improves code quality, right? Meaning, it would be good to merge soon, but can wait until after the branch cut?

**Comment by pmeier** [comment]
ONNX test is green: https://app.circleci.com/pipelines/github/pytorch/vision/23230/workflows/c3c3853e-6c98-4571-aae7-760bb6c36967/jobs/1829412

**Comment by justinchuby** [comment]
> Just so I understand correctly, #7249 is not strictly needed but improves code quality, right? Meaning, it would be good to merge soon, but can wait until after the branch cut?

That's accurate

**Pull request merged**
