### PR TITLE
Remove fakeroot dependency of Places365 in download tests

### PR DESCRIPTION
**Pull request by pmeier**
Supersedes #3719. #3705 ported the tests for `Places365` to the new architecture. The download tests however depended on parts of the old architecture and thus failed. This was not observed in the PR itself since the download tests are usually only ran on a schedule. 

This removes the dependency. Thus, #3705 can be reinstated after it was reverted in #3718.

### CODE REVIEW

**Review by datumbox — APPROVED** [review]
LGTM, if tests pass. Our CI is a bit broken at the moment, so if there are local tests you can run to confirm we are good then it would be great.

**Review by NicolasHug — APPROVED** [review]
Thanks @pmeier . CI can't test this until it's merged, right?

`pytest test/test_datasets_download.py -k places` passes locally, so LGTM

**Comment by pmeier** [comment]
The download tests are decoupled from the rest of the CI. They [successfully ran](https://github.com/pytorch/vision/pull/3730/checks?check_run_id=2436606387).

**Review by prabhat00155 — APPROVED** [review]

**Comment by prabhat00155** [comment]
Thanks @pmeier for fixing this.

**Pull request merged**
