### PR TITLE
Improve torchvision documentation

### PR DESCRIPTION
**Pull request by chsasank**
Added proper docstrings for all transforms.

WIP. Document:

- [x] Transforms
- [x] Datasets
- [x] Mean Std to be used for models
- [ ] Create a PR to pytorch/pytorch with rst files modified

### CODE REVIEW

**Comment by fmassa** [comment]
Awesome, thanks @chsasank !

**Comment by chsasank** [comment]
@fmassa This PR is ready to be reviewed and merged. 
Once merged I'll create another PR in pytorch/pytorch.

 Does all the models use this normalisation: ` transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])`

**Comment by chsasank** [comment]
Latest commit fixes #180.

**Comment by fmassa** [comment]
The PR looks good, thanks a lot!

Yes, the mean / std should be the same for all models (except googlenet, but there is an extra argument to the model to adapt to it).

Unfortunately the `README.rst` from torchvision is not automatically updated, but it's ok for the moment I think.
At some point in future, it might be good to get the docs automatically generated from the python files (like it's done in pytorch).

**Pull request merged**
