### PR TITLE
Allow gcc to be overwritten with an environment variable

### PR DESCRIPTION
**Pull request by hmaarrfk**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Running:
```
$ ufmt format setup.py
Formatted setup.py
$ git diff
```
yeilds mods to things I did not touch
```diff
diff --git a/setup.py b/setup.py
index 70ba0aa2e..85f779f13 100644
--- a/setup.py
+++ b/setup.py
@@ -7,9 +7,9 @@ import subprocess
 import sys
 
 import torch
-from pkg_resources import parse_version, get_distribution, DistributionNotFound
-from setuptools import setup, find_packages
-from torch.utils.cpp_extension import BuildExtension, CppExtension, CUDAExtension, CUDA_HOME
+from pkg_resources import DistributionNotFound, get_distribution, parse_version
+from setuptools import find_packages, setup
+from torch.utils.cpp_extension import BuildExtension, CppExtension, CUDA_HOME, CUDAExtension
 
 
 def read(*names, **kwargs):
```

**Review by datumbox — APPROVED** [review]
LGTM too, thanks!

**Comment by hmaarrfk** [comment]
Thanks

**Comment by hmaarrfk** [comment]
as for the curiosity quesiton. Conda forge compilers are all prefixed, and this helps for cross compilation too.

**Pull request merged**
