### PR TITLE
Don't use named args in MHA calls in VIT Encoder

### PR DESCRIPTION
**Pull request by sovrasov**
Currently in VIT implementation names are used for positional arguments to call `MultiheadAttention.forward`. That makes impossible model analysis with pytorch hooks (they don't see kwargs). See https://github.com/sovrasov/flops-counter.pytorch/issues/95 for example.

cc @datumbox

### CODE REVIEW

**Review by datumbox — APPROVED** [review]
LGTM, thanks!

@sovrasov you will need to sign the CLA before I'm able to merge the PR.

**Comment by sovrasov** [comment]
@datumbox I signed the CLA, perhaps the corresponding bot needs some time to update the status.

**Comment by datumbox** [comment]
Yeah, sometimes it happens. The bot should ping us when it "sees" it and I'll merge afterwards. Thanks!

**Comment by sovrasov** [comment]
@datumbox CLA status was finally updated

**Comment by datumbox** [comment]
@sovrasov Thanks for the ping. It's weird that the bot didn't posts a message, good spot. :)

**Pull request merged**
