### PR TITLE
Remove CUDA 11.7 builds; add 11.8

### PR DESCRIPTION
**Pull request by ptrblck**
CC @atalman @malfet 

cc @seemethere

This PR will be removing cuda 11.7 builds from matrix: https://github.com/pytorch/test-infra/pull/4205

### CODE REVIEW

**Comment by pmeier** [comment]
Hey @ptrblck, we are in the process of killing CircleCI in favor of GitHub Actions (#7611). Thus, your patch would be removed soon. Plus, it is missing the parts on GitHub Actions that also need to be patched. I'll send a few new commits here for future reference.

**Comment by pmeier** [comment]
In the future, we also need to set this on the CMake workflow as I did in 79ae3e6e2851623a86acdb196d19fef18f4bff9a / #7417.

**Comment by pmeier** [comment]
Linux GPU failure looks valid

```
Traceback (most recent call last):
  File "/work/test/test_models.py", line 705, in test_classification_model
    _assert_expected(out.cpu(), model_name, prec=prec)
  File "/work/test/test_models.py", line 155, in _assert_expected
    torch.testing.assert_close(output, expected, rtol=rtol, atol=atol, check_dtype=False, check_device=False)
  File "/opt/conda/envs/ci/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1511, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 50 (2.0%)
Greatest absolute difference: 5.10198974609375 at index (0, 22) (up to 0.2 allowed)
Greatest relative difference: 0.2689853608608246 at index (0, 22) (up to 0.2 allowed)
```

Since the CPU test is just fine, this means that our GPU output now diverges from the CUDA 11.7 one.

We already have quite a few hacks in 

https://github.com/pytorch/vision/blob/bd4471ccc73644ef7dde79f11cc7507d760546e1/test/test_models.py#L676

@NicolasHug do you know if we had something like above before?

**Comment by NicolasHug** [comment]
I'm not sure, the failure is rather concerning especially considering it happens on such a simple arch like ResNet. Are we sure this isn't an upstream regression?

**Review by atalman — APPROVED** [review]

**Review by atalman — APPROVED** [review]

**Review by atalman — APPROVED** [review]

**Pull request merged**
