### PR TITLE
Try to fix mypy

### PR DESCRIPTION
**Pull request by fmassa**
Doesn't know if this will fix it, but worth giving it a try

### CODE REVIEW

**Comment by pmeier** [comment]
I don't think the problem is with the annotations in the file. I think it is either not created or misplaced. Could you verify that the file is actually where it is supposed to be? Something along the line of `tree torchvision/` in the CircleCI job.

**Comment by pmeier** [comment]
Another idea:

I think we should install it with `develop`. As is, it might be that the installed version is not actually the version that is checked.

**Comment by fmassa** [comment]
@pmeier 
> I think we should install it with develop. As is, it might be that the installed version is not actually the version that is checked.

That's probably the issue. I've ssh'ed to the build machine and after build the `version.py` file is not in the project folder.

**Comment by fmassa** [comment]
Superseeded by #2247

**Pull request closed without merging**
