### PR TITLE
Added evaluation code for VOC Pascal dataset

### PR DESCRIPTION
**Pull request by lpuglia**
With the following PR it is possible to train FasterRCNN network using VOC dataset.
It was tested on `fasterrcnn_resnet50_fpn` and got over 70% mAp in 10 epochs.

`python train.py --dataset voc --epochs 15 --lr-steps 10 -b 4 --lr 0.04 --model fasterrcnn_resnet50_fpn --data-path /data/set/`

**notes**:
* I'm pretty sure that the two eval method can easily be merged in a single one but I have no experience with the DistributedDataParallel module so i left it as it is
* The eval code for VOC is file based, probably it is not the best idea to store the results in /tmp/ but it works
* In ConvertVOCtoCOCO the name of the file is converted from string to array of `int8`, this is not as clean as parsing the actual image number, but it generalize better if used on other dataset that have more complex indexing system (e.g. WIDER FACE)
* If you note useless code it may be because i have more advanced features in my repo that I didn't include in the PR

### CODE REVIEW

**Comment by akshitac8** [comment]
Are the changes proposed by @lpuglia are good to use for VOC evaluation?

**Comment by yassineAlouini** [comment]
Hello @lpuglia and sorry for the taking that long for an update.

As far as my understanding goes, it seems that in general, the `references` folder contains few reference scripts to train
various categories of computer vision models. I am not sure what is the strategy for the object detection subfolder (or other subfolders): is it planned to add more datasets and more training recipes or keep it "as is" for now and maybe link to external resources that provide other recipes. @pmeier has more details to share most likely.

In the meantime, there is a new datasets API being designed and since you use an existing dataset (namely `VOCDetection`),
I would like to share some details:

* the main strategy is to pause development while the new API is being finished
* otherwise, you can port the dataset to the new API and then use it in your proposed PR. Of course, someone else can do the migration first in another PR.

That being said, before embarking on this development, let's first check if this feature is still needed. Have you used this branch in some work or do you use another project to do this VOC Pascal evaluation? Or maybe another alternative?

Please share if this feature is still relevant @lpuglia. Many thanks in advance and sorry again for the delay.

**Comment by pmeier** [comment]
@yassineAlouini This PR does not add a new dataset. The VOC detection dataset is supported in the old 

https://github.com/pytorch/vision/blob/a1232c212d7cf84806189910ba83bc36bcea916c/torchvision/datasets/voc.py#L133

as well as the new API:

https://github.com/pytorch/vision/blob/a1232c212d7cf84806189910ba83bc36bcea916c/torchvision/prototype/datasets/_builtin/voc.py#L50

This PR adds support for this dataset in the reference training scripts, which only supports COCO

https://github.com/pytorch/vision/blob/a1232c212d7cf84806189910ba83bc36bcea916c/references/detection/train.py#L37

@lpuglia As @yassineAlouini mentioned, we are currently redesigning the datasets as well as the transforms. This in turn means that we also will adapting the reference scripts quite a bit and it should be easier to add new datasets. 

IIUC, the major part of this contribution is to implement the evaluation method used for VOC. There shouldn't be much changes there, so we can port easily.

That being said, we are trying to close stale PRs. I would open an issue linking this PR so we don't forget (again) about this and close the PR for now. How does that sound?

**Comment by pmeier** [comment]
@yassineAlouini This PR does not add a new dataset. The VOC detection dataset is supported in the old 

https://github.com/pytorch/vision/blob/a1232c212d7cf84806189910ba83bc36bcea916c/torchvision/datasets/voc.py#L133

as well as the new API:

https://github.com/pytorch/vision/blob/a1232c212d7cf84806189910ba83bc36bcea916c/torchvision/prototype/datasets/_builtin/voc.py#L50

This PR adds support for this dataset in the reference training scripts, which only supports COCO

https://github.com/pytorch/vision/blob/a1232c212d7cf84806189910ba83bc36bcea916c/references/detection/train.py#L37

@lpuglia As @yassineAlouini mentioned, we are currently redesigning the datasets as well as the transforms. This in turn means that we also will adapting the reference scripts quite a bit and it should be easier to add new datasets. 

IIUC, the major part of this contribution is to implement the evaluation method used for VOC. There shouldn't be much changes there, so we can port easily.

That being said, we are trying to close stale PRs. I would open an issue linking this PR so we don't forget (again) about this and close the PR for now. How does that sound?

**Comment by lpuglia** [comment]
I'm ok to close this, the feature is not needed anymore

**Pull request closed without merging**
