### PR TITLE
Document that datasets support pathlib.Path

### PR DESCRIPTION
**Pull request by NicolasHug**
All datasets' `root` param already supports `pathlib.Path` because they just call `os.expanduser()` under the hood, which will nicely handle `Path`. So this PR just adds that to the docstrings.

This isn't explicitly tested, but https://github.com/pytorch/vision/pull/8320 should prove that `Path` works fine (@pmeier if there's a better way to test that consistently, LMK).

I'm not updating the type annotations because in all honestly I really, REALLY don't want to spend my time doing that. I gave it a go adding the annotations mentioned in https://github.com/pytorch/vision/issues/8120#issue-2000458034 to just the imagenet file, and after running for 3+ minutes mypy started to give me hell. So I'm just not doing it. If someone wants to spend the time and add the annotations, I'll be happy to stamp the PR.

With that and https://github.com/pytorch/vision/pull/8314, https://github.com/pytorch/vision/issues/8120 could be closed.

### CODE REVIEW

**Comment by vfdev-5** [comment]
Can you post here some of the mypy errors you see with imagenet and updated typing hints?

**Comment by NicolasHug** [comment]
Sorry, mypy takes 3+ minutes to run on my machine and honestly I just don't want to go back to it knowing that I won't be addressing type annotations for all those 40+ files anyway.

**Review by pmeier — APPROVED** [review]
I've added the type annotations. Regarding testing, #8320 is what I would have done as well. If you want the extra security, we could potentially implement a smoke test for that, but not sure if its worth it.

**Comment by pmeier** [comment]
BC linter fails with these warnings:

```
Warning: Function find_classes: directory changed from str to Union[str, Path]
Warning: Function make_dataset: directory changed from str to Union[str, Path]
Warning: Function DatasetFolder.make_dataset: directory changed from str to Union[str, Path]
Warning: Function DatasetFolder.find_classes: directory changed from str to Union[str, Path]
Warning: Function load_meta_file: root changed from str to Union[str, Path]
Warning: Function parse_devkit_archive: root changed from str to Union[str, Path]
Warning: Function parse_train_archive: root changed from str to Union[str, Path]
Warning: Function parse_val_archive: root changed from str to Union[str, Path]
```

Yes, annotations have changed, but they were expanded. Passing `str` is still fully acceptable.

**Comment by pmeier** [comment]
Here is the [green `mypy` job](https://github.com/pytorch/vision/actions/runs/8323087993/job/22772049733?pr=8321).

**Comment by NicolasHug** [comment]
Thanks @pmeier

**Pull request merged**
