### PR TITLE
Warn if torchvision imported from repo root

### PR DESCRIPTION
**Pull request by jamt9000**
Suggested fix for #2239

(Should it be an error or are there cases where it would be desired during development?)

### CODE REVIEW

**Comment by andfoy** [comment]
Hi @jamt9000, thanks for this contribution! My only comment here is that we should rather check for the existence of the compiled files `_C.so` in both Mac and Linux and `_C.pyd` on Windows, since that shared library is the one that might cause failures when is not found.

**Comment by andfoy** [comment]
Maybe you can use this call to importlib to find it:
https://github.com/pytorch/vision/blob/217e26fcb168aeea00a6341c2a478237f7e75808/torchvision/io/image.py#L17

**Comment by jamt9000** [comment]
@andfoy It looks like torchvision checks for _C.so already 

https://github.com/pytorch/vision/blob/7a36388cfa4cef309094f3d9aa4606055435f4b4/torchvision/extension.py#L16-L19

https://github.com/pytorch/vision/blob/7a36388cfa4cef309094f3d9aa4606055435f4b4/torchvision/extension.py#L23-L27

and can continue with reduced functionality if it is missing.

Maybe it should always show a warning when _HAS_OPS = False (which could be for several reasons) and then also
show an extra message if the reason for this seems to be because of being in the root dir.

**Comment by fmassa** [comment]
@jamt9000 yes, adding checks for the existence of `_HAS_OPS` is something that we are considering doing, see for example https://github.com/pytorch/vision/pull/2467 (which makes me think that I should revamp that PR, I completely forgot about it)

**Comment by fmassa** [comment]
and I agree with @andfoy , we should instead check for the existence of the `_C` library.
I for example always run torchvision from the root folder, but I install it via `python setup.py build develop`, so it works fine. Also a few other systems might package things weirdly, so it's better to error on the safe side.

**Review by fmassa — APPROVED** [review]
LGTM, thanks a lot!

@mthrok @cpuhrsch this is something that could be interesting to be done to the other libraries as well. Also, I'm not sure if the current implementation works as expected in fbcode or if we need to do something else, but let's see.

**Pull request merged**
