### PR TITLE
remove Travis CI status badge from README

### PR DESCRIPTION
**Pull request by pmeier**
Although we migrated all remaining workflows from Travis CI to CIrcleCi in #3137 the status badge in the README was not upgraded:

This PR replaces this with

This is the default badge style from CircleCI, but we could also go with 

for consistency.

### CODE REVIEW

**Comment by pmeier** [comment]
After some more research, it seems that the CircleCI badge is not reliable. Without knowing the internals, I imagine it does something like a logical OR instead of AND with the individual workflows. 

There seem to be a lot of discussion about this in their support forums. As of now I think we should not place this badge since it might be misleading. @fmassa?

**Comment by pmeier** [comment]
I've contacted the CircleCI support about this. The badge only shows the status of the last run workflow which is on the top of the list in their UI, i.e. `nightly`. There is now a [feature request](https://circleci.canny.io/cloud-feature-requests/p/status-badge-for-pipeline-status) for what we need. Until then we have only two options if we want the status badge:

1. Determine the most important workflow and move it to run last.
2. Merge all workflows into one.

IMO both options are subpar. Thus, I suggest we remove the badge for now and only re-add it if the feature request went through.

**Review by fmassa — APPROVED** [review]
Thanks @pmeier!

**Comment by fmassa** [comment]
I agree with your current solution, we can add the CircleCI badge in the future

**Pull request merged**
