### PR TITLE
Fix augmentation space to be uint8 compatible

### PR DESCRIPTION
**Pull request by jopo666**
A simple fix that addresses #4805.

cc @vfdev-5 @datumbox

### CODE REVIEW

**Comment by jopo666** [comment]
Maybe unit tests should also be extended to cover these types of bugs?

**Review by datumbox — APPROVED** [review]
LGTM, thanks for fixing it.

**Review by prabhat00155 — APPROVED** [review]
Thanks @jopo666! Could you also perhaps add a unit test to cover this case?

**Comment by datumbox** [comment]
@prabhat00155 What are your thoughts on testing this?

On the AutoAugmentation module we currently don't have any similar tests to check for misconfigurations of the methods and it's unclear how such a test would look like. One place we could potentially add it is on the implementation of `solarize`. For example we could add an assertion to ensure that the threshold is within bounds and then create a test to check the assertion is triggered:

https://github.com/pytorch/vision/blob/d367a01a18a3ae6bee13d8be3b63fd6a581ea46f/torchvision/transforms/functional_tensor.py#L885-L886

Probably a similar assertion is worth to be added at `posterize` for the number of bits.

Finally I wonder if it's worth merging this so that we cover the bug and add the tests on a follow up PR. No strong opinions, just want to make sure this bug fix will be merged. :)

**Comment by prabhat00155** [comment]
> @prabhat00155 What are your thoughts on testing this?
> 
> On the AutoAugmentation module we currently don't have any similar tests to check for misconfigurations of the methods and it's unclear how such a test would look like. One place we could potentially add it is on the implementation of `solarize`. For example we could add an assertion to ensure that the threshold is within bounds and then create a test to check the assertion is triggered:
> 
> https://github.com/pytorch/vision/blob/d367a01a18a3ae6bee13d8be3b63fd6a581ea46f/torchvision/transforms/functional_tensor.py#L885-L886
> 
> Probably a similar assertion is worth to be added at `posterize` for the number of bits.
> 
> Finally I wonder if it's worth merging this so that we cover the bug and add the tests on a follow up PR. No strong opinions, just want to make sure this bug fix will be merged. :)

Thanks @datumbox for the explanation. Makes sense to merge this PR then. We could look at adding tests in a follow-up PR.

**Comment by datumbox** [comment]
@prabhat00155 Sounds great, thanks for the flexibility. I've created a ticket for this so that we don't forget: #4818 

Feel free to merge on green CI.

**Pull request merged**
