### PR TITLE
Updated CONTRIBUTING guide.

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:

- Added conda-forge channel, otherwise old pytorch nightly is proposed.

### CODE REVIEW

**Review by datumbox — APPROVED** [review]
LGTM, thanks!

**Comment by fmassa** [comment]
cc @seemethere should we update the installation instructions in the PyTorch website to take this into account?

**Comment by seemethere** [comment]
The conda installation instructions for Python 3.9  include a disclaimer about installing with `conda-forge`.

Is this going to be a hard requirement for `torchvision` now?

**Comment by fmassa** [comment]
> Is this going to be a hard requirement for torchvision now?

I'm not even sure anymore why we are adding `conda-forge` as a dependency -- is it because of `libjpeg` / `libpng` ? Because `ffmpeg` is currently not a hard-dependency for torchvision, so if it's the reason why we are adding the `conda-forge` dependency we can probably remove it.

cc @andfoy

**Comment by vfdev-5** [comment]
@fmassa now, I'm not that sure even if using or not `conda-forge` channel we can properly install pytorch nightly with cudatoolkit=11.0. Doing that as
```
conda install pytorch cudatoolkit=11.0 -c pytorch-nightly -c conda-forge
> 
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.12.5  |       ha878542_0         137 KB  conda-forge
    certifi-2020.12.5          |   py38h578d9bd_1         143 KB  conda-forge
    conda-4.9.2                |   py38h578d9bd_0         3.0 MB  conda-forge
    libuv-1.40.0               |       hd18ef5c_0         920 KB  conda-forge
    python_abi-3.8             |           1_cp38           4 KB  conda-forge
    pytorch-1.8.0.dev20201112  |py3.8_cuda11.0.221_cudnn8.0.3_0       713.5 MB  pytorch-nightly
    typing_extensions-3.7.4.3  |             py_0          25 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       717.8 MB
```
Proposed pytorch is still 1.8.0.dev20201112. Same with `conda install pytorch cudatoolkit=11.0 -c pytorch-nightly`.

But using cudatoolkit=10.2 with or without conda-forge, proposes more recent version
```
conda install pytorch cudatoolkit=10.2 -c pytorch-nightly
> The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cudatoolkit-10.2.89        |       hfd86e86_1       365.1 MB
    pytorch-1.9.0.dev20210216  |py3.8_cuda10.2_cudnn7.6.5_0       673.6 MB  pytorch-nightly
    typing_extensions-3.7.4.3  |     pyha847dfd_0          25 KB
    ------------------------------------------------------------
                                           Total:        1.01 GB
```

If we would like to install cudatoolkit=11.2, seems like there is no way to install packages without specifying conda-forge channel...

**Comment by andfoy** [comment]
Actually, conda-forge installations may lead to incompatibilities between libjpeg/jpegturbo, since PIL depends on the latter, and jpegturbo is not available in Windows AFAIK. Also there could be potential errors with FFmpeg

**Comment by datumbox** [comment]
I'm on Python 3.8 and I'm getting also quite old versions:
```
conda install pytorch torchvision cudatoolkit=11.0 -c pytorch-nightly -c conda-forge
>

Collecting package metadata (current_repodata.json): done
Solving environment: done

[...]

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytorch-1.8.0.dev20210208  |py3.8_cuda110_cudnn8.0.5_0       625.0 MB  pytorch-nightly
    torchvision-0.9.0.dev20210211|       py38_cu110        25.8 MB  pytorch-nightly
    ------------------------------------------------------------

[...]
```

Where is the latest nightly?

**Comment by vfdev-5** [comment]
@datumbox try to install with cudatoolkit=11.2, may help

**Comment by datumbox** [comment]
You are right:

```
conda install pytorch torchvision cudatoolkit=11.2 -c pytorch-nightly -c conda-forge
>

[...]

    package                    |            build
    ---------------------------|-----------------
    pytorch-1.9.0.dev20210217  |py3.8_cuda11.2_cudnn8.1.0_0       911.2 MB  pytorch-nightly
    torchvision-0.9.0.dev20210221|       py38_cu112        26.0 MB  pytorch-nightly\
    ------------------------------------------------------------

[...]

```

**Pull request merged**
