### PR TITLE
Refactor transformations by extracting probabilities to get_params() method

### PR DESCRIPTION
**Pull request by kondela**
Fixes: #3066

Transformations that need to be refactored since they call `torch.rand(1)` in `forward()`:
- [x] RandomApply
- [x] RandomHorizontalFlip
- [x] RandomVerticalFlip
- [x] RandomGrayscale
- [x] RandomErasing 
- [x] RandomPerspective

Not sure how to handle the last two as they already have `get_params()` method define and the probability needs to be drawn before `get_params()` is called, for example `RandomPerspective()`:

https://github.com/pytorch/vision/blob/7f1a05a346cf1d5c6fe6b0af3ffb3e4b0b651ff3/torchvision/transforms/transforms.py#L708-L711

### CODE REVIEW

**Comment by fmassa** [comment]
Hi,

Thanks for the PR!

I've just made a comment in https://github.com/pytorch/vision/pull/3065#discussion_r536000529 which explains my reasoning behind `get_params`. Let me know what you think

**Comment by kondela** [comment]
> Hi,
> 
> Thanks for the PR!
> 
> I've just made a comment in [#3065 (comment)](https://github.com/pytorch/vision/pull/3065#discussion_r536000529) which explains my reasoning behind `get_params`. Let me know what you think

Hi, it seems that the discussion in that thread is still ongoing. Do we want to merge it as it is, i.e leave` RandomErasing()`,  `RandomPerspective()` unchanged or how do we proceed with these two as we can't simply extract `torch.rand(1).item()` to `get_params()`?

Thanks!

**Comment by datumbox** [comment]
@kondela I wonder if you don't mind to finish the 2 remaining methods so that this PR is complete. I have also a bunch of operators that are pending to be merged and use the specific idiom, so if we decide to return a boolean instead of a weight, I can fix yours and mine in the same PR. I don't really have a preference, let me know. :)

**Comment by kondela** [comment]
> @kondela I wonder if you don't mind to finish the 2 remaining methods so that this PR is complete. I have also a bunch of operators that are pending to be merged and use the specific idiom, so if we decide to return a boolean instead of a weight, I can fix yours and mine in the same PR. I don't really have a preference, let me know. :)

Hey @datumbox I refactored the last two transformations, please see if its okay. I was hoping for a hint since as I said in https://github.com/pytorch/vision/pull/3098#issue-531224076 that these two transformations are different.

**Comment by datumbox** [comment]
> I was hoping for a hint since as I said in [#3098 (comment)](https://github.com/pytorch/vision/pull/3098#issue-531224076) that these two transformations are different.

Hmm, I just saw that you edited your original message. You are right, let us get back to you on this one.

**Comment by kondela** [comment]
> > I was hoping for a hint since as I said in [#3098 (comment)](https://github.com/pytorch/vision/pull/3098#issue-531224076) that these two transformations are different.
> 
> Hmm, I just saw that you edited your original message. You are right, let us get back to you on this one.

Ok, let me know :). I will wait with fixing the failing tests.

**Comment by datumbox** [comment]
@kondela FYI we have not forgotten about this. It's just unclear right now which path we are going to take.

Note that we recently merged PR #3123 which adds more transforms. Originally I took the approach of your PR for structuring the random params but I rolled it back (see https://github.com/pytorch/vision/pull/3123#discussion_r542369102) until we are certain on how to handle this.

**Comment by datumbox** [comment]
Unfortunately, it seems we need to rethink the plan to cover better cases such as Object Detection. See #3286 for more details on the discussion.

@kondela Thank you for sending the PR, I'll close it for now but I'm happy to ping you once we have a more concrete proposal on how to move forwards.

**Pull request closed without merging**
