### PR TITLE
Add download tests for remaining datasets

### PR DESCRIPTION
**Pull request by pmeier**
This adds the remaining download tests for

- `KMNIST`
- `EMNIST`
- `QMNIST`
- `Omniglot`
- `Phototour`
- `SBDataset`
- `SBU`
- `SEMEION`
- `STL10`
- `SVHN`
- `USPS`
- `CelebA`
- `WIDERFace`

and fixes the test for `CIFAR100`.

### CODE REVIEW

**Review by datumbox — APPROVED** [review]
LGTM.

**Comment by pmeier** [comment]
The three failing URLs

- http://matthewalunbrown.com/patchdata/notredame_harris.zip
- http://matthewalunbrown.com/patchdata/yosemite_harris.zip
- http://matthewalunbrown.com/patchdata/liberty_harris.zip

are working fine. Either re-run the download tests or accept them as fluke an merge this :wink:

**Comment by datumbox** [comment]
@pmeier There are still a [few failures](https://github.com/pytorch/vision/pull/3338/checks?check_run_id=1815833958). I think it's important to see them passing and address any flakiness before merging. Let me know what you think.

**Comment by pmeier** [comment]
@datumbox The failing URLs reported in the test are the ones from my last comment. They are working and I've not touched `Places365`. IMO this was just a fluke. Lets see what the new CI run brings.

**Comment by pmeier** [comment]
So, I was wrong. The request indeed timed out. I've added some logic to better capture timeouts. As for the reason why these tests times out: I'm not sure yet. I cannot produce the timeout locally.

**Review by datumbox — APPROVED** [review]
LGTM. I left a few non-blocking nits that can be addressed on future PRs.

**Pull request merged**
