### PR TITLE
Adds Anchor tests

### PR DESCRIPTION
**Pull request by oke-aditya**
Followup PR. Adds tests for #2960

Somehow I was not able to run tests locally. I'm unsure if this is fixed quite well.

I'm not sure what and how tests can or should be for this, somehow it simply creates an empty Anchor and no ValueErorr is generated.

### CODE REVIEW

**Comment by zhiqwang** [comment]
Hi, I think the function

https://github.com/pytorch/vision/blob/052edcecef3eb0ae9fe9e4b256fa2a488f9f395b/test/test_onnx.py#L197-L200

and

https://github.com/pytorch/vision/blob/052edcecef3eb0ae9fe9e4b256fa2a488f9f395b/test/test_onnx.py#L273-L280

may be added to the unittest?

**Comment by fmassa** [comment]
Hi

Thanks for the PR!

@oke-aditya Test failures are related, can you have a look?

@zhiqwang yes, we can improve testing of AnchorGenerator to check for correctness as well, and this is just a first PR to start this effort. I think tests which would be useful would be tests for a few known values of a very small feature map size, so that we know the ground-truth.
Would you be willing to help with adding more tests to AnchorGenerator?

**Comment by oke-aditya** [comment]
Yes the failures are related. The reason is I'm not able to generate `ValueError` which I created with last PR.
Somehow I am not able to figure out why a simple tuple doesn't raise this.
Can someone help me ? 😓

**Comment by fmassa** [comment]
@oke-aditya might be because of https://github.com/pytorch/vision/blob/5a4bb19db56529e824a92048fa8e9b50f53fb3dd/torchvision/models/detection/anchor_utils.py#L42-L46 , which was there to help on those cases.

I think you should add instead a tuple of tuple, but with different sizes

**Comment by zhiqwang** [comment]
> @zhiqwang yes, we can improve testing of AnchorGenerator to check for correctness as well, and this is just a first PR to start this effort. I think tests which would be useful would be tests for a few known values of a very small feature map size, so that we know the ground-truth.
> Would you be willing to help with adding more tests to AnchorGenerator?

Hi @fmassa , Yep, It's my pleasure, I will trace this current PR, and check wath can I contribute to following this PR.

**Comment by oke-aditya** [comment]
I'm really unsure what code would generate the error. I have tries various combinations locally but no sucess yet.

Following is what I tried to generate the `ValueError` but somehow it isn't getting generated

I think there is some confusion.

```
assert len(sizes) == len(aspect_ratios)
```
This assert actually checks if sizes and aspect ratios match.

This can be easily triggered.
E.g. case
```
incorrect_sizes = ((128, 258, 512), (128, 32))
incorrect_aspects = ((0.5, 1.0, 2.0),),
```

But this
```
if not (len(grid_sizes) == len(strides) == len(cell_anchors)):
```

is a call to very internal code in the `forward` method which makes it quite hard to get such test cases.

Some test cases that didn't work to fix the `ValueError`

```
incorrect_sizes = ((128), (258, 32), )
incorrect_aspects = ((0.5, 2.0), (3.0))

incorrect_sizes = ((128, 128, 128), (258, 32), )
incorrect_aspects = ((0.5, 2.0), (3.0))
```

Passing only tuple too didn't work. I think that it needs further digging into code.

**Comment by fmassa** [comment]
@oke-aditya you need to set the `features` to have a different (wrong?) number of feature maps

**Comment by oke-aditya** [comment]
Ah, now I get it. I have fixed the test. 😄

**Review by fmassa — APPROVED** [review]
Thanks!

**Pull request merged**
