### PR TITLE
Testing pyav

### PR DESCRIPTION
**Pull request by fmassa**
Let's see when it breaks

### CODE REVIEW

**Comment by andfoy** [comment]
It seems that other test is causing video ones to fail:
imagen

**Comment by andfoy** [comment]
`test_io_opt` seems to be the culprit for the failure of the tests, I don't know what is the intent of that test

imagen

**Comment by andfoy** [comment]
The only effect that `set_video_backend('video_reader')` has over `test_io.py` is related to the codecs used to encode/decode the test videos: 

https://github.com/pytorch/vision/blob/217e26fcb168aeea00a6341c2a478237f7e75808/test/test_io.py#L45

That means that under the current circumstances `test_io` is only testing the video_reader backend, rather than the PyAV one.

**Comment by fmassa** [comment]
@andfoy this is great debugging, thanks!

So, `test_io_opt` is there to test the `video_reader` backend of `read_video`, without having to resort to copy-pasting all the tests. If it is negatively interfering with `test_io`, we should do something to change that.

It is great that we now know the reason why this wasn't working before, now we need to understand why the partial reading of files is not working with the `video_reader` backend.

@bjuncek you have used the `video_reader` backend for partial reads recently, right? Can you check again if those tests are passing or not in your system?

**Comment by bjuncek** [comment]
@fmassa I pulled your branch and run the tests in my PR. They are passing locally for me but that has always been the case so lets see what CI says

**Comment by andfoy** [comment]
I think we can close this one

**Pull request closed without merging**
