### PR TITLE
Removing/replacing Py3.6 references.

### PR DESCRIPTION
**Pull request by datumbox**
Removing remaining references of python 3.6 from CI and replacing where necessary with later python versions.

cc @seemethere

### CODE REVIEW

**Comment by pmeier** [comment]
@malfet @seemethere Will the next release also happen for Python 3.10? If yes, we should basically migrate 3.6 -> 3.10 everywhere

**Comment by datumbox** [comment]
All unit-test failures are unrelated. This is due to changes on PIL v9 (released 2 days ago) which switched to libjpeg-turbo for both linux and mac. The CI breakages are investigated separately.

**Comment by pmeier** [comment]
> Will the next release also happen for Python 3.10?

Seems like it: pytorch/pytorch#70917

**Review by NicolasHug — APPROVED** [review]
Stamping to unlock, I haven't checked myself whether 3.9 or 3.10 will be supported

**Comment by datumbox** [comment]
@malfet @seemethere I'll merge to simplify the code but if you have input please let me know and I can fix on a follow up PR. Thanks!

**Pull request merged**
