### PR TITLE
Hash contents of directory

### PR DESCRIPTION
**Pull request by bgokbakan**
Added calculate_md5() the facility to hash the contents of  a directory. This can be used to check the integrity of the contents of an already downloaded dataset.

### CODE REVIEW

**Comment by NicolasHug** [comment]
@bgokbakan  thanks for the PR. The code looks good but the new `hash_dir` functionality isn't being used anywhere yet. Where do you think this could be useful?

CC @pmeier, could this be useful to check the dataset or would this be overkill / take too much time?

**Review by Sifat1998 — APPROVED** [review]

**Comment by pmeier** [comment]
> could this be useful to check the dataset or would this be overkill / take too much time?

Yes, for larger datasets this will take to much time. Even for smaller datasets I don't see the point yet. If checksums are provided, they correspond to the individual files, so we need to check them individually.

@bgokbakan What is the intention behind this PR?

**Comment by bgokbakan** [comment]
> > could this be useful to check the dataset or would this be overkill / take too much time?
> 
> Yes, for larger datasets this will take to much time. Even for smaller datasets I don't see the point yet. If checksums are provided, they correspond to the individual files, so we need to check them individually.
> 
> @bgokbakan What is the intention behind this PR?

It's a trivial feature, its purpose is to check whether the extracted files were corrupted somehow, c.f. https://github.com/pytorch/vision/blob/cd1728d09bd6d4288b5833249ba09b00529809f9/torchvision/datasets/caltech.py#L112

**Comment by fmassa** [comment]
Hi @bgokbakan 

Thanks for the PR!

Just so that I understand, if we check the hash of the zipped file and it matches, then there is no need in computing the hash of the uncompressed files, correct?

**Comment by pmeier** [comment]
> It's a trivial feature

True, but if it is not needed anywhere, there is no point in adding it.

> its purpose is to check whether the extracted files were corrupted somehow, c.f. 

For large datasets this takes too long. This is not feasible since it has to performed every time a dataset is instantiated. 

Do you have a specific use case in mind, where this is needed?

**Comment by NicolasHug** [comment]
Thanks for the PR @bgokbakan , unfortunately it seems that the use-case for this isn't obvious, according to the above discussion. I'll close the PR to keep things tidy, but please feel free to re-open if you wish to make a stronger case for this feature.

**Pull request closed without merging**
