### PR TITLE
Revert "addressing #3805: remove deprecated function call 3"

### PR DESCRIPTION
**Pull request by prabhat00155**
Reverts pytorch/vision#3861

### CODE REVIEW

**Review by fmassa — APPROVED** [review]

**Comment by fmassa** [comment]
@bjuncek we got internal failures with this PR.

Prabhat will be sending a follow-up PR that addresses the issues

**Comment by fmassa** [comment]
@prabhat00155 Just a remainder that you forgot to add the `[FBcode->GH]` tag, as we won't be merging the other PR in fbcode so we will need to skip this one

**Comment by prabhat00155** [comment]
> @prabhat00155 Just a remainder that you forgot to add the `[FBcode->GH]` tag, as we won't be merging the other PR in fbcode so we will need to skip this one

@fmassa Isn't `[FBcode->GH]` to be added when we import from FBcode?

**Comment by NicolasHug** [comment]
> Isn't [FBcode->GH] to be added when we import from FBcode?

It needs to be added when we want to ignore a PR during the GH -> fbcode syncing. PRs imported from fbcode are a subset of that only. But you do make a point that the tag isn't as general as it could ;)

**Comment by prabhat00155** [comment]
> > Isn't [FBcode->GH] to be added when we import from FBcode?
> 
> It needs to be added when we want to ignore a PR during the GH -> fbcode syncing. PRs imported from fbcode are a subset of that only. But you do make a point that the tag isn't as general as it could ;)

@NicolasHug Thanks for explaining that. Perhaps we should have a tag called `FBCode Ignore` or something like that.

**Comment by datumbox** [comment]
@prabhat00155 There is another param you can use on the script to ignore a specific commit id. Just note it operates on full git hashes.

**Pull request merged**
