### PR TITLE
Update functional.py

### PR DESCRIPTION
**Pull request by yoondonghwee**
Correct the documentation
i is the y_coordinate, j is the x_coordinate

### CODE REVIEW

**Comment by pmeier** [comment]
Actually, the current comment is correct. I'll try to explain:

The variable `i` describes the vertical or _y_ direction and `j` the horizontal or _x_ direction. You can deduce this from the fact that `i` is added to the height `h`, which would make no sense if `i` would represent a horizontal coordinate.

https://github.com/pytorch/vision/blob/a91fe7221b55c55dbbc23c23aecf33d470a5c08e/torchvision/transforms/functional.py#L368

The same is of course true for `j`.

From the [pillow documentation for `Image.crop()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.crop)

> `box` – The crop rectangle, as a (left, upper, right, lower)-tuple

Thus, our call is indeed correct since `j` is the _left_ part and `i` the _upper_ part in

https://github.com/pytorch/vision/blob/a91fe7221b55c55dbbc23c23aecf33d470a5c08e/torchvision/transforms/functional.py#L357-L358

---

However, I agree that the current documentation does not reflect this well. We should update it to avoid any misunderstandings in the future.

**Comment by yoondonghwee** [comment]
Thank you for the answer.
I thought the documentation of the method is ambiguous.
I hope it will be clarified soon.

2019년 9월 11일 (수) 오후 4:46, Philip Meier <notifications@github.com>님이 작성:

**Comment by fmassa** [comment]
One of the problems here is that Pillow uses a different convention than PyTorch for representing the sizes, (`width, height` instead of `height, width`), and this can bring some confusion.

We decided to keep the PyTorch convention, where we represent it as `height, width`, and thus the indices are passed as `y, x` (in plane coordinates), which are also represented as `i, j`.

If those indexing conventions are a bit confusing, check the [numpy.meshgrid documentation for the indexing argument](https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html), which explains this in a bit more detail.

Can you update the PR to make the description a bit more clear?

**Comment by fmassa** [comment]
Superseeded by https://github.com/pytorch/vision/pull/1388

**Pull request closed without merging**
