### PR TITLE
Fix edge cases on test_backbone_utils when the sampled node is buffer with integer value

### PR DESCRIPTION
**Pull request by YosuaMichael**
Cherry pick https://github.com/pytorch/vision/pull/6090 from main into `release/0.13`

### CODE REVIEW

**Comment by YosuaMichael** [comment]
The type check failed, but seems like it is not related with this PR. It affect all the model loading. Will investigate...

**Review by datumbox — APPROVED** [review]
LGTM. Looks like the breakage is completely unrelated. Possibly due to a change on Core??? I recommend prior merging this PR to open a dummy PR against the release branch to confirm.

**Comment by YosuaMichael** [comment]
Seems like the problem in typecheck is not because of this PR: https://github.com/pytorch/vision/pull/6092
I have created this dummy PR to check.

I am not too sure what cause this problem, but I have a fix for the type check, will create separate PR for it

**Comment by datumbox** [comment]
The problem is not on your side. We should merge this and review the issue on a separate PR.

**Pull request merged**
