### PR TITLE
Upgrade clang version for M1 test

### PR DESCRIPTION
**Pull request by albanD**
See if a more recent clang helps

EDIT: looks like it does.
Note that this is NOT changing the build job or any binary building job!

Seems to fix https://github.com/pytorch/vision/issues/6142

### CODE REVIEW

**Review by malfet — APPROVED** [review]

**Review by atalman — APPROVED** [review]

**Comment by vfdev-5** [comment]
@albanD if we do not install `clang==14.0.4` what does it use by default to compile vision ? Maybe we should trace that in `setup.py` and ask users to install latest clang

**Comment by albanD** [comment]
It uses 13.0.0 from what I was discussing with @malfet 

torch is built with `13.1.6`. And if vision is built with `13.1.6`, it also fixes the problem. Note that the clang version itself might not be the core of the issue and the "fix" might come from the fact that the toolchain that comes with the newer clang version avoids the issue.

I went with `14.0.4` here as conda-forge only has `13.0.X` versions. So I had to go to `14.0` to get `13.1+`.

**Comment by albanD** [comment]
So the problem is not that "clang is too old" but some misterious bad interaction between 13.1 (used to build torch) and 13.0 (used to build vision)

**Comment by albanD** [comment]
Canceling this as the conda-forge dependency is not great. @malfet will update the runners directly with 13.1.6+

**Pull request closed without merging**
