### PR TITLE
Zero-init the residual branch in resnet

### PR DESCRIPTION
**Pull request by ppwwyyxx**

### CODE REVIEW

**Comment by ppwwyyxx** [comment]
@fmassa Could you take a look?

**Comment by fmassa** [comment]
Hey,

I think the only way I'd accept such modifications would be if we pass extra arguments into the constructor to modify the way we initialize the weights.

I don't want to break backwards-compatibility as lots of people are using this model already.

**Comment by ppwwyyxx** [comment]
This only makes the model better without any user-side changes. But sure I can make it optional.

**Comment by vfdev-5** [comment]
Just wondering @ppwwyyxx could you benchmark this improvement with pytorch (or using tensorpack) ?

**Comment by ppwwyyxx** [comment]
I have. I'm able to get 23.6~23.7 with pytorch. Without this change it's about 24.1

**Comment by ppwwyyxx** [comment]
@fmassa I added it as an argument

**Pull request merged**
