### PR TITLE
Replace hardcoded error code with ENODATA

### LINKED ISSUE #3274: Different ENODATA code on macOS
## 🐛 Bug
It seems macOS ENODATA code (96) is different than the Linux one (61). The Linux code is currently hard-coded in `Video.cpp`, which results in an (unnecessary?) error being shown when using the video decoder on macOS:

https://github.com/pytorch/vision/blob/7d831a2f9b3ebab9eb8e5c899cf70b103ad6908a/torchvision/csrc/io/video/Video.cpp#L314-L318

cc @bjuncek

### PR DESCRIPTION
**Pull request by SliMM**
The video reader suppressed code 61 (`ENODATA` on Linux) that occured at the end of a stream and logged an `INFO` message. On macOS `ENODATA` has a different code (96), which resulted in an error message being logged.

This small patch replaces the hard-coded value with the `ENODATA` constant to suppress the macOS error.

Fixes #3274

### CODE REVIEW

**Comment by bjuncek** [comment]
Looks good to me; LGTM if there are no test failures

**Comment by SliMM** [comment]
> Looks good to me; LGTM if there are no test failures

Looks like there are some failing tests in master, that are also failing here.

**Comment by datumbox** [comment]
> Looks like there are some failing tests in master, that are also failing here.

Don't worry these are not from your commit. :)

**Review by datumbox — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
