### PR TITLE
Downgrade tqdm version to 4.19 for py2.7

### PR DESCRIPTION
**Pull request by vishwakftw**
This was observed during discussion in #541 . This will prevent spurious error while downloading.

cc @fmassa

### CODE REVIEW

**Comment by fmassa** [comment]
Do we know what's the reason why we have the error message with newer versions of tqdm? It might be better to find out the reason and address it properly?

**Comment by vishwakftw** [comment]
This is an unsolved bug in `tqdm`. https://github.com/tqdm/tqdm/issues/548 .

**Comment by vishwakftw** [comment]
@fmassa is this good to go?

**Comment by fmassa** [comment]
Thanks!

**Pull request merged**
