### PR TITLE
Upgrade nightly wheels to ROCm5.3

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Dependent on PR https://github.com/pytorch/pytorch/pull/89101

cc @jeffdaily

### CODE REVIEW

**Review by datumbox — COMMENTED** [review]
The changes look good to me and the tests pass. Nevertheless I observed that some of the jobs such as `Build Linux Wheels / pytorch/vision / manywheel-py3_10-rocm5_1_1 (pull_request) ` still run for 5.1.1 which means there are more places that need to be modified. I think this is related to @osalpekar's work of migrating from CircleCI to GA.

I've added the RelEng team to confirm.

**Comment by jithunnair-amd** [comment]
> The changes look good to me and the tests pass. Nevertheless I observed that some of the jobs such as `Build Linux Wheels / pytorch/vision / manywheel-py3_10-rocm5_1_1 (pull_request) ` still run for 5.1.1 which means there are more places that need to be modified. I think this is related to @osalpekar's work of migrating from CircleCI to GA.
> 
> I've added the RelEng team to confirm.

@datumbox Yes, I noticed that too. I filed a PR https://github.com/pytorch/test-infra/pull/1219 for upgrading to ROCm5.3. cc @osalpekar

**Comment by datumbox** [comment]
@jithunnair-amd Thanks for confirming! 

@osalpekar Do you advise merging this PR or wait for the other fix? My understanding is that it can be merged but I could be wrong. Thanks!

**Comment by osalpekar** [comment]
Thanks @jithunnair-amd  and @datumbox. We should be good to merge both in any order! Note that the test-infra PR will be the one that actually changes the ROCm versions in the nightly wheels, since those are build via GHA. The remaining py3.7 CircleCI jobs that are changed by this PR are just for the docs build.

**Review by osalpekar — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@datumbox The test-infra PR is merged. Is this PR good to go now?

**Comment by jithunnair-amd** [comment]
@datumbox @osalpekar While the PR https://github.com/pytorch/test-infra/pull/1219 was merged on Dec 2, I see that rocm5.3 wheels haven't started being published yet for torchvision (https://download.pytorch.org/whl/nightly/rocm5.3/torchvision/). Even the latest rocm5.2 wheels for torchvision were only upto Nov 21 (https://download.pytorch.org/whl/nightly/rocm5.3/torchvision/). Would you know why?

**Comment by datumbox** [comment]
@atalman Any thoughts?

**Comment by osalpekar** [comment]
@jithunnair-amd I see the Dec 5 rocm5.3 wheels at that page. They're closer to the top of the page for some reason (the ordering of the jobs on the page is a little strange). Here's the name and link for reference:
```
[torchvision-0.15.0.dev20221205+cpu-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.15.0.dev20221205%2Bcpu-cp310-cp310-linux_x86_64.whl)
```

And successful build job: https://github.com/pytorch/vision/actions/runs/3620045031/jobs/6101821737.

I see the Dec 5 rocm5.2 wheels on the nightly page as well (this time near the middle of the page): https://download.pytorch.org/whl/nightly/rocm5.2/torchvision/

**Comment by malfet** [comment]
> ```
> [torchvision-0.15.0.dev20221205+cpu-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.15.0.dev20221205%2Bcpu-cp310-cp310-linux_x86_64.whl)
> ```

@osalpekar perhaps I'm reading the package suffix name incorrectly, but this looks like a CPU build rather than ROCM accelerated one, isn't it?

**Comment by osalpekar** [comment]
@malfet You're right, I see that issue and working on a fix now

**Comment by osalpekar** [comment]
Just merged https://github.com/pytorch/test-infra/pull/1230 in test-infra. Tests suggest that PR successfully fixes the issue @jithunnair-amd mentioned. I'll monitor the nightlies tomorrow to ensure they've been published correctly.

**Pull request merged**
