### PR TITLE
make resnext50_32x4d scriptable

### PR DESCRIPTION
**Pull request by eellison**
Not much here in the way of changes, have to add `downsample` to constants.

### CODE REVIEW

**Comment by fmassa** [comment]
@peterjc123 do you know what's happening with the windows CI? It looks like the machine got full?

**Comment by peterjc123** [comment]
@fmassa I have the same idea with @ezyang in https://github.com/pytorch/vision/pull/1298#issuecomment-528378497. Conda-build is a black box and I don't actually know what it is doing here.

**Comment by peterjc123** [comment]
I've sent an issue at conda-build. https://github.com/conda/conda-build/issues/3736 Let's see what they say.

**Comment by peterjc123** [comment]
They confirmed that this is a bug and provided some workground. I'll try to fix that.

**Comment by fmassa** [comment]
@peterjc123 awesome, thanks a lot for the work!

We might need then to change the way we do our testings to not rely on `conda build`

**Pull request merged**
