### PR TITLE
Image enconding and deconding fixes

### PR DESCRIPTION
**Pull request by cyyever**

### CODE REVIEW

**Comment by fmassa** [comment]
Thanks a lot for the PR!

This in principle looks good to me, but I would love if @andfoy could have a closer look.

Also, could you add a test?

**Comment by andfoy** [comment]
In principle, the changes do not modify any of the current behaviour, as they only provide a refactor of terms for clarity. I'll take a look if this fixes the libpng bug. But I agree with the changes

**Comment by cyyever** [comment]
> 
> 
> Thanks a lot for the PR!
> 
> This in principle looks good to me, but I would love if @andfoy could have a closer look.
> 
> Also, could you add a test?

To test image decoding errors, we'd better add fuzzing tests.

**Comment by fmassa** [comment]
@cyyever can you clarify what are your thoughts about the fuzzy testing that you are describing?

Also, can you clarify what this PR fixes?

**Comment by andfoy** [comment]
This PR does not fix #3613:

```
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
>>> image = torchvision.io.read_image("283xnnabju4z.png")
>>> image = torchvision.io.read_image("283xnnabju4z.png")
free(): invalid size
Aborted (core dumped)

```

**Pull request closed without merging**
