### PR TITLE
Add typing Annotations to detection/utils

### PR DESCRIPTION
**Pull request by oke-aditya**
Let's begin #4582

@khushi-411 do you want to take this up? I think you can push to this branch on my fork.
You can clone my forked repo and push changes. They should reflect here.

cc @datumbox

### CODE REVIEW

**Comment by khushi-411** [comment]
Definitely @oke-aditya, I'd love to start up with this PR! The explanations you provided are really helpful. 
I'll ping you once it is complete or if I have some doubts.

**Comment by oke-aditya** [comment]
Apart from above comment everything looks good.

cc @pmeier @NicolasHug

**Comment by oke-aditya** [comment]
Mypy was happy locally Hopefully CI will be all green.

**Comment by pmeier** [comment]
> I'm amazed that people in 3 different time zones synced so fast.

Well for Vasilis and me the time is at least somewhat reasonable whereas for you folks is the middle of the night :stuck_out_tongue:

**Pull request merged**
