### PR TITLE
ROI Pooling Layer

### PR DESCRIPTION
**Pull request by varunagrawal**
Code for ROI Pooling layer.
(#477)

### CODE REVIEW

**Comment by fmassa** [comment]
Hi @varunagrawal ,

Thanks a lot for the PR!
Could you first send the PR to the `layers` branch? I'd rather not merge this into master yet, as it will add a few dependencies that I'd rather double check throughly.

**Comment by varunagrawal** [comment]
@fmassa I took out the NMS and ROI Align layers in order to minimize the dependencies on this PR and tackle each thing separately. I don't know if this branch would merge with your `layers` branch. 
Any recommendations on what should I do?

**Comment by fmassa** [comment]
When you create a PR, you can select to which branch you want it to send the PR to, see https://help.github.com/articles/creating-a-pull-request/ for some more information.

**Comment by fmassa** [comment]
Just saw your other PR. I think that's the way to go, I'd look into updating the layers branch.
Also, one more thing, what version of PyTorch did you use to compile?
With PyTorch pulled from master yesterday, I'm facing issues such as
```
/private/home/fmassa/.conda/envs/detectron/lib/python3.6/site-packages/torch/lib/include/THC/THCNumerics.cuh(163): error: more than one operator "<" matches these operands:
            built-in operator "arithmetic < arithmetic"
            function "operator<(const __half &, const __half &)"
            operand types are: at::Half < at::Half

/private/home/fmassa/.conda/envs/detectron/lib/python3.6/site-packages/torch/lib/include/THC/THCNumerics.cuh(167): error: more than one operator "<=" matches these operands:
            built-in operator "arithmetic <= arithmetic"
            function "operator<=(const __half &, const __half &)"
            operand types are: at::Half <= at::Half

/private/home/fmassa/.conda/envs/detectron/lib/python3.6/site-packages/torch/lib/include/THC/THCNumerics.cuh(171): error: more than one operator ">" matches these operands:
            built-in operator "arithmetic > arithmetic"
            function "operator>(const __half &, const __half &)"
            operand types are: at::Half > at::Half

/private/home/fmassa/.conda/envs/detectron/lib/python3.6/site-packages/torch/lib/include/THC/THCNumerics.cuh(175): error: more than one operator ">=" matches these operands:
            built-in operator "arithmetic >= arithmetic"
            function "operator>=(const __half &, const __half &)"
            operand types are: at::Half >= at::Half
```

**Comment by varunagrawal** [comment]
@fmassa so do you want me to just base off the `layers` branch (without the updates from `master`) and update ROI pooling accordingly? Just want to make sure I understand your last comment correctly.

Also, regarding that compilation error, it is a regression introduced by pytorch/pytorch#10301.  Syed should have a fix in by next week.

**Comment by fmassa** [comment]
Oh yes, I had seen the diff but I didn't check the discussion in the PR.

I think it's easier to base the diff off from the `layers` branch, and then I separately rebase `layers` on top of `master` in a follow-up commit. what do you think?

**Comment by varunagrawal** [comment]
That should work. I'll force-update the PR to align with the `layers` branch.

**Comment by varunagrawal** [comment]
@fmassa it is done.

**Pull request closed without merging**
