### PR TITLE
remove int interpolation from elastic

### PR DESCRIPTION
**Pull request by pmeier**
This was not included in #7176, since it seems we forgot to put a concrete removal date or better yet an actual deprecation warning in there. So we did warn, but not compliant with our BC policy. Question now is, do we want to move forward with the removal regardless of the point above or do we formally deprecate it now and remove in 0.17?

I lean towards 1., since it is unlikely someone using only `ElasticTransform` and thus has seen the concrete deprecation warnings of all other transforms and in turn most likely will also have fixed it here. However, there is no guarantee and so I'm also fine with the other option. In that case let's close this PR and open another one.

cc @vfdev-5

### CODE REVIEW

**Comment by NicolasHug** [comment]
Thanks Philip, I'm fine removing it.

**Review by NicolasHug — APPROVED** [review]
LGTM when green, thank you

**Comment by pmeier** [comment]
Blocked by #7205.

**Comment by pmeier** [comment]
Superseded by #7241.

**Pull request closed without merging**
