### PR TITLE
add dummy workflow to test GitHub Actions CI

### PR DESCRIPTION
**Pull request by pmeier**
@fmassa please merge this to test your suggestion from https://github.com/pytorch/vision/pull/2675#issuecomment-695987935.

### CODE REVIEW

**Review by fmassa — APPROVED** [review]
Thanks, let's see if we get one issue opened in the next 30 min

**Comment by vfdev-5** [comment]
I think this can be easily experimented in a fresh repository :) For example, I do such things here : https://github.com/vfdev-5/github-actions-playground

**Comment by pmeier** [comment]
@fmassa It will not open an issue. It just spins up and tests everything else :wink:

**Comment by fmassa** [comment]
The GitHub Actions work on this dummy action, reverting this now.

**Pull request merged**
