### PR TITLE
Redirect page

### PR DESCRIPTION
**Pull request by brianjo**
Added a new gh-pages branch to include a redirect to https://pytorch.org/     docs/stable/torchvision/index.html

### CODE REVIEW

**Comment by JoelMarcey** [comment]
@brianjo - do you expect the build failures?

**Comment by brianjo** [comment]
> @brianjo - do you expect the build failures?

It's just a stand alone branch so it shouldn't build. @fmassa do you have thoughts on this? I'm not sure how your full workflow is setup.

**Comment by fmassa** [comment]
We by default run CI on all PRs sent to all branches. Given that this PR removed the CI configuration, CI now started failing because it can't find the `.circleci/config.yaml`, but that is expected I believe.

Let's not worry about CI on this PR

**Comment by brianjo** [comment]
> We by default run CI on all PRs sent to all branches. Given that this PR removed the CI configuration, CI now started failing because it can't find the `.circleci/config.yaml`, but that is expected I believe.
> 
> Let's not worry about CI on this PR

Great. Can you merge this then? That should cause the redirect automatically from pytorch.org/vision to the documentation set. 

You can see this working from my repo here. https://brianjo.github.io/vision/

Thanks!

**Comment by brianjo** [comment]
https://pytorch.org/vision is working now. 
Thanks all for your help on this.

**Comment by fmassa** [comment]
Thank Brian!

**Pull request merged**
