### PR TITLE
test_prototype_datasets_builtin: Properly close all streams

### PR DESCRIPTION
**Pull request by SvenDS9**
In https://github.com/pytorch/data/pull/1016 I noticed that if a test fails subsequent tests will also fail as not all streams are being closed correctly due to:

```
for stream in StreamWrapper.session_streams.keys():
RuntimeError: dictionary changed size during iteration
```
This addresses this issue so that only the "necessary" tests fail.
In theory we should also be able to remove l.135-136 but to be safe I have kept them.
```python
if StreamWrapper.session_streams:
    raise pytest.UsageError(make_msg_and_close("A previous test did not close the following streams:"))
```

### CODE REVIEW

**Comment by pmeier** [comment]
Thanks @SvenDS9 for the report and fix. The error looks quite weird to me TBH. We are never touching `StreamWrapper.session_streams.keys()` so why would this happen? Could it be that `stream.close()` removes it on the fly and thus causing this? If so, wouldn't it be sufficient to just copy the iterator, e.g. `for stream in list(StreamWrapper.session_streams.keys())`?

**Comment by SvenDS9** [comment]
> Thanks @SvenDS9 for the report and fix. The error looks quite weird to me TBH. We are never touching `StreamWrapper.session_streams.keys()` so why would this happen? Could it be that `stream.close()` removes it on the fly and thus causing this? If so, wouldn't it be sufficient to just copy the iterator, e.g. `for stream in list(StreamWrapper.session_streams.keys())`?

I think that is what happens yes. And you are right, that is sufficient. Will change it now.

**Review by pmeier — APPROVED** [review]
LGTM, thanks @SvenDS9! This will be available in tomorrows nightly release. Could you push an update to pytorch/data#1016 after roughly 12:00 UTC+0 tomorrow to see if this actually fixed your issue?

**Comment by SvenDS9** [comment]
I have already run the test with my changes to both the test and the datapipe. It unfortunately does not. I would be very grateful if you could take a look why the stream isn't being closed correctly. as you probably have a much deeper understanding what actually happens in the tests... i have linked the relelvant parts in the PR. Please don't feel obligated to do so as I have already wasted enough time on this :D

**Comment by pmeier** [comment]
> I have already run the test with my changes to both the test and the datapipe. It unfortunately does not.

Sorry, I was not clear enough above. Could you make sure that the issue of failing unrelated tests that was addressed by this PR is fixed? Meaning, after this PR you should only see relevant test failures on the TorchData PR, right?

> I would be very grateful if you could take a look why the stream isn't being closed correctly. as you probably have a much deeper understanding what actually happens in the tests

I'll look into it if I find some time next week. No promises however.

**Pull request merged**
