### PR TITLE
add a signature consistency tests for v1 vs. v2 dispatchers

### PR DESCRIPTION
**Pull request by pmeier**
Follow-up to https://github.com/pytorch/vision/pull/6904#issuecomment-1303189194. There are some failures. Will post them here as soon as CI surfaced them so we can decide whether they are valid or test needs an update.

cc @vfdev-5 @datumbox @bjuncek

### CODE REVIEW

**Comment by datumbox** [comment]
Everything looks fine to me except of the following:
```
rotate: center
affine: translate, center
```

I'm not sure whether the type conversion is expected. If it is, should we consider it a bug fix and resolve on V1 as well?

Concerning the other things that are failing that have Unions, perhaps it's worth letting supersets pass. For example if V1=int and V2=Union[int, List[int]], this should be OK. But if V1=List[int] and V2=Union[int, List[float]] this should be failing.

**Comment by pmeier** [comment]
Up for discussion are the following annotations:

v1:

- https://github.com/pytorch/vision/blob/e3f7baaf2ee4ef51ee1829636ec34566349eac60/torchvision/transforms/functional.py#L1057
- https://github.com/pytorch/vision/blob/e3f7baaf2ee4ef51ee1829636ec34566349eac60/torchvision/transforms/functional.py#L1134
- https://github.com/pytorch/vision/blob/e3f7baaf2ee4ef51ee1829636ec34566349eac60/torchvision/transforms/functional.py#L1129

v2:

- https://github.com/pytorch/vision/blob/e3f7baaf2ee4ef51ee1829636ec34566349eac60/torchvision/prototype/transforms/functional/_geometry.py#L656
- https://github.com/pytorch/vision/blob/e3f7baaf2ee4ef51ee1829636ec34566349eac60/torchvision/prototype/transforms/functional/_geometry.py#L488
- https://github.com/pytorch/vision/blob/e3f7baaf2ee4ef51ee1829636ec34566349eac60/torchvision/prototype/transforms/functional/_geometry.py#L483

Given that we use them as `float`'s internally anyway 

https://github.com/pytorch/vision/blob/e3f7baaf2ee4ef51ee1829636ec34566349eac60/torchvision/prototype/transforms/functional/_geometry.py#L270

I think we should be fine. No strong opinion though.

---

Apart from that, the test actually found a bug. For stable `F.rotate` we have 

https://github.com/pytorch/vision/blob/e3f7baaf2ee4ef51ee1829636ec34566349eac60/torchvision/transforms/functional.py#L1057-L1058

and in prototype we have

https://github.com/pytorch/vision/blob/e3f7baaf2ee4ef51ee1829636ec34566349eac60/torchvision/prototype/transforms/functional/_geometry.py#L655-L656

I've fixed that in b4218c0f4d15d79a5eaf1f4e7183d53c1d49a875.

**Comment by datumbox** [comment]
@pmeier Thanks for confirming.

I checked the code one V1 and it seems we convert both `center` and `translate` into floats anyway later in the implementation. So implementation-wise we shouldn't have issues. My only question is whether passing floats in V1 is permitted when JIT-scripting. Have you tried if you get an error? If you don't, I think we can either fix on V1 directly or exclude for the check of V2 the specific 2 params. An alternative could also be to Union[List[int], List[float]] both n V1 and V2 but I'm not sure if JIT likes that. Thoughts?

**Comment by pmeier** [comment]
JIT seems to implicitly convert `int` to `float` if we use the latter as annotation:

```py
from typing import List

import torch


@torch.jit.script
def foo(bar: List[float]) -> List[float]:
    return bar


print(foo([1, 2, 3]))
print(foo([1.0, 2.0, 3.0]))
```

```
[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]
```

Seems we are good.

**Comment by datumbox** [comment]
@pmeier sounds good. Up to you which mitigation you will choose.

**Pull request merged**
