### PR TITLE
Test against torch RC instead of nightly. Bump build version

### PR DESCRIPTION
**Pull request by atalman**
Test against torch RC instead of nightly. Bump build version

### CODE REVIEW

**Comment by YosuaMichael** [comment]
@atalman seems like the build failed because it can't fine pytorch 1.13.0:
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'pytorch==1.13.0'}
```

**Comment by atalman** [comment]
> @atalman seems like the build failed because it can't fine pytorch 1.13.0:
> 
> ```
> conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'pytorch==1.13.0'}
> ```

Yes we had an issue yesterday with missing binaries. This should be fixed now

**Comment by YosuaMichael** [comment]
Have discussed with @atalman offline, seems like we still have problem with naming on the pytorch core binary.

**Comment by YosuaMichael** [comment]
This is related fix on pytorch core: https://github.com/pytorch/pytorch/pull/86460

**Review by YosuaMichael — APPROVED** [review]
LGTM and all test passed now, thanks @atalman !

**Pull request merged**
