### PR TITLE
Update usages of torch.library APIs

### PR DESCRIPTION
**Pull request by zou3519**
We deprecated impl_abstract. This PR replaces it with the new API (register_fake). register_fake also (sometimes) requires a `set_python_module` in C++, so I add that as well.

Test Plan:
- existing tests

### CODE REVIEW

**Review by NicolasHug — APPROVED** [review]
Thank you @zou3519 !

**Comment by zbt78** [comment]
hello，when i install vision by source code，i got this error：
```bash
/home/gai_test/wuyang/vision/torchvision/csrc/ops/nms.cpp:22:5: error: ‘class torch::Library’ has no member named ‘set_python_module’
   22 |   m.set_python_module("torchvision._meta_registrations");
      |     ^~~~~~~~~~~~~~~~~
error: command '/usr/bin/gcc' failed with exit code 1
```
is there any solutions?
thank you!

**Comment by jielyu** [comment]
> hello，when i install vision by source code，i got this error：
> 
> ```shell
> /home/gai_test/wuyang/vision/torchvision/csrc/ops/nms.cpp:22:5: error: ‘class torch::Library’ has no member named ‘set_python_module’
>    22 |   m.set_python_module("torchvision._meta_registrations");
>       |     ^~~~~~~~~~~~~~~~~
> error: command '/usr/bin/gcc' failed with exit code 1
> ```
> 
> is there any solutions? thank you!

It seems like the versions are not matching. You can check the corresponding versions of Torch and TorchVision on the official website, and then switch TorchVision’s source code to the appropriate version.
[INSTALLING PREVIOUS VERSIONS OF PYTORCH](https://pytorch.org/get-started/previous-versions/)

**Comment by humphreyde** [comment]
> > hello，when i install vision by source code，i got this error：
> > ```shell
> > /home/gai_test/wuyang/vision/torchvision/csrc/ops/nms.cpp:22:5: error: ‘class torch::Library’ has no member named ‘set_python_module’
> >    22 |   m.set_python_module("torchvision._meta_registrations");
> >       |     ^~~~~~~~~~~~~~~~~
> > error: command '/usr/bin/gcc' failed with exit code 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is there any solutions? thank you!
> 
> It seems like the versions are not matching. You can check the corresponding versions of Torch and TorchVision on the official website, and then switch TorchVision’s source code to the appropriate version. [INSTALLING PREVIOUS VERSIONS OF PYTORCH](https://pytorch.org/get-started/previous-versions/)

I got the same problem, while I'm using torch==2.4.0 torchvision==0.19.0 on jetson(arch). They are matched.But I got error:
`/vision-0.19.0/torchvision/csrc/ops/nms.cpp:22:5: error: ‘class torch::Library’ has no member named ‘set_python_module’`

**Pull request merged**
