### PR TITLE
Replace byte tensor

### PR DESCRIPTION
**Pull request by vipyoung**
replaced the deprecated byteTensor call with from_numpy. 
Also slightly refactored the code.

### CODE REVIEW

**Comment by vfdev-5** [comment]
@datumbox thanks for pinging. 
There is a list of issues talking about removing `torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))` : 
- https://github.com/pytorch/vision/issues/3666
- https://github.com/pytorch/vision/issues/2989

@fmassa even self-assigned himself to fix #3666 , I let him review this PR as well.

**Review by fmassa — COMMENTED** [review]
The code looks great, thanks a lot @vipyoung !

There are lint failures in https://app.circleci.com/pipelines/github/pytorch/vision/8023/workflows/9179c017-9365-410e-8959-e77c94a37c26/jobs/571724 , can you look into fixing those so that we can merge the PR?

Additionally, one thing we might want to consider as well is that we now get the following warning for the `uint8` use-case (which we didn't have before)

```
  /root/project/torchvision/transforms/functional.py:129: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1620716760038/work/torch/csrc/utils/tensor_numpy.cpp:180.)
    np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=False)

```
see https://app.circleci.com/pipelines/github/pytorch/vision/8023/workflows/5620d2f7-08be-493d-9878-fcb5db93539f/jobs/571690 for one example.

We might want think if we want to perform the copy here (which will be less efficient), or suppress this warning somehow.

Thoughts @vfdev-5 ?

**Review by vipyoung — COMMENTED** [review]
I've fixed the lint issues and enabled copy of the array here as a quick fix to the warning.

**Review by fmassa — APPROVED** [review]
Thanks a lot!

**Pull request merged**
