### PR TITLE
Fix dataset url

### PR DESCRIPTION
**Pull request by lanpa**
There is "HTTP Error 500" for http. change url to https fixes this.
(link in the official cifar page also says `https://`)

### CODE REVIEW

**Comment by soumith** [comment]
The http works fine for me, i just checked...

**Comment by apaszke** [comment]
It might work, but it's better to use https if we can

**Comment by soumith** [comment]
no, https is giving subtle problems based on user machines and python version. lets stick to http please (we verify hash anyways)

**Comment by apaszke** [comment]
It's `md5`, so it's not really secure.

**Comment by soumith** [comment]
@lanpa is it still happening for you? or is the 500-internal-error an intermittent message you get sometimes?
@apaszke let's switch to a more secure hash than md5 then.

**Comment by lanpa** [comment]
@soumith You are right, that error happens occasionally. How about

    try 
        download_url(http_url, ...) 
    except 
        download_url(https_url, ...)

 to handle them all?

**Comment by soumith** [comment]
yes i think that's a good idea.
Actually the reverse:

try:
   https_url
except:
   http_url

**Comment by soumith** [comment]
thanks @lanpa !

**Comment by alykhantejani** [comment]
@soumith @apaszke should we update this download function in the same way that we did for pytorch's load_url, I think that'd be cleaner and more consistent?

**Comment by lanpa** [comment]
@alykhantejani Whay if we should also move `model_zoo.py` from torch to torchvision? Because it does not referenced by functions in torch, the only invokers lie in `torchvision/model/*.py`.

**Comment by fmassa** [comment]
@lanpa originally `model_zoo.py` was in torchvision, but we decided to move it to pytorch because it can be used elsewhere (like torchtext for example). I think it's better to leave it there.

**Pull request merged**
