### PR TITLE
Remove unneeded packaging files

### PR DESCRIPTION
**Pull request by NicolasHug**
Closes https://github.com/pytorch/vision/issues/3617

This PR removes some unneeded packaging files

Original post says we can remove all scripts in `packaging/conda/` but they all seem to be scripts. Should we remove the directory altogether?

### CODE REVIEW

**Comment by fmassa** [comment]
@peterjc123 could you have a look to double-check that this was what you had in mind?

**Comment by peterjc123** [comment]
> Original post says we can remove all scripts in `packaging/conda/` but they all seem to be scripts. Should we remove the directory altogether?

Sure, please do that.

**Comment by peterjc123** [comment]
> @peterjc123 could you have a look to double-check that this was what you had in mind?

Yeah.

**Review by fmassa — APPROVED** [review]
Thanks!

**Pull request merged**
