### PR TITLE
Moving tensors to the right device

### PR DESCRIPTION
**Pull request by datumbox**
The latest PyTorch core seems to add an additional limitation over indexing tensors when the index is not on the same device. See https://github.com/pytorch/vision/pull/3869#issuecomment-845825949

This PR resolves this and fixes the broken master.

### CODE REVIEW

**Review by NicolasHug — APPROVED** [review]
lgtm when green, thanks!

This should also solve the flakyness of `test_pad` internally which IIRC was failing with the same error

**Comment by datumbox** [comment]
It seems we get memory errors:
```
E           RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 7.44 GiB total capacity; 6.54 GiB already allocated; 3.06 MiB free; 6.61 GiB reserved in total by PyTorch)

env/lib/python3.8/site-packages/torch/nn/modules/module.py:1051: RuntimeError
```

**Comment by datumbox** [comment]
So after updating to the latest PyTorch core, we get memory issues. Currently it's unclear whether PyTorch core has a regression that increases the memory footprint or our test was passing marginally the memory limits earlier and now that we bring on GPU a tiny amount of data (indexes) they fail. I noticed also that a non-trivial amount of memory is not allocated to PyTorch which is weird. The OS should not be reserving 0.9GB given it does not run a GUI.

At any case, I've increased the instance type on linux to medium so that we have the same GPU memory as on Windows. This will fix the failing master and unblock follow up PRs. We should investigate this issue further later.

**Comment by fmassa** [comment]
Thanks for looking into this!

My guess is that this is potentially an (unwanted?) regression in PyTorch, due maybe to https://github.com/pytorch/pytorch/pull/57839

@ngimel is this expected that now that `index_put` doesn't support indices on the CPU while the tensor is on the GPU?

**Comment by ngimel** [comment]
#57839 should not have any effect if deterministic mode is not on (and if deterministic mode is on, it would allow cases that errored out previously to run). 
`index_put` still supports indices on the cpu:
```
In [5]: import torch
   ...: a=torch.randn(4,4, device="cuda")
   ...: indices = torch.randint(4, (4,), dtype=torch.long)
   ...: a[indices]=100
   ...: print(a)
   ...: print(indices)
tensor([[ 1.0000e+02,  1.0000e+02,  1.0000e+02,  1.0000e+02],
        [-5.1810e-01, -1.4072e-02, -5.6064e-01,  5.0140e-01],
        [ 1.0000e+02,  1.0000e+02,  1.0000e+02,  1.0000e+02],
        [-8.2297e-03, -3.6658e-01,  7.2363e-02, -1.2188e+00]], device='cuda:0')
```

**Pull request merged**
