### PR TITLE
Add CircleCI (v2)

### PR DESCRIPTION
**Pull request by fmassa**
Re-do of https://github.com/pytorch/vision/pull/1295, but re-using most of the packaging code that we already have. Takes into account the comments of @ezyang from https://github.com/pytorch/vision/pull/1295

The final code is much simpler as well it seems.

Tests currently are forced to run on the CPU because we currently do not have PyTorch nightly conda packages for Linux with CUDA

I still need to improve the job selection to run in master / CI

### CODE REVIEW

**Comment by fmassa** [comment]
@soumith @ezyang  I have the impression that I can entirely remove https://github.com/pytorch/vision/tree/master/packaging/conda , plus the build instructions in https://github.com/pytorch/vision/blob/master/packaging/README.md seem to be deprecated.

@ezyang does this sounds about right?

**Comment by ezyang** [comment]
> @soumith @ezyang I have the impression that I can entirely remove https://github.com/pytorch/vision/tree/master/packaging/conda , plus the build instructions in https://github.com/pytorch/vision/blob/master/packaging/README.md seem to be deprecated.

It's OK for Linux and OS X; but it was previously used by Windows, unless peterjc123 has fixed the Windows pipeline.

**Comment by ezyang** [comment]
CUDA tests via conda build is a useful thing to test for. However, I'm not sure I would have them be the only testing we do (since builds always happening inside `conda build` is unrealistic; it's also a pain to debug failed `conda build` because conda tries hard to be hermetic). This is probably fine for now, but something to keep in mind if you start having pressures to do more testing in more unusual situations.

**Comment by ezyang** [comment]
@peterjc123 This has windows bits now. (My audio PR isn't that useful, I never got it to actually work haha)

**Comment by fmassa** [comment]
Note that the Windows bits are not doing anything useful yet... but I'd love to be able to run some (at least CPU) tests on Windows, but I have no Windows experience

**Comment by peterjc123** [comment]
@fmassa The Windows CPU build is working, but you'll have to skip some tests.

**Comment by fmassa** [comment]
@peterjc123 awesome, thanks a lot for all the help!

Let me know once you are done with the Windows part, I'll move your changes to `config.yml.in` as well, which need to be regenerated via `python regenerate.py` to update `config.yml`.

**Comment by fmassa** [comment]
Also, I'll disable the tests for Windows that are failing, don't worry about it

**Comment by fmassa** [comment]
@peterjc123 I have a commit ready to be pushed that disables the failing tests for Windows for now. Let me know when I can push it, to avoid potential conflicts

**Comment by peterjc123** [comment]
@fmassa Sure, feel free to push that. Current build failure is caused by something else. (Conda base package not uploaded but cpu-only packages uploaded)

**Comment by peterjc123** [comment]
Looks like the CUDA nightlies for Linux are not generated. When I run the command added in https://github.com/pytorch/vision/pull/1298/commits/cb7a33d45d0449b4b0b3b20f8db5c3c3bf2f16ea, it returned an empty result. @ezyang

**Comment by fmassa** [comment]
@peterjc123 yes, that's true, and it is the cause of the failing builds that we currently have.

**Comment by peterjc123** [comment]
@fmassa Now it won't fail when only part of new packages are uploaded because I introduced fine-grained search for PyTorch version.

**Pull request merged**
