### PR TITLE
Fix wheel relocation issues

### PR DESCRIPTION
**Pull request by andfoy**

### CODE REVIEW

**Comment by andfoy** [comment]
I have bad news here, we need to compile FFmpeg from scratch on the manylinux image in order to have manylinux wheel compatibility

**Comment by fmassa** [comment]
Ok. I propose that we first fix the issues with libjpeg / libpng, merge this, and then fix ffmpeg in a follow-up PR

**Comment by andfoy** [comment]
We need to compile libPNG ourselves as well

**Comment by andfoy** [comment]
Regarding the Windows testing errors, it seems that we're picking the global conda ffmpeg binaries instead of the wheel ones

imagen

**Comment by andfoy** [comment]
My solution on this case would be the following:

1. Compile the pyd for video_reader
2. Copy the FFmpeg libraries and rename them
3. Update the pyd to point to the new binaries
4. Include those as part of both the conda recipe and the wheels

**Comment by andfoy** [comment]
I tried to rename `avcodec-58.dll` to `avcodec-asdasd-50.dll` on `video_reader.pyd`, however, it seems that PyAV dlls are picking `avcodec-58.dll` from conda, that's because `C:\Users\circleci\project\env\Library\bin` is first on PATH, and PyAV wheels are not renaming the packaged DLLs inside the wheels. That means that PyAV wheels are the culprit here, since those should be loading their own binaries to prevent clashes

**Comment by vfdev-5** [comment]
PyAV is not a hard dependency, right ? For windows, we can put "experimentatl" mention in the docs, put try/catch while it is imported and include a detailed instruction on what to do instead.

**Comment by fmassa** [comment]
My take on this: let's separate this into two PRs: one with only libjpeg / libpng, and one with FFmpeg. This way we can start merging the libjpeg / libpng bits and testing it, while we iterate on FFmpeg.

**Comment by fmassa** [comment]
Test failures are unrelated, merging this to unblock. We should still fix FFmpeg on Windows and Linux

**Comment by vfdev-5** [comment]
Manual tests:
- [x] Colab linux+pip, io.image works fine : https://colab.research.google.com/drive/1DQbZfdA9N1IGuuRVS37hvy9BKtLboxxI
- [x] MacOSX 10.13 pip binaries, io.image works fine
- [x] MacOSX 10.13 conda binaries, io.image works fine

**Comment by fmassa** [comment]
Awesome, thanks a lot for checking this @vfdev-5 !

**Pull request merged**
