### PR TITLE
disable download test for Places365 and SBU

### PR DESCRIPTION
**Pull request by pmeier**
Adresses #6268. The bot is spamming this once per day. Let's revisit this before the next release to see if we can reinstate the test or disable downloads for Places365 entirely.

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
Another failing download is flaky or not tested ? Otherwise, OK for me

**Comment by pmeier** [comment]
Oh yeah, SBU is also failing. I'll have a look.

**Comment by NicolasHug** [comment]
Thanks @pmeier 

How will we remember to revisit this before the next release?

**Comment by pmeier** [comment]
> How will we remember to revisit this before the next release?

Given that we are not using GH milestone feature or any other project management tool that I'm aware of, I'll set a notification for myself. If you have a better idea I'm all ears.

**Comment by pmeier** [comment]
> Oh yeah, SBU is also failing.

See #6390. Do you want me to disable this in this PR as well or should I send another one?

**Comment by pmeier** [comment]
> Is it possible to turn the test into an xfail one so that if it gets fixed we know it?

Done.

**Review by datumbox — APPROVED** [review]
LGTM, thanks!

**Review by NicolasHug — APPROVED** [review]
Thanks @pmeier, LGTM

**Pull request merged**
