### PR TITLE
[NOMRG] Investigate kp regression

### PR DESCRIPTION
**Pull request by datumbox**
Do NOT merge. Investigation PR for #3829, we turn off most of the CI tests to read results faster/easier.

The non-scripted prediction time takes rather long, >25 sec. The scripted one seems to take 4 times more than that.

### Reproducing the slowdown

Does 2 predicts in normal mode + JIT compiling + 1 predict in JIT mode.

[Tested](https://app.circleci.com/pipelines/github/pytorch/vision/8154/workflows/72716dad-da2d-4a1e-934b-dccc71a46200/jobs/583067) with https://github.com/pytorch/vision/pull/3847/commits/adc202d575b86d6a99727189d9407f1252469e90

```
============================= slowest 20 durations =============================
144.70s call     test/test_models.py::test_detection_model[dev0-keypointrcnn_resnet50_fpn]
65.70s call     test/test_models.py::test_detection_model[dev0-maskrcnn_resnet50_fpn]
49.40s call     test/test_models.py::test_detection_model[dev0-fasterrcnn_resnet50_fpn]
1.36s call     test/test_models.py::test_detection_model_validation[keypointrcnn_resnet50_fpn]
0.90s call     test/test_models.py::test_detection_model_validation[fasterrcnn_resnet50_fpn]
0.89s call     test/test_models.py::test_detection_model_validation[maskrcnn_resnet50_fpn]
```

### Skipping JIT execution

Does 1 predict in normal mode, no JIT execution.

[Tested](https://app.circleci.com/pipelines/github/pytorch/vision/8155/workflows/5a2d7e01-917e-4741-b8ec-871ce95c93f4/jobs/583071) with https://github.com/pytorch/vision/pull/3847/commits/3ca60faab490a6f6189cfe51b23ade820914898a

```
============================= slowest 20 durations =============================
28.79s call     test/test_models.py::test_detection_model[dev0-keypointrcnn_resnet50_fpn]
12.62s call     test/test_models.py::test_detection_model[dev0-maskrcnn_resnet50_fpn]
9.38s call     test/test_models.py::test_detection_model[dev0-fasterrcnn_resnet50_fpn]
1.35s call     test/test_models.py::test_detection_model_validation[keypointrcnn_resnet50_fpn]
0.96s call     test/test_models.py::test_detection_model_validation[maskrcnn_resnet50_fpn]
0.85s call     test/test_models.py::test_detection_model_validation[fasterrcnn_resnet50_fpn]
```

### With JIT compiling but no JIT executions

Does 1 predict in normal mode + JIT compiling.

[Tested](https://app.circleci.com/pipelines/github/pytorch/vision/8156/workflows/1a7b8db6-b80b-4317-8ec5-4c97fe1fc743/jobs/583074) with https://github.com/pytorch/vision/pull/3847/commits/64f5ff51aba90ed3213125eabdedf7fb12a57a1a

```
============================= slowest 20 durations =============================
29.99s call     test/test_models.py::test_detection_model[dev0-keypointrcnn_resnet50_fpn]
13.95s call     test/test_models.py::test_detection_model[dev0-maskrcnn_resnet50_fpn]
12.14s call     test/test_models.py::test_detection_model[dev0-fasterrcnn_resnet50_fpn]
1.34s call     test/test_models.py::test_detection_model_validation[keypointrcnn_resnet50_fpn]
1.00s call     test/test_models.py::test_detection_model_validation[maskrcnn_resnet50_fpn]
0.90s call     test/test_models.py::test_detection_model_validation[fasterrcnn_resnet50_fpn]
```

### CODE REVIEW

**Comment by fmassa** [comment]
28s for a single forward pass seems too much. And this slowdown only appears in keypoint rcnn? There might be a change of kernel (conv2d? something else?) that makes the runtime much slower.

**Comment by datumbox** [comment]
@fmassa Haven't finished yet the investigation but so far I can't reproduce these slow speeds on my mac.

My first thoughts are that this is not a JIT specific issue but a general slowdown of the model. From memory the other *RCNN models are not affected but needs to be confirmed.

**Comment by datumbox** [comment]
Here are my findings:

### 1. There is no regression; the keypoint unit-test was always slow

See my old CI speed optimization PR #3189. After reducing the execution time of the worst offenders, the keypoint was the [next slowest test](https://app.circleci.com/pipelines/github/pytorch/vision/5598/workflows/ad7b6782-4dfb-4806-bc95-c4864c312533/jobs/353663):

```
============================= slowest 20 durations =============================
133.62s call     test/test_models.py::ModelTester::test_keypointrcnn_resnet50_fpn_cpu
79.42s call     test/test_datasets.py::Tester::test_ucf101
69.63s call     test/test_ops.py::DeformConvTester::test_backward_cpu_non_contiguous
60.43s call     test/test_models.py::ModelTester::test_maskrcnn_resnet50_fpn_cpu
53.50s call     test/test_ops.py::DeformConvTester::test_backward_cpu_contiguous
43.58s call     test/test_models.py::ModelTester::test_fasterrcnn_resnet50_fpn_cpu
43.20s call     test/test_models.py::ModelTester::test_retinanet_resnet50_fpn_cpu
39.31s call     test/test_models.py::ModelTester::test_deeplabv3_resnet101_cpu
```

So it is slow and it does need improvement but it did not get slower.

### 2. There is no issue with the CI; it's just much slower than a real macOS

Though originally I thought I could not reproduce the slowness on a real macOS laptop, I noticed that the ratios between the test times are the same. In other words the maskrcnn is 25% slower than fasterrcnn and keypoint takes more than 2 times the time of maskrcnn both on the CI and on the laptop:
image

So I think that this is just a case of a test running too slowly on the medium image that we use on CircleCI.

### 3. JIT predictions are quite slow

All the measurements show that inference with a scripted model takes 4 times the time of an unscripted. Unclear why this happens but again not a regression on TorchVision side.

### 4. Most time spent on convolutions

Profiling the test shows that the majority of time is spent on Conv2D. On the table below we see all methods that took more than 1% own time: 
image

So nothing pops up as an unexpected issue on TorchVision side.

---------

### Summary

I will close the PR and the original issue because there is no regression problem. It's worth speeding up the unit-test by reducing the input size, tuning the inference params, checking why JIT is so slow etc on the future but all these are separate issues.

**Comment by fmassa** [comment]
Awesome, thanks for the investigation @datumbox !

About JIT slowness, I think it's due to compilation -- indeed, compilation happens during the first forward of the model, so running the model more times might make it faster afterwards (at least comparable with the non-JIT version)

**Pull request closed without merging**
