### PR TITLE
Added tests for check_md5 and check_integrity

### PR DESCRIPTION
**Pull request by pmeier**
See #871

### CODE REVIEW

**Comment by fmassa** [comment]
@pmeier tests are failing, can you have a look?

**Comment by pmeier** [comment]
The test seem to fail, because they image file I test against is not found. Is there something special about the path for CI? The tests work fine for me locally.

**Comment by fmassa** [comment]
Tests seems to be run from the root folder, not from `test/` https://github.com/pytorch/vision/blob/master/.travis.yml#L53

**Comment by fmassa** [comment]
Best would be to use something like `__file__` maybe?

**Comment by fmassa** [comment]
Thanks!

**Pull request merged**
