### PR TITLE
Fix overshoot issue in F.to_pil_image

### PR DESCRIPTION
**Pull request by Coloquinte**
When converting a tensor to a PIL image, overshoots are not clamped. This means that a value of 1.001 becomes 0 instead of 255. This issue is described here: https://github.com/pytorch/vision/issues/2950#issuecomment-722070283
Additionally, replace the imprecise truncation by a rounding.
Both issues are particularly annoying for downsampling/upsampling code, where such overshoots are common.

### CODE REVIEW

**Review by NicolasHug — COMMENTED** [review]
I think these are reasonable changes, thanks @Coloquinte .

It'd be nice to also have a simple non-regression test in `test/test_transforms.py`, with a reference to this PR as a comment (it's often easier than to follow git blame)

**Comment by NicolasHug** [comment]
Although the failing tests seem related: would you mind looking at these?

**Comment by Coloquinte** [comment]
Thanks! I fixed the transform tests and added mine. I'm letting the CI do the checks, so there may be one more round.

It seems that some tests were failing due to the branch being a fork. I don't know how to workaround these.

**Comment by Coloquinte** [comment]
The following error is still present during the CI run:

> ValueError: Cannot find master in https://github.com/pytorch/vision. If it's a commit from a forked repo, please call hub.load() with forked repo directly.

Is there anything to do on my side to help merge this?

**Comment by fmassa** [comment]
Hi @Coloquinte 

The torchub failure is unrelated, don't worry.

I'll have a closer look at the PR on Monday, but here is my quick thoughts about it:

- ideally, `to_pil_image(to_tensor(data)) == data`, and I'm not yet clear that the `round` satisfies this behavior

I think it might be safer to remove the `.round`, as it will affect the behavior of `to_pil_image`, but I'll let @vfdev-5 chime in as well

**Comment by Coloquinte** [comment]
Hi @fmassa,

Thanks, no hurry. 

I can confirm that `to_pil_image(to_tensor(data)) == data` is preserved - I can add a unit test for this if you like.

In my opinion, round() is necessary because it has the lowest error for  `to_tensor(to_pil_image(data)) - data`, and is robust to a little noise i.e. `to_pil_image(to_tensor(data) - epsilon) == data`. This is important for image reconstruction applications, which otherwise have to second guess this behaviour to reduce the reconstruction error.

**Comment by Coloquinte** [comment]
Hi,
It would be nice to see this merged. Any action I can take?

**Comment by NicolasHug** [comment]
Hi @Coloquinte , thanks for your patience. I took care of porting the tests to our new testing infra (with pytest).

> I can confirm that to_pil_image(to_tensor(data)) == data is preserved - I can add a unit test for this if you like.

I think having such round-trip test would be great, yes! We could even parametrize it over a few  epsilon values and do `o_pil_image(to_tensor(data) - epsilon) == data` as you suggested above.

**Comment by Coloquinte** [comment]
Thanks @NicolasHug ! I pushed such a test on my branch

**Comment by NicolasHug** [comment]
Hi @Coloquinte , I fixed the failing tests that resulted from a problem during the `merge`, but I think the new `test_tensor_to_pil_robust` is failing because it's not properly parametrized. Would you mind taking a look?

**Pull request closed without merging**
