### PR TITLE
Transpose SVHN to HWC on class init

### PR DESCRIPTION
**Pull request by augustoolucas**
SVHN is transposed into HWC when converting it into PIL Image, on the getitem method. This is inconsistent with other datasets, like CIFAR10 and MNIST, where the image is already on the right shape at the moment of the PIL conversion. This inconsistency makes it needed to do two transpositions instead of only one, and can make it troublesome to use this dataset together with others, like the aforementioned ones.

This PR fix this behaviour, transposing the data into HWC on class init.

### CODE REVIEW

**Review by fmassa — COMMENTED** [review]
Hi,

Thanks for the PR!

The change looks good to me, although it could be considered BC-breaking if a user were to access `self.data` directly (which I would hope it's not the case, but given that you are sending this PR then there might be users doing it :-)  )

From this perspective, and given that we don't currently have a good way of checking if this is being used by others, I'd maybe prefer to restrain from merging this PR.

Thoughts?

**Comment by fmassa** [comment]
@NicolasHug yes, I think from now on we might want to start prefixing the attributes of new datasets / etc with an underscore, so that we can have more flexibility there.

**Comment by datumbox** [comment]
What if we pay the debt now, make the `self.data` private and at the same time accept the proposed change of this PR? This will be BC-breaking but it will be a start of cleaning things up. Also to play devil's advocate, why would anyone access `self.data` when the main target of the class is to index them for you and provide extra functionality?

**Comment by augustoolucas** [comment]
Well, don't know if I have much more to add to this discussion but...
Although I think it's a very good idea to start setting these attributes as private for new datasets, this leads to the problem of inconsistency... imo, it would be better if all datasets had a standard way of implementing things. I know that the way that things are implemented under the hood should not be a problem, since we have standard methods to get access to the data. But having datasets which we can access it directly while having others which this isn't possible doesn't sounds good, for me. I suggested this pull request exactly to solve an inconsistency and was not thinking in creating more ones, haha. About setting the attributes as private by now for the existing datasets, well... the BC issue would be even worse... But I really think it should be considered for future versions.

**Comment by NicolasHug** [comment]
Thanks again for the PR @augustoolucas . Unfortunately our hands are tied with the backward compatibility changes here, so I'll close the PR if you don't mind.

However, we're currently working on re-implementing the datasets in a more unified and flexible fashion, so we can be confident that this issue will be fixed in the future!

CC @pmeier : this will probably be something to keep in mind when implementing the equivalent DataPipe class :)

**Pull request closed without merging**
