### PR TITLE
Fix Torchvision iOS nightly build

### PR DESCRIPTION
**Pull request by husthyc**
1. Change the PyTorch binary dependency from libtorch_ios_nightly_build.zip to libtorch_lite_ios_nightly_build.zip
2. Upgrade the testapp from using LibTorch to LibTorch-Lite
3. Fix some build errors for the testapp project

### CODE REVIEW

**Comment by husthyc** [comment]
The CI failure is due to the LibTorch-Lite binary on 11/24 has not been generated yet. Since there is a guarantee that the Torchvision nightly build will happen after the LibTorch-Lite nightly, these two jobs will be successful when the nightly builds are triggered.

**Comment by datumbox** [comment]
@husthyc Is this something that will make our CI appear broken often? If this will be a source of flakiness, we should consider removing the date from the file name and access the latest available nightly. Thoughts?

**Comment by husthyc** [comment]
PR updated:
1. Change the PyTorch binary dependency from libtorch_ios_nightly_build.zip to libtorch_lite_ios_nightly_build.zip
2. Upgrade the testapp from using LibTorch to LibTorch-Lite
3.. Fix some build errors for the testapp project

**Comment by husthyc** [comment]
Close this one because unrelated changes involved. Will create a new one just for VisionTestApp setups.

**Pull request closed without merging**
