### PR TITLE
update python syntax >=3.6

### PR DESCRIPTION
**Pull request by Borda**
In fact, I was just adding a new hook to pre-commit `pyupgrade` which generated all these changes
also I have added `python_requires=">=3.6",` to the seup.py

An alternative would be enable pre-commit bot and then it would be clear that most of the changes comes just from the pre-commit hooks, see https://pre-commit.ci/

### CODE REVIEW

**Comment by Borda** [comment]
> One thing I'm not sure about is the commit hook, considering that some of these changes are making torchscript unhappy (see comment below), we might not be able to enforce this with a hook.

I may have related thought as each statement (code line) can be written in many ways, is the actual optimal, personally, I would keep any of these hook/bots and try to rewrite some small number of lines to complain of hook and also to be fine with you and `torchscript`... what do you think?

**Comment by Borda** [comment]
> We do enforce black-formatting now, since last week.

do you have it also in pre-commit hooks?
I see this one https://github.com/pytorch/vision/blob/221dd5f76c206d2d9c93dd910c71007bd6791082/.pre-commit-config.yaml#L5
but I don't think that it is the optimal one, rather use
```yaml
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        name: Format code
```
I can add it in separate PR

**Comment by NicolasHug** [comment]
`ufmt` is a combination of `black` and `usort`, we have to rely on this (and not on the individual formatters) because of compatibility reasons with FB's internal linters.

**Comment by Borda** [comment]
> Reference scripts are not tested by unit tests, did you verify that everything runs fine?

seems they require multi-node/GPU machines which I do not have in my disposal :(

**Comment by Borda** [comment]
seems to be failing on Segmentation fault :/

**Comment by datumbox** [comment]
@Borda It's not your PR, our CI is toasted... It should be resolved tomorrow using the latest nightly of PyTorch. Apologies for the inconvenience.

**Pull request merged**
