### PR TITLE
make ResNet and DenseNet more flexible for usage on smaller images

### PR DESCRIPTION
**Pull request by stadlmax**
- ResNet and DenseNet both are implemented to work best for datasets containing larger images like ImageNet. This is due to the the convolutional stem with a kernel_size of 7, a stride of 2 and an additional max-pooling layer. Moreover, most of the specifications for feature map sizes and number of basic building blocks/layers are fixed/hardcoded. 
- Both publications however mention experiments carried out on the Cifar10 dataset. For using those architecture on datasets consisting of smaller images, the implementation is lacking some flexibility. 
- The proposed changes allow changing specifications of the convolutional stem, number of building blocks/layers and the number of channels in the feature maps. Those changes are implemented without losing any backwards compatibility, i.e. all pre-trained models still can be used. 
- Moreover, shorthand models are defined following the definitions in the original experiments. ResNets used for Cifar10 are mainly characterized by the 'depth' with other settings taken from the paper. DenseNets used for Cifar10 are characterized by the 'growth_rate' and the 'depth' with settings taken from the publication analogously.

### CODE REVIEW

**Comment by pmeier** [comment]
Hey @StadlerMaximilian, I see why this is useful, but I can't decide if we want this or not. We'll have to wait for @fmassa for that. In the meantime, there are two issues that you need to address before this can get merged:

1. Our linter is failing with 

    ```
    ./torchvision/models/resnet.py:129:47: W291 trailing whitespace
    ./torchvision/models/resnet.py:130:85: W291 trailing whitespace
    ./torchvision/models/resnet.py:135:95: W291 trailing whitespace
    ./torchvision/models/resnet.py:136:107: W291 trailing whitespace
    ./torchvision/models/resnet.py:144:39: W291 trailing whitespace
    ./torchvision/models/resnet.py:152:98: W291 trailing whitespace
    ./torchvision/models/resnet.py:182:121: E501 line too long (127 > 120 characters)
    ./torchvision/models/resnet.py:184:109: W291 trailing whitespace
    ./torchvision/models/resnet.py:194:121: E501 line too long (135 > 120 characters)
    ./torchvision/models/resnet.py:196:121: E501 line too long (134 > 120 characters)
    ./torchvision/models/resnet.py:197:112: E226 missing whitespace around arithmetic operator
    ./torchvision/models/resnet.py:400:1: E302 expected 2 blank lines, found 1
    ./torchvision/models/resnet.py:401:46: W291 trailing whitespace
    ./torchvision/models/resnet.py:403:93: W291 trailing whitespace
    ./torchvision/models/resnet.py:407:106: W291 trailing whitespace
    ./torchvision/models/resnet.py:412:1: W293 blank line contains whitespace
    ./torchvision/models/resnet.py:416:85: W291 trailing whitespace
    ./torchvision/models/resnet.py:417:102: W291 trailing whitespace
    ./torchvision/models/densenet.py:152:121: E501 line too long (127 > 120 characters)
    ./torchvision/models/densenet.py:212:1: E302 expected 2 blank lines, found 1
    ./torchvision/models/densenet.py:293:1: E302 expected 2 blank lines, found 1
    ./torchvision/models/densenet.py:296:83: W291 trailing whitespace
    ./torchvision/models/densenet.py:298:52: W291 trailing whitespace
    ./torchvision/models/densenet.py:306:82: W291 trailing whitespace
    ./torchvision/models/densenet.py:307:87: W291 trailing whitespace
    ```

    Please address this.

2. The following failing tests are related:

    ```
    FAILED test/test_quantized_models.py::ModelTester::test_resnet18 - AssertionE...
    FAILED test/test_quantized_models.py::ModelTester::test_resnet50 - AssertionE...
    FAILED test/test_quantized_models.py::ModelTester::test_resnext101_32x8d - As...
    ```

    Could you look into that?

**Comment by vfdev-5** [comment]
I think this PR may be related to these issues: https://github.com/pytorch/vision/issues/1570 and https://github.com/pytorch/vision/issues/1166#issuecomment-515371986
Let's see if something changed meanwhile...

**Comment by pmeier** [comment]
@StadlerMaximilian In the light of https://github.com/pytorch/vision/issues/1570#issuecomment-558632419 I think you should hold fixing the errors above before you get green light that this will be implemented.

**Comment by StadlerMaximilian** [comment]
First of all, thank you for the comments and sorry for the trivial errors. I should have checked that in more detail.  

I haven't considered that a list of modules (currently) cannot be used in torch scripts (except when using a _nn.ModuleList_) which lead to the _AssertionError_, as e.g. mentioned in the PyTorch issue [#36061](https://github.com/pytorch/pytorch/issues/36061). Using a _nn.ModuleList_ however would destroy the compatibility with pre-trained models. 

My workaround is to limit the ResNet up to 4 layers (as the original existing implementation) and use nn.Identity to 'fill' layers if less are specified. This keeps the original structure of _self.layer1, ...., self.layer4_ which is compatible with torch scripts, but allows smaller networks and still introduces flexibility in changing the number of features used in those blocks. In particular, reproducing the paper's results on CIFAR10 is possible. 
However, it is certainly not the most elegant form to define smaller models. What is your opinion to introduce such a feature using such a workaround?

**Comment by pmeier** [comment]
@StadlerMaximilian Problem is that @fmassa rejected a previous proposal of the same feature as mentioned above. If nothing substantial has changed since then, I don't think we will go through with this PR. Mind that I can't make this decision; We'll have to wait for @fmassa for that. If I were you, I would stop working on this feature and wait for his feedback. Otherwise it might be wasted time.

**Comment by StadlerMaximilian** [comment]
@pmeier Thank you for the feedback. I am aware of the discussion about this issue. I needed those changes for a project anyways. And since I did some mistakes w.r.t the CI pipeline, I spent some time looking at this pipeline and how to write code correspondingly. So it is definitely not a waste of time for me. 

I understand the arguments with respect to consistency. However, as it was pointed out in the original issue, the general principles of the architecture do not change for different datasets. Besides changes in the specification of the architecture (like the convolutional stem, the number of basic building blocks, and the number of channels in the features maps), the models are the same. From a systems engineering point of view, it would make more sense to make the underlying model more flexible and define specific variants for certain datasets (like ImageNet). Architecture implementations like ResNet or DenseNet specify short-hand notations for specific model variants anyways (e.g. _resnet and resnet18 calling _resnet with specific model parameters). The usage of pre-trained models is specified for those and not for the underlying base class (e.g. ResNet). As torchvision currently does not provide "pre-trained models for different datasets than ImageNet / COCO / Kinetics", one simple thing to do is keep those short-hand definitions for those pre-trained models only while allowing flexibility in the underlying architecture implementation. 

On the other hand, changes allowing more flexibility probably would require similar changes for consistency reasons (all the models should work on the same classification task to some extent).

**Comment by fmassa** [comment]
Hi @StadlerMaximilian 

Thanks for opening the PR and sparkling the discussion.

I think the difficulty in here is that the design space for a given family of models is potentially very large. We should try to keep a balance between simplicity and generality. The underlying implementation of `ResNet` is generic enough to cover the models we have in torchvision, but as you noted it's not generic enough for other use-cases (like CIFAR).

I would actually prefer to be consistent and only have models in torchvision that have:
- pre-trained weights (so that users can directly use it and do transfer learning)
- been trained on a standard large-scale dataset (to make the model as generic as possible)
- expect images of a common input size (so ImageNet-scale input, we have exceptions like Inception, but most models expect 224x224)

As such, I would prefer if we don't move forward with this PR, but thanks a lot for it, it is very well implemented!

In the future, if you could please open an issue first so that we could discuss about the addition of new models, it would be better as it would avoid situations like this, where you have spent time working on the PR which we might not merge in torchvision, which is a pity.

**Pull request closed without merging**
