### PR TITLE
Added annotation typing to mobilenet

### PR DESCRIPTION
**Pull request by frgfm**
Hi there!

As per #2025, annotation typing are welcome in torchvision. So, this PR focuses on `torchvision.models.mobilenet` this PR!

Any feedback is welcome!

### CODE REVIEW

**Review by pmeier — COMMENTED** [review]
Only incremental changes needed from the other PRs. Otherwise LGTM.

**Comment by frgfm** [comment]
> Only incremental changes needed from the other PRs. Otherwise LGTM.

Fixed! Although, I'm still getting an issue I didn't manage to get around:
```
torchvision/models/mobilenet.py:82: error: List item 1 has incompatible type
"Conv2d"; expected "ConvBNReLU"  [list-item]
                nn.Conv2d(hidden_dim, oup, 1, 1, 0, bias=False),
                ^
torchvision/models/mobilenet.py:83: error: List item 2 has incompatible type
Module; expected "ConvBNReLU"  [list-item]
                norm_layer(oup),
                ^
torchvision/models/mobilenet.py:154: error: Argument 1 to "append" of "list"
has incompatible type Module; expected "ConvBNReLU"  [arg-type]
                    features.append(block(input_channel, output_channel, s...
```

**Comment by fmassa** [comment]
@pmeier any way of telling mypy that `ConvBNReLU` inherits from `Module`?

**Comment by pmeier** [comment]
I think annotating  `layers: List[nn.Module] = []` should be sufficient. If the annotation is left out `mypy` assumes the first type that is added to the list is the only one. Thus, it probably assumes that `layers` is `List[ConvBNReLU]` and thus complains. 

@frgfm You can check which type `mypy` uses for a variable by simply inserting `reveal_type(layers)` into the code and run `mypy` over it.

**Comment by frgfm** [comment]
> @frgfm You can check which type `mypy` uses for a variable by simply inserting `reveal_type(layers)` into the code and run `mypy` over it.

Neat trick @pmeier :ok_hand: Your suggestion is working, just pushed it!

**Review by fmassa — APPROVED** [review]
Thanks!

**Pull request merged**
