### PR TITLE
Replace distutils.spawn with shutil.which per PEP632 in setup script

### PR DESCRIPTION
**Pull request by bjuncek**
Addressing #5837

### CODE REVIEW

**Review by NicolasHug — APPROVED** [review]
Thanks @bjuncek , LGTM if green

**Comment by bjuncek** [comment]
@NicolasHug the failing unit test seems unrelated to me but I might be missing something.

**Comment by NicolasHug** [comment]
Yes it's safe to ignore as it's been failing for a while.

I'll just wait for @datumbox to take a look before merging. Since all jobs have run (and compiled torchvision) successfully I think this is safe to go on my side

**Review by datumbox — APPROVED** [review]
LGTM, thanks for checking. The specific job is failing for unrelated reasons, we should be OK.

**Pull request merged**
