### PR TITLE
Vflip and Hflip In tensor format

### PR DESCRIPTION
**Pull request by surgan12**
cc: @fmassa reopened.
ref: #1375

### CODE REVIEW

**Comment by fmassa** [comment]
Didn't seem to work. I'll try contacting CircleCI to see what's going on

**Comment by fmassa** [comment]
@surgan12 I found this on their support page https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

Can you follow what's listed there and let me know once you've done it?

**Comment by surgan12** [comment]
Sure !!

**Comment by fmassa** [comment]
@surgan12 there is a problem with CI, I'm trying to fix it but I think there is no need to close-reopen the PR for now

**Comment by fmassa** [comment]
@surgan12 I've fixed CI in master, can you rebase your PR and do the change in CircleCI mentioned in https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization- so that we can run tests on your PR

**Comment by surgan12** [comment]
@fmassa, the error has been resolved. Thanks !

**Pull request merged**
