### PR TITLE
Add Shear and RandomShear

### PR DESCRIPTION
**Pull request by ekagra-ranjan**
This PR adds Shear and RandomShear which were not available as a standalone transformation like Rotation.

### CODE REVIEW

**Comment by ekagra-ranjan** [comment]
@fmassa Is this fine?

**Comment by ekagra-ranjan** [comment]
@fmassa Is this fine?

**Comment by ekagra-ranjan** [comment]
cc: @fmassa

**Comment by vfdev-5** [comment]
@ekagra-ranjan can I ask why we need to introduce `RandomShear` as specification of `RandomAffine` ?  I mean, the following transformation 
```python
t = RandomAffine(degrees=0, shear=s)
```
performs shear transformation.
Am I missing something ?

**Comment by ekagra-ranjan** [comment]
@vfdev-5 The addition of Shear is motivated from the transformation `Rotate` which exists as a standalone transformation even though it could also have been implemented as 

`t = RandomAffine(degrees=0, shear=s)`

**Comment by vfdev-5** [comment]
@ekagra-ranjan that's true about `RandomRotate`, but the main difference is that `RandomAffine` was implemented later that `RandomRotate`.
Anyway, @fmassa will decide whether we this PR is fine. 
Just another remark is that your current implementation looks like a code copying with specialization.

**Pull request closed without merging**
