### PR TITLE
Add auto-augment introduced transforms in docs

### PR DESCRIPTION
**Pull request by datumbox**
Related to #3784

Adds in the documentation all the new transforms introduced during the AutoAugment work that are currently missing.

### CODE REVIEW

**Review by NicolasHug — APPROVED** [review]
Let's add them to the gallery as well?

**Comment by datumbox** [comment]
@NicolasHug Good call. Could you review again please? I don't have a great way to view the changes on my setup. Hoping you can confirm it renders OK.

**Review by NicolasHug — COMMENTED** [review]
It seems that some of them should be in the "Randomly-applied" section rather than in the "random" section?

Also it's not clear what the effect on the image is for some of them: for example RandomAutocontrast, RandomPosterize 

Regarding RandomSolarize, is there an issue in the plot or is this expected?

**Comment by datumbox** [comment]
I made the RandomPosterize more extreme so that the effect is more visible. RandomSolarize works as expected. RandomAutocontrast is basically a fancy contrast transform so it's hard to visually see with such a small image.

**Pull request merged**
