### PR TITLE
Add VGGface2 dataset

### PR DESCRIPTION
**Pull request by dakshjotwani**
PR for adding VGGFace2 dataset.

Questions:
1. I'm not sure on how to add test cases for this (Not sure how to produce fake data to test it). I tried to find `CelebA` test cases to use as reference and didn't see any test cases for that dataset either.
2. Currently I am using a dictionary to store bounding box and landmark data. Do you think it would be better/more efficient to store it as a list instead?

### CODE REVIEW

**Comment by dakshjotwani** [comment]
> About the structure of the dataset, I'm thinking if we should always return the full image plus a dict with the `id` / `box` / `landmarks`.

This might not be a good idea, since it will require the user to download all the optional metadata files to use the dataset. If all the metadata came from one file, this would have been good. Also, having to provide additional data only to remove it using a target_transform feels wrong. What do you think?

**Comment by fmassa** [comment]
> since it will require the user to download all the optional metadata files to use the dataset

But the metadata is much smaller than the images in size, right? So this should not be a problem I think. And we could provide the download function in the dataset itself.

> Also, having to provide additional data only to remove it using a target_transform feels wrong. What do you think?

I'm not 100% sure. Having the type of output of the dataset depend on a constructor argument doesn't sound like the best thing to me.

I'll let others give their opinion in here.

cc @soumith @cpuhrsch @zhangguanheng66 what do you think?

**Comment by fmassa** [comment]
I'm very sorry for the delay in replying, it was sent just after I came back from holidays and I missed your message from a pile of notifications.

I still think that returning a dict with all the metadata would make more sense, if it's what the dataset provides by default. As I mentioned before, having the return values depend on a constructor argument adds a lot less structure to the datasets, and is done only for convenience with the current transforms. Plus, we would probably also want to handle the empty case as well, as discussed in https://github.com/pytorch/vision/pull/1351

I'll ping @cpuhrsch @zhangguanheng66 and @vincentqb again on thoughts about it.

**Comment by vincentqb** [comment]
> I still think that returning a dict with all the metadata would make more sense, if it's what the dataset provides by default.

I second that, with maybe a minor tweak. 

Do we have an example of a dataset returning more than one tensor? I'd say a dict is a good idea, but the tensors returned could be part of it to address such case. This however pushes the organization of a dataset into how we structure the dict itself. :) Thoughts?

> it will require the user to download all the optional metadata files to use the dataset. If all the metadata came from one file, this would have been good.

Can you clarify this @dakshjotwani? Could the dict only contain the fields that were downloaded?

**Comment by dakshjotwani** [comment]
Sorry for the late reply, I just saw these messages buried in my email!

> Can you clarify this @dakshjotwani? Could the dict only contain the fields that were downloaded?

Yes we can. I think that's a good way to avoid returning extra data that would later end up being removed with a target_transform.

@fmassa I agree that returning a dict is a good idea as long as we construct the dict based on the metadata/fields files provided as args to the constructor. What do you think?

**Comment by jgbradley1** [comment]
Is this PR still being worked?

**Comment by dakshjotwani** [comment]
I can pick it up again. @fmassa @jgbradley1 should I close this PR and open a new one? This one's about a year old and a lot of things have changed since then.

**Comment by jgbradley1** [comment]
Since 2 files are only impacted by this change, it seems simpler to just update the branch from `master`. There would really only be one conflict to resolve probably (i.e. no need to start a new PR).

I'm interested in seeing this dataset get added.

A couple suggestions I have:
* consider adding a `download` option
* if you're not going to add a `download` option to the class, consider adding some more information in the docstring that explains the expected folder structure that the data files must be in. I just submitted a [PR](https://github.com/pytorch/vision/pull/2883) for another dataset and after reading through several of the current Dataset classes, I started to realize how unclear it may be to new users (that use a local copy) to hook up torchvision to their local folders.
* consider adding a `split` argument that must be set to either `train`/`test`. It's not immediately clear to me what partition is being used.

**Comment by jgbradley1** [comment]
Since this PR has been open for awhile, I wrote a quick updated version of what the dataset could look like [here](https://github.com/jgbradley1/vision/blob/add-vggface2-dataset/torchvision/datasets/vggface2.py). It matches the design of the CelebA Dataset.

**Comment by yassineAlouini** [comment]
It seems that this PR is being continued here: https://github.com/pytorch/vision/pull/2910. I guess it can be closed @pmeier?

**Comment by pmeier** [comment]
Given that @dakshjotwani [wrote](https://github.com/pytorch/vision/pull/1193#issuecomment-715556783):

> I can pick it up again.

and @jgbradley1 already send the update in #2910, I'm going to close this PR.

**Pull request closed without merging**
