### PR TITLE
test_randomresized_params fixes

### LINKED ISSUE #1170: test_randomresized_params is flaky
See https://travis-ci.org/pytorch/vision/jobs/563558702

```
self = <test_transforms.Tester testMethod=test_randomresized_params>
    def test_randomresized_params(self):
        height = random.randint(24, 32) * 2
        width = random.randint(24, 32) * 2
        img = torch.ones(3, height, width)
        to_pil_image = transforms.ToPILImage()
        img = to_pil_image(img)
        size = 100
        epsilon = 0.05
        for _ in range(10):
            scale_min = round(random.random(), 2)
            scale_range = (scale_min, scale_min + round(random.random(), 2))
            aspect_min = max(round(random.random(), 2), epsilon)
            aspect_ratio_range = (aspect_min, aspect_min + round(random.random(), 2))
            randresizecrop = transforms.RandomResizedCrop(size, scale_range, aspect_ratio_range)
            i, j, h, w = randresizecrop.get_params(img, scale_range, aspect_ratio_range)
            aspect_ratio_obtained = w / h
>           assert (min(aspect_ratio_range) - epsilon <= aspect_ratio_obtained <= max(aspect_ratio_range) + epsilon or
                    aspect_ratio_obtained == 1.0)
E           AssertionError: assert (1.411764705882353 <= (1.3599999999999999 + 0.05) or 1.411764705882353 == 1.0)
E            +  where 1.3599999999999999 = max((0.96, 1.3599999999999999))
```

### PR DESCRIPTION
**Pull request by surgan12**
Fixes #1170

### CODE REVIEW

**Comment by fmassa** [comment]
(closed and reopened to rerun tests)

**Comment by surgan12** [comment]
@fmassa , the tests are still failing.

**Comment by fmassa** [comment]
Let's see if they pass now

**Comment by surgan12** [comment]
@fmassa , i think it is good to go now.

**Comment by fmassa** [comment]
My previous reasoning was wrong. I'm closing this in favor of https://github.com/pytorch/vision/pull/1282

Thanks @surgan12 for the original PR!

**Pull request closed without merging**
