### PR TITLE
Pin ninja version for Windows jobs

### PR DESCRIPTION
**Pull request by peterjc123**

### CODE REVIEW

**Comment by peterjc123** [comment]
@seemethere Nope, the linux one is fine.

**Comment by fmassa** [comment]
FYI there is a breakage introduced in PyTorch which affects torchvision CI.
It should be fixed with https://github.com/pytorch/pytorch/pull/40041

**Comment by peterjc123** [comment]
@fmassa Yeah, I know. Actually you could merge it so that the wheel jobs will be fixed.

**Comment by ezyang** [comment]
TBH you should still just pin it for everything

**Comment by peterjc123** [comment]
@ezyang @seemethere Done.

**Pull request merged**
