### PR TITLE
[ROCm] Update to rocm5.0 wheels

### PR DESCRIPTION
**Pull request by KyleCZH**
fixing https://github.com/pytorch/vision/issues/5658

@jeffdaily @jithunnair-amd

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]

**Comment by NicolasHug** [comment]
Thanks @KyleCZH and @jithunnair-amd 

@malfet is this something you could take a look at?

**Comment by KyleCZH** [comment]
any updates?

**Review by datumbox — APPROVED** [review]
LGTM, thanks for the change.

@NicolasHug The RelEng team seems busy. The change seems straight forward, are you OK if we merge this as-is?

**Comment by NicolasHug** [comment]
No opinion on my side I'm not competent on this

**Comment by datumbox** [comment]
Given the simplicity of the change and the fact that @jithunnair-amd reviewed and approved I'll merged this.

@malfet @seemethere if you have concerns feel free to revert.

**Pull request merged**
