### PR TITLE
List comprehension instead of a loop

### PR DESCRIPTION
**Pull request by theonekeyg**
Tiny tweak

### CODE REVIEW

**Comment by mthrok** [comment]
Thanks for the PR, however this reduces readability of the code and it does not reproduce the same behavior.

**Comment by fmassa** [comment]
To complement @mthrok message, tests fail with this PR, see https://circleci.com/gh/pytorch/vision/129637?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link for example

**Comment by theonekeyg** [comment]
Hi @fmassa, thanks for this link to test. Hmm, i really can't figure out why would this PR change the previous behavior, do you have any suspicion?

**Comment by fmassa** [comment]
@theonekeyg I think the difference now comes from the fact that `is_valid_file(fname)` is called on `fname` instead of `path`.

**Pull request closed without merging**
