### PR TITLE
Make weights tables row size smaller

### PR DESCRIPTION
**Pull request by NicolasHug**

### CODE REVIEW

**Comment by pmeier** [comment]
[Rendered docs](https://output.circle-artifacts.com/output/job/ff6eb89f-2f35-4612-8c16-ce4d2da9e0b7/artifacts/0/docs/models_new.html#table-of-all-available-classification-weights).

**Review by pmeier — APPROVED** [review]
LGTM, thanks Nicolas!

**Comment by NicolasHug** [comment]
> [Rendered docs](https://output.circle-artifacts.com/output/job/ff6eb89f-2f35-4612-8c16-ce4d2da9e0b7/artifacts/0/docs/models_new.html#table-of-all-available-classification-weights).

Thanks Philip.  It also changes the style of the individual weight tables in the model builders' pages:

image

**Comment by NicolasHug** [comment]
Thanks a lot @svekars for the CSS suggestions!

**Pull request merged**
