### PR TITLE
Update unstable docs from master to main

### LINKED ISSUE #4356: Migrate Docs from master to main
### 📚 The doc issue

Inorder to view the latest docs Users should NOT navigate to https://pytorch.org/vision/master/index.html

but instead navigate to

https://pytorch.org/vision/main/index.html

This happens because Main is not visible in the version selector, 
image

### Suggest a potential alternative/fix

Simple fix is to edit https://github.com/pytorch/vision/blob/gh-pages/versions.html#L21  
To include main instead of master.
Note that this is in the gh-pages (deployed over GitHub) branch.

I can probably send a PR!

### PR DESCRIPTION
**Pull request by oke-aditya**
Resolves #4356 

- [x] Add .gitignore
- [x] Edits versions.html and Readme
- [x] Create symbolic link for master to main.

Note that this PR goes to gh-pages branch and not to the master branch.

### CODE REVIEW

**Comment by oke-aditya** [comment]
Hi @NicolasHug  I think I have done all the changes. Also I think I have created a correct symlink for master to main.
Can you have a look at CircleCI failure?

**Comment by oke-aditya** [comment]
Apparently the Circle CI failure appeared in torchaudio PR too. 
https://github.com/pytorch/audio/pull/1676

**Review by NicolasHug — APPROVED** [review]
Thanks a lot @oke-aditya , this LGTM.

If you don't mind, let's wait until early next week to merge it: if this PR breaks anything, we wouldn't be able to fix it during the weekend.

I saw that you added a gitignore, not strong opinion on this but did you find it necessary?

**Comment by oke-aditya** [comment]
The gitignore is also in torchaudio over gh-pages. I merely copy pasted it. And added to ignore editor configs. 

Also there is a small chance someone working on torchvision might push it and docs. So just added that too. (It did happen in my editor why made it hard to see stuff).

**Comment by oke-aditya** [comment]
Let's merge over weekend. 😀 Good idea.

**Comment by fmassa** [comment]
Thanks!

**Pull request merged**
