### PR TITLE
NOMRG Show libjpeg version when building

### PR DESCRIPTION
**Pull request by NicolasHug**

### CODE REVIEW

**Comment by NicolasHug** [comment]
From the logs it looks like linux is using `jpeg-9b-h024ee3a_2` and windows is using `jpeg-9b-hb83a4c4_2`.

So they're both 9b versions clearly, but looking at https://anaconda.org/anaconda/jpeg/files?sort=time&sort_order=desc&version=9b the windows binary is 1.5 years older than the linux one... which seems a bit fishy. It's possible that the linux version contains patches / fixes that the windows version doesn't have.

CC @fmassa , any thought?

**Comment by NicolasHug** [comment]
That being said I still don't know how to verify which version is used by torchvision and by PIL  🤔

**Comment by fmassa** [comment]
> From the logs it looks like linux is using jpeg-9b-h024ee3a_2, macos is using jpeg-9b-he5867d9_2 and windows is using jpeg-9b-hb83a4c4_2.

Thanks for checking this!

> the windows binary is 1.5 years older than the linux and the macos ones... which seems a bit fishy

that is interesting. Yeah, that definitely looks suspicious.

> That being said I still don't know how to verify which version is used by torchvision and by PIL 🤔

We could probably add a method like https://github.com/pytorch/vision/blob/21426ddc98cbc87b318b1712191951c771ad58f0/torchvision/csrc/vision.cpp#L25-L30 that prints the jpeg version.

Something like 
```python
torchvision.io._print_jpeg_version()
```

But there might be an easier way if we ssh into the CI

**Comment by NicolasHug** [comment]
Thanks a lot for the help @fmassa . As we suspected, the libjpeg version on Windows CI jobs is different for PIL and for torchvision:

```
python -c "from PIL import _imaging; print(_imaging.jpeglib_version)"
8.0
python -c "import torch; import torchvision; print(torch.ops.torchvision._jpeg_version())"
90
```

on the linux job, it is the same:

```
(/root/project/env) [root@4d1d2d6edd3d project]# python -c "from PIL import _imaging; print(_imaging.jpeglib_version)"
9.0
(/root/project/env) [root@4d1d2d6edd3d project]# python -c "import torch; import torchvision; print(torch.ops.torchvision._jpeg_version())"
90
```

**Comment by fmassa** [comment]
Awesome, thanks for the investigation @NicolasHug !

This means that we are consistent on our side. Maybe we can open an issue in PIL to mention that they use different versions of libjpeg depending on the OS?

**Comment by NicolasHug** [comment]
Oh:

On windows:

```
python -c "from PIL import features; print(features.check_feature('libjpeg_turbo'))"
True
```

On linux:

```
python -c "from PIL import features; print(features.check_feature('libjpeg_turbo'))"
False
```

**Comment by NicolasHug** [comment]
Closing this, I followed up in https://github.com/pytorch/vision/issues/3913

**Pull request closed without merging**
