### PR TITLE
Add description for Dataset objects

### PR DESCRIPTION
**Pull request by vishwakftw**
This closes https://github.com/pytorch/vision/issues/383.

Currently this is how it is displayed (for MNIST). Please let me know what you think.
```python
>>> import torchvision as tv
>>> transform = tv.transforms.Compose([tv.transforms.ToTensor(), tv.transforms.Normalize((0.5,), (0.5,))])
>>> tv.datasets.MNIST(root='./MNIST_data', transform=transform, target_transform=transform)
Dataset MNIST
    Number of datapoints: 60000
    Split: train
    Root Location: ./MNIST_data
    Transforms (if any): Compose(
                             ToTensor()
                             Normalize(mean=(0.5, 0.5), std=(0.5, 0.5))
                         )
    Target Transforms (if any): Compose(
                                    ToTensor()
                                    Normalize(mean=(0.5, 0.5), std=(0.5, 0.5))
                                )
```

### CODE REVIEW

**Comment by vishwakftw** [comment]
Is it possible to test `__repr__()`? I found no test files available, and I think it would be hard to test without downloading, I believe.

**Comment by soumith** [comment]
tests are here: https://github.com/pytorch/vision/blob/master/test/test_transforms.py

Just call repr inside this file for each transform and that should be sufficient as a smoke test

**Comment by vishwakftw** [comment]
Oh, I am sorry. I meant the `__repr()__` for the Dataset objects. The tests for transforms objects have been added already.

**Comment by soumith** [comment]
oh i see, yea no good way to test these things. it's fine for now.

**Pull request merged**
