### PR TITLE
Fixed warning in torchvision.models.detection.transforms._resize_image_and_masks.

### PR DESCRIPTION
**Pull request by maxfrei750**
`torchvision.models.detection.transforms._resize_image_and_masks` raises the following warning, when being run with `torch>=1.6.0`:

```
UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details.
```

This was already mentioned in #2154, but apparently not fixed yet.

This PR fixes the warning by restoring the original behavior.

EDIT: I think, originally, @java-abhinav07  wanted to create a PR, so he might have some insights on whether the fix is good.

### CODE REVIEW

**Review by datumbox — CHANGES_REQUESTED** [review]
@maxfrei750 Thanks for the PR.

If this is to be addressed like this we will probably need to also aligning the onnx method:
https://github.com/pytorch/vision/blob/c86417183faee7bb24d799b1b8b158a8ba7c93c1/torchvision/models/detection/transform.py#L30

@fmassa Could you also have a look to confirm if we want to maintain the old behaviour here?

**Comment by fmassa** [comment]
Thanks for the PR!

@datumbox I would say that this PR keeps the old behavior (but without the warning), so this is good.
If we wanted to switch in the future to the new default behavior (`recompute_scale_factor=False`), we would need to perform a validation of the results to see if it affects the results a bit (I don't think it should affect them in a significant manner, but would still be good to validate)

@maxfrei750 can you address the other comment from @datumbox so that we can get this PR merged?

**Comment by maxfrei750** [comment]
@fmassa Thanks for the review. 

I just made the requested change.

**Review by fmassa — APPROVED** [review]
Thanks!

**Pull request merged**
