### PR TITLE
[WIP] Implement torchvision.utils.draw_bounding_boxes

### PR DESCRIPTION
**Pull request by sumanthratna**
see #2556 for details

status:
- [ ] implements `torchvision.utils.draw_bounding_boxes`
- [ ] adds appropriate tests
- [ ] adds appropriate docs

CC @pmeier

### CODE REVIEW

**Comment by oke-aditya** [comment]
Hey @sumanthratna are you working on this? Can I work together with this and help in getting it merge 😃

**Comment by sumanthratna** [comment]
> Hey @sumanthratna are you working on this? Can I work together with this and help in getting it merge 😃

Hi @oke-aditya! I, unfortunately, can't work on this anymore because of school—but please do contribute! I've added you as a collaborator to my fork but feel free to open a new PR if you want!

**Comment by oke-aditya** [comment]
Let me try. I would refactor a bit. 
Also, use the torchvision native `read_image` function that was introduced recently instead of PIL.
Let me have a go !
Can you convert this PR from draft to open?
Since I cannot do that and I can then continue on this PR. I don't want to open up a new PR as this looks half way there.
(It keeps your contributions same as I don't want to copy paste your code and not have them in contributions)

**Comment by pmeier** [comment]
@oke-aditya I'm unsubscribing for now. Ping me when you are done.

**Comment by sumanthratna** [comment]
closing in favor of #2785. thanks @oke-aditya!

**Pull request closed without merging**
