### PR TITLE
make the tensor continuous when passing numpy object to tensor

### PR DESCRIPTION
**Pull request by dddzg**
The to_tensor will return noncontiguous tensor if we pass the NumPy image (e.g. reading image by cv.imread). It is very common usage. If we pass a PIL object, however, it will be contiguous (https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L93).
I think It is necessary to make them consistent.

Check the code 
`torch.from_numpy(np.random.rand(299,299,3).transpose(2,0,1)).is_contiguous()`
it will return `False`.

### CODE REVIEW

**Review by vfdev-5 — APPROVED** [review]
Thanks for the PR @dddzg !
This makes sense.

PS: sorry for delay.

**Comment by vfdev-5** [comment]
@dddzg could you please update your branch to the current master. Thanks !

**Comment by dddzg** [comment]
@vfdev-5 Hi, thanks for your reply. I have updated the branch.

**Comment by vfdev-5** [comment]
Hi @dddzg could you please update your branch such that we see only your commit. Probably, merge instead of rebase.

**Comment by dddzg** [comment]
oops. Is there any chance I can make it right?

**Comment by vfdev-5** [comment]
@dddzg thanks, it is OK now !

**Comment by dddzg** [comment]
@vfdev-5 It seems to be OK now with force-push?

**Comment by vfdev-5** [comment]
@dddzg looks good !

**Comment by dddzg** [comment]
anything else shall I do?

**Comment by vfdev-5** [comment]
@dddzg it is OK for now. I'll talk about this PR tomorrow with @fmassa

**Comment by moi90** [comment]
I'm surprised that you decided to make contiguous the default. I would argue that it would be better to leave them non-contiguous in the general case, because `.contiguous()` incurs a mandatory copy which is a dramatic performance penalty (and superfluous in most cases as the data needs to be copied a second time when multiple images are assembled into a batch).

**Comment by fmassa** [comment]
I agree with @moi90 comment above

@vfdev-5 do you remember the reasons why we made the tensor contiguous in the first place?

**Comment by fmassa** [comment]
FYI, our `read_image` functions don't return contiguous tensors specifically for the reasons mentioned by @moi90

**Comment by vfdev-5** [comment]
I think it was to keep it consistent with PIL input: https://github.com/dddzg/vision/blob/bf0ad73b9610fac8f117810a3e30c7389c727e4f/torchvision/transforms/functional.py#L100

**Comment by fmassa** [comment]
Oh I see. Sounds good then. The `ToTensor` does too many things internally anyway, and in previous versions of PyTorch performing the `/ 255` normalization would cast the tensor to be contiguous as well, so let's keep things as is.

**Comment by moi90** [comment]
> I think it was to keep it consistent with PIL input: https://github.com/dddzg/vision/blob/bf0ad73b9610fac8f117810a3e30c7389c727e4f/torchvision/transforms/functional.py#L100

If consistency is important, I would rather remove the `.contiguous()` in both places.
This way, the conversion can take place implicitly when needed and no overhead for memory copies is incurred otherwise.

But if you think this is the correct behavior, I don't feel too strongly about this.

**Comment by datumbox** [comment]
Ok, taking a step back... 

@fmassa @vfdev-5 `pil_to_tensor()` [does not call contiguous](https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L168) while `to_tensor()` [calls contiguous](https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L136)... 

Few thoughts:
1. Shall we align the two?
2. Can we make pil_to_tensor() call to_tensor() and cast to right type instead of having to separate similar implementations?

**Comment by theahura** [comment]
Not sure if this falls in the realm of 'unexpected results', but wanted to flag https://github.com/pytorch/vision/issues/4529 which runs into process hangs specifically on the `contiguous()` call.

**Pull request merged**
