### PR TITLE
Fix location of dropout in VGG

### LINKED ISSUE #92: VGG classifier setting different from Original paper
One of the dropout layer was "wrongly" inserted.
The original final layers of Caffe Version (https://gist.github.com/ksimonyan/211839e770f7b538e2d8) is:
self.classifier = nn.Sequential(
            nn.Linear(512 * 7 * 7, 4096),
            nn.ReLU(True),
            nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(True),
            nn.Dropout()
            nn.Linear(4096, 1000),
        )
This won't make difference when we use model.eval(), but will make discrepancy if we want to finetune VggNet by loading Caffe's parameters.

### PR DESCRIPTION
**Pull request by colesbury**
Fixes #92

I've re-trained the VGG models on ImageNet. The fixed dropout location improved the accuracy.

### CODE REVIEW

**Comment by colesbury** [comment]
For posterity:

I trained the models using the [https://github.com/pytorch/examples/tree/master/imagenet](ImageNet example):

```
python3 -u main.py -a vgg11 -j 16 --lr 0.01 /path/to/imagenet/ | tee vgg11.stdout.log
python3 -u main.py -a vgg13 -j 16 --lr 0.01 /path/to/imagenet/ | tee vgg13.stdout.log
python3 -u main.py -a vgg16 -j 16 --lr 0.01 /path/to/imagenet/ | tee vgg16.stdout.log
python3 -u main.py -a vgg19 -j 16 --lr 0.01 /path/to/imagenet/ | tee vgg19.stdout.log
```

[https://gist.github.com/colesbury/bb2dcf9fa0344d2228b6239ec0601d39](vgg11.stdout.log)
[https://gist.github.com/colesbury/8a6c5cbf9e4ae7d47fede271740ee7bd](vgg13.stdout.log)
[https://gist.github.com/colesbury/95f563168a27ffcb1de19bd5b6908955](vgg16.stdout.log)
[https://gist.github.com/colesbury/5a6c1aae30a0815b162dd6c12952a5d2](vgg19.stdout.log)

**Comment by ecolss** [comment]
@colesbury

So we can download the new models using the same url as before, right?

**Comment by ecolss** [comment]
@colesbury 

Downloaded this latest vgg19 model, but error occurs when loading it:

```
/usr/local/lib/python3.6/site-packages/torch/serialization.py in load(f, map_location, pickle_module)
    220         f = open(f, 'rb')
    221     try:
--> 222         return _load(f, map_location, pickle_module)
    223     finally:
    224         if new_fd:

/usr/local/lib/python3.6/site-packages/torch/serialization.py in _load(f, map_location, pickle_module)
    368     unpickler = pickle_module.Unpickler(f)
    369     unpickler.persistent_load = persistent_load
--> 370     result = unpickler.load()
    371
    372     deserialized_storage_keys = pickle_module.load(f)

AttributeError: Can't get attribute '_rebuild_tensor' on <module 'torch._utils' from '/usr/local/lib/python3.6/site-packages/torch/_utils.py'>

```

**Comment by colesbury** [comment]
You need to be running the latest version of PyTorch as well. You may have
to build from master for now.

**Comment by soumith** [comment]
this error would be fixed with the release on Wednesday v0.1.11.

**Comment by ecolss** [comment]
I see, thanks

**Pull request merged**
