### PR TITLE
Deprecate functional_pil and functional_tensor and make them private

### PR DESCRIPTION
**Pull request by NicolasHug**
This PR moves `functional_pil.py` into `_functional_pil.py` and let  `functional_pil.py` have the same content (ish), with a warning.
The changes are made for `functional_tensor.py`.

These changes are hard to test because if we want to make sure all scenarios raise the proper warning, we need multiple executions of the Python interpreter. This can be done via [utils like this one](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/utils/_testing.py#L747) form scikit-learn which is used [like this](https://github.com/scikit-learn/scikit-learn/pull/12807/files#diff-00a227550f7960b32289b87752c97d62dbb7707d316ca8d3ca34b6199bb691a2).

I... can't be arsed to go through that right now. If you have a better idea, LMK :)
As manual check, all those blocks below properly raise the warning:

```py
from torchvision.transforms import functional_pil # warns
import torchvision.transforms.functional_pil as fp # warns

from torchvision.transforms.functional_pil import resize # warns
print(resize)

# Importing stuff that was already private breaks: this is for the best?
# from torchvision.transforms.functional_pil import _parse_fill  # Breaks
# from torchvision.transforms.functional_tensor import _is_tensor_a_torch_image  # Breaks

from torchvision.transforms import functional_tensor # warns
import torchvision.transforms.functional_tensor as ft #warns

from torchvision.transforms.functional_tensor import resize # warns
print(resize)
```

### CODE REVIEW

**Comment by NicolasHug** [comment]
And sadly `git` doesn't understand it was a simple `git mv` rather than a big change... So the diff looks much bigger than it actually should. Not sure we can do much about this either.

**Review by vfdev-5 — APPROVED** [review]
LGTM, thanks @NicolasHug

**Review by pmeier — APPROVED** [review]
LGTM if CI is green. Thanks Nicolas!

**Comment by NicolasHug** [comment]
Thanks for the reviews, failures are unrelated, merging

**Comment by Ahmaddimran** [comment]
At this line of code: from pytorchvideo.transforms import (ApplyTransformToKey, Normalize,UniformTemporalSubsample) I am getting ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor' how can I solve this after this depreciation?

**Comment by wohaoeRiver** [comment]
> 在这行代码中： from pytorchvideo.transforms import (ApplyTransformToKey, Normalize,UniformTemporalSubsample) 我收到 ModuleNotFoundError: No module named 'torchvision.transforms.function_tensor' 折旧后如何解决此问题？

TorchVision Version Issue: Use a version below 0.17, or modify the `degradations.py` file in your Python directory by replacing 
`from torchvision.transforms.functional_tensor import rgb_to_grayscale` with `from torchvision.transforms.functional import rgb_to_grayscale`.

**Comment by aminakmim** [comment]
> At this line of code: from pytorchvideo.transforms import (ApplyTransformToKey, Normalize,UniformTemporalSubsample) I am getting ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor' how can I solve this after this depreciation?

facing same issue

**Comment by ibtehajali67** [comment]
python -m pip install torch==2.0.1 torchvision==0.15.2 --extra-index-url https://download.pytorch.org/whl/cu118

**Pull request merged**
