### PR TITLE
Add groups support to ResNet

### PR DESCRIPTION
**Pull request by fmassa**
This adds the necessary building blocks to add support for ResNeXt models in torchvision.

One thing worth discussion: should we let the user specify arbitrary number of channels in each layer (as is currently supported in `BaseResNet`), or just stick with the options that are necessary to cover ResNet / ResNeXt?

### CODE REVIEW

**Comment by ekagra-ranjan** [comment]
ResNets and its variants find their place as a building block in many new models. So providing a flexibility in choosing the number of channels (besides choosing the layer configuration) would give more power and ease to users while constructing their own custom models. And since there is a relation between the number of channels and groups, the implementation is quite neat and will remind the user (experimenting the source code) about the relation proposed by the authors.

**Comment by fmassa** [comment]
@ekagra-ranjan just to make sure I understand, were you advocating for passing the `layers` argument (as it was before, in the BaseResNet) or just the `width_per_group` ?

**Comment by ekagra-ranjan** [comment]
I am supporting the BaseResNet implementation that you implemented earlier in the PR which has `planes` and `layers` arguments.

**Comment by fmassa** [comment]
I'll be merging this as is for now to unblock a few other things, and I can add back BaseResNet in a follow-up implementation.

**Pull request merged**
