### PR TITLE
Adding ROIAlign backwards for CPU

### PR DESCRIPTION
**Pull request by xssChauhan**
Adding ROIAlign backwards implementation for CPU.

Implemented using vision's CUDA implementation for the same purpose.

Currently the layers branch is not compiling.

### CODE REVIEW

**Comment by fmassa** [comment]
Thanks for the PR!

I believe we still need to modify [this file](https://github.com/pytorch/vision/blob/layers/torchvision/csrc/ROIAlign.h#L43) in order for the CPU dispatch to work?

**Comment by xssChauhan** [comment]
@fmassa My bad! Fixing this.

**Comment by xssChauhan** [comment]
@fmassa Fixed the python interface

**Comment by sampepose** [comment]
Can you make sure flake8 runs successfully on your code? CI is failing since there are some linter errors.

**Comment by fmassa** [comment]
@sampepose  I believe the flake8 issues are on my end. I need to fix them before merging the `layers` branch into master.
And we don't currently have a linter for C++ in torchvision, so this should be fine.

**Comment by fmassa** [comment]
@xssChauhan could you please write a small python file that tests that the gradients are indeed computed correctly?
For that, you can use PyTorch `torch.autograd.gradcheck`. Also, when running the code, make sure that you are using double tensors - if you use float tensors, you'll have problems because of the lack of precision for finite differences differentiation that `gradcheck` uses to compare the gradients.

Once we know that the gradcheck is passing, I'll merge this patch.

Thanks!

**Comment by xssChauhan** [comment]
@fmassa Will do so

**Comment by xssChauhan** [comment]
@fmassa Layers branch is currently not compiling.

Here's the error:

**Comment by xssChauhan** [comment]
Yes. Initially thought that it was introduced by me. Then tried on the `layers` branch, and found the same issue.

**Comment by fmassa** [comment]
weird. Let me try compiling it (last time I checked it was working)

**Comment by fmassa** [comment]
Ok, I know what's going on.

You need to have a source install from PyTorch. The bug you are facing was fixed in https://github.com/pytorch/pytorch/pull/6986

**Comment by xssChauhan** [comment]
Understood. Would install PyTorch from source.
Was using pip installation till now. Thank you :)

**Comment by xssChauhan** [comment]
@fmassa Installed PyTorch from source and then tried compiling the layers branch.
Here's the error that i got:
```
running install
running bdist_egg
running egg_info
writing torchvision.egg-info/PKG-INFO
writing dependency_links to torchvision.egg-info/dependency_links.txt
writing requirements to torchvision.egg-info/requires.txt
writing top-level names to torchvision.egg-info/top_level.txt
reading manifest file 'torchvision.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'torchvision.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'torchvision._C' extension
gcc -pthread -B /home/shikhar/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shikhar/Documents/vision-org/torchvision/csrc -I/home/shikhar/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/shikhar/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/shikhar/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/home/shikhar/anaconda3/include/python3.6m -c /home/shikhar/Documents/vision-org/torchvision/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/home/shikhar/Documents/vision-org/torchvision/csrc/vision.o -DTORCH_EXTENSION_NAME=_C -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/shikhar/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/shikhar/Documents/vision-org/torchvision/csrc -I/home/shikhar/anaconda3/lib/python3.6/site-packages/torch/lib/include -I/home/shikhar/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -I/home/shikhar/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -I/home/shikhar/anaconda3/include/python3.6m -c /home/shikhar/Documents/vision-org/torchvision/csrc/cpu/ROIAlign_cpu.cpp -o build/temp.linux-x86_64-3.6/home/shikhar/Documents/vision-org/torchvision/csrc/cpu/ROIAlign_cpu.o -DTORCH_EXTENSION_NAME=_C -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/shikhar/Documents/vision-org/torchvision/csrc/cpu/ROIAlign_cpu.cpp:226:66: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   AT_ASSERT(!input.type().is_cuda(), "input must be a CPU tensor");
                                                                  ^
/home/shikhar/Documents/vision-org/torchvision/csrc/cpu/ROIAlign_cpu.cpp:227:64: error: macro "AT_ASSERT" passed 2 arguments, but takes just 1
   AT_ASSERT(!rois.type().is_cuda(), "rois must be a CPU tensor");
                                                                ^
/home/shikhar/Documents/vision-org/torchvision/csrc/cpu/ROIAlign_cpu.cpp: In function ‘at::Tensor ROIAlign_forward_cpu(const at::Tensor&, const at::Tensor&, float, int, int, int)’:
/home/shikhar/Documents/vision-org/torchvision/csrc/cpu/ROIAlign_cpu.cpp:226:3: error: ‘AT_ASSERT’ was not declared in this scope
   AT_ASSERT(!input.type().is_cuda(), "input must be a CPU tensor");
   ^
error: command 'gcc' failed with exit status 1

```

**Comment by fmassa** [comment]
Ok, this is due to a recent change in PyTorch that modified the behavior of `AT_ASSERT` as you can see in https://github.com/pytorch/pytorch/pull/7104

I believe you can replace `AT_ASSERT` with `AT_CHECK` and it should compile.

And sorry for the troubles getting this branch to compile, as you can see PyTorch is evolving quite fast!

**Comment by xssChauhan** [comment]
I'll do the changes.

**Comment by xssChauhan** [comment]
Hey @fmassa 
torchvision is now successfully compiling, but here's the issue that i am facing now:

Even the successful compilation does not seem to add `layers` or `_C` modules to torchvision.

Here are the steps that i took:

- Install pytorch from source using the `master` branch and `no cuda` support.
- Replace all the occurences of `AT_ASSERT` with `AT_CHECK` in `nms_cpu.cpp` and `ROIAlign_cpu.cpp`.
- Install torchvision from source using `layers` branch

The build process throws no error.
In the shell:
image

Here are a couple of implementation details:

- Using a conda environment
- The build folder seems to have the compiled extension and the layers module
image

- I dont know if it is relevant, but installing pytorch and vision from source has different effects
image

- I have tried manually copying the contents of the build folder to the environment. The `_C` extension, is thus present in the environment package, but still does not appear in the terminal.


How can i fix this? Would be grateful for the help.

**Comment by xssChauhan** [comment]
@fmassa My bad. `from torchvision import pytorch` seemed to do the trick. Thank you.

**Comment by fmassa** [comment]
@xssChauhan is this ready for review? Did you manage to perform the gradcheck?

**Comment by xssChauhan** [comment]
@fmassa The branch is currently not passing the gradcheck. I've been working on finding the issue. 

My code is referenced from Caffe2 and vision's implementation of the same.
I recently stumbled upon [this](https://github.com/AceCoooool/RoIAlign-RoIPool-pytorch/blob/master/roialign/roi_align.py) implementation that references `caffe2` as well. Using the same parameters as in the link to run the gradcheck.

**Comment by varunagrawal** [comment]
Since this PR seems to be abandoned, I have taken the liberty to add the backwards pass for CPU in #630.

**Comment by fmassa** [comment]
Closing in favor of #630

**Pull request closed without merging**
